//! pcsx2_common_rs — Rust reimplementation of PCSX2's `common/` library.
//!
//! This crate is consumed by the C++ PCSX2 core via C ABI (extern "C").
//! Build produces a static library (`libpcsx2_common_rs.a` / `.lib`) that
//! CMake links into the main PCSX2 binary. The corresponding C++ header
//! (`pcsx2_common_rs.h`) is auto-generated by `cbindgen` (see `build.rs`).
//!
//! Conventions:
//! - Pure-Rust logic in normal `pub fn` (idiomatic Rust).
//! - FFI surface in `#[no_mangle] pub extern "C" fn` with `*const c_char`
//!   or `*mut c_void` for strings and opaque handles.
//! - C++ owns all allocations; Rust never frees memory the C++ side gave
//!   us, and vice versa. Buffers passed across the boundary have explicit
//!   size arguments.
//!
//! Module coverage: ~54 files ported from PCSX2's `common/` (leaf utilities,
//! string/path, file system, logging, settings, threading, host sys, format,
//! OS-specific). The x86 JIT emitter (`common/emitter/*`) stays in C++.

#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    unused_imports,
    unused_variables,
    clippy::all,
)]

// ============================================================================
// Phase 1: leaf utilities
// ============================================================================
pub mod bit_utils;
pub mod byte_swap;
pub mod easing;
pub mod enum_ops;
pub mod hash_combine;
pub mod heap_array;
pub mod heterogeneous_containers;
pub mod lru_cache;
pub mod md5_digest;
pub mod pcsx2_defs;
pub mod pcsx2_types;
pub mod scoped_guard;
pub mod spsc_queue;
pub mod single_register_types;
pub mod small_string;
pub mod vector_intrin;
pub mod wrapped_mem_copy;
pub mod x86_emitter; // proof-of-concept JIT emitter (iced-x86 backend)
#[cfg(target_arch = "x86_64")]
pub mod cpu_features; // CPUID-based feature detection via raw-cpuid

// ============================================================================
// Phase 2: assertions + memory primitives + alignment
// ============================================================================
pub mod assertions;
pub mod aligned_malloc;
pub mod fast_jmp;
pub mod fast_jmp_asm; // stub note for FastJmp.asm deferral

// ============================================================================
// Phase 3: error + progress + concurrency primitives
// ============================================================================
pub mod crash_handler;
pub mod error;
pub mod progress_callback;
pub mod readback_spin_manager;
pub mod semaphore_impl;
pub mod threading;

// ============================================================================
// Phase 4: string + path + file system
// ============================================================================
pub mod file_system;
pub mod path;
pub mod string_util;

// ============================================================================
// Phase 5: host system
// ============================================================================
pub mod host_sys;
#[cfg(target_os = "linux")]
pub mod linux_host_sys;
// windows_host_sys — memory protection + shared memory.
// Guarded by `#[cfg(target_os = "windows")]` inside the module.
#[cfg(target_os = "windows")]
pub mod windows_host_sys;

// Thin cross-platform FFI shim. Exposes `pcsx2_host_*` symbols on
// every platform using the safe `host_sys` API. Avoids per-platform
// duplication and the windows-sys feature gate headaches.
pub mod host_sys_ffi;

// ============================================================================
// Phase 6: logging
// ============================================================================
pub mod console;

// ============================================================================
// Phase 7: settings (MemorySettingsInterface impl, SettingsInterface trait)
// ============================================================================
pub mod memory_settings_interface;
pub mod settings_interface;
pub mod settings_wrapper;

// ============================================================================
// Phase 8: memory interface (MIPS recompiler ↔ EE/IOP/VU memory)
// ============================================================================
pub mod memory_interface;

// ============================================================================
// Phase 9: format/codec — image, http_downloader, zip, dynamic_library
// ============================================================================
pub mod dynamic_library;
pub mod http_downloader;
pub mod image;
pub mod stack_walker;
pub mod texture_decompress;
pub mod wav_writer;
pub mod window_info;
pub mod yaml;
pub mod zip_helpers;

// ============================================================================
// Phase 10: misc (timer, perf, fp_control)
// ============================================================================
pub mod fp_control;
pub mod perf;
#[cfg(target_os = "linux")]
pub mod perf_event_counter;
pub mod timer;

// ============================================================================
// Phase 11: OS-specific (cocoa/misc, threads, platform misc)
// ============================================================================
#[cfg(target_os = "macos")]
pub mod cocoa_tools;
#[cfg(target_os = "macos")]
pub mod darwin_misc;
#[cfg(target_os = "macos")]
pub mod darwin_threads;
#[cfg(target_os = "linux")]
pub mod linux_misc;
#[cfg(target_os = "linux")]
pub mod linux_threads;
#[cfg(target_os = "windows")]
pub mod windows_misc;
#[cfg(target_os = "windows")]
pub mod redtape;
#[cfg(target_os = "windows")]
pub mod windows_threads;

// ============================================================================
// FFI exports aggregated here. Each submodule declares its own
// `#[no_mangle] pub extern "C" fn pcsx2_xxx` functions; cbindgen picks
// them up via `pub use` re-export below.
// ============================================================================

// Phase 1
pub use bit_utils::*;
pub use byte_swap::*;
pub use easing::*;
pub use enum_ops::*;
pub use hash_combine::*;
pub use heap_array::*;
pub use heterogeneous_containers::*;
pub use lru_cache::*;
pub use md5_digest::*;
pub use pcsx2_defs::*;
pub use pcsx2_types::*;
pub use scoped_guard::*;
pub use single_register_types::*;
pub use small_string::*;
pub use vector_intrin::*;
pub use wrapped_mem_copy::*;
#[cfg(target_arch = "x86_64")]
pub use cpu_features::*;

// Phase 2
pub use assertions::*;
pub use aligned_malloc::*;
pub use fast_jmp::*;

// Phase 3
pub use crash_handler::*;
pub use error::*;
pub use progress_callback::*;
pub use readback_spin_manager::*;
pub use semaphore_impl::*;
pub use threading::*;

// Phase 4
pub use file_system::*;
pub use path::*;
pub use string_util::*;

// Phase 5 — host_sys safe API + cross-platform FFI shim
pub use host_sys::*;
pub use host_sys_ffi::*;
// linux_host_sys disabled for now (cross-platform shim covers it)
// #[cfg(target_os = "linux")]
// pub use linux_host_sys::*;
// windows_host_sys disabled for now (cross-platform shim covers it)
// Phase 6
pub use console::*;

// Phase 7
pub use memory_settings_interface::*;
pub use settings_interface::*;
pub use settings_wrapper::*;

// Phase 8
pub use memory_interface::*;

// Phase 9
pub use dynamic_library::*;
pub use http_downloader::*;
pub use image::*;
pub use stack_walker::*;
pub use texture_decompress::*;
pub use wav_writer::*;
pub use window_info::*;
pub use yaml::*;
pub use zip_helpers::*;
pub use wav_writer::*;
pub use window_info::*;
pub use yaml::*;
pub use zip_helpers::*;

// Phase 10
pub use fp_control::*;
pub use perf::*;
pub use timer::*;

// Phase 11
#[cfg(target_os = "macos")]
pub use cocoa_tools::*;
#[cfg(target_os = "macos")]
pub use darwin_misc::*;
#[cfg(target_os = "macos")]
pub use darwin_threads::*;
#[cfg(target_os = "linux")]
pub use linux_misc::*;
#[cfg(target_os = "linux")]
pub use linux_threads::*;
#[cfg(target_os = "windows")]
pub use windows_misc::*;
#[cfg(target_os = "windows")]
pub use redtape::*;
#[cfg(target_os = "windows")]
pub use windows_threads::*;