//! Idiomatic Rust translation of the PCSX2 ARM64 dynarec subsystem.
//!
//! This module consolidates the contents of the C/C++ sources
//! `arm64/AsmHelpers.{h,cpp}`, `arm64/RecStubs.cpp`, `arm64/Vif_Dynarec.cpp`,
//! `arm64/Vif_UnpackNEON.{h,cpp}` into a single Rust 2021 module that is
//! API-compatible at the level of the dynarec entry points.  It mirrors the
//! role of the original code: providing ARM64 assembly helpers, a constant
//! pool, a `VifUnpackNEON_Dynarec` compiler, and the VIF unpacking routines
//! driven by the native VIXL macro-assembler.
//!
//! Only the `std` crate is used.  No filesystem, no networking, no panicking
//! FFI — the code is structured so it can be linked into a real dynarec
//! binary later by swapping the placeholder vixl types for the real ones.

// ---------------------------------------------------------------------------
// Primitive aliases
// ---------------------------------------------------------------------------

pub type s8 = i8;
pub type s16 = i16;
pub type s32 = i32;
pub type s64 = i64;

pub type u8 = std::primitive::u8;
pub type u16 = std::primitive::u16;
pub type u32 = std::primitive::u32;
pub type u64 = std::primitive::u64;
pub type u128 = u128_value;
pub type uptr = usize;
pub type uint = std::primitive::u32;
pub type sptr = isize;

/// Minimal 128-bit value used by the constant pool literal cache.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Default, Hash)]
pub struct u128_value {
    pub lo: u64,
    pub hi: u64,
}

impl u128_value {
    pub const fn new(lo: u64, hi: u64) -> Self {
        Self { lo, hi }
    }

    pub fn from_64(v: u64) -> Self {
        Self { lo: v, hi: 0 }
    }

    pub fn as_bytes(&self) -> [u8; 16] {
        let mut out = [0u8; 16];
        out[0..8].copy_from_slice(&self.lo.to_le_bytes());
        out[8..16].copy_from_slice(&self.hi.to_le_bytes());
        out
    }
}

// ---------------------------------------------------------------------------
// Logging stubs (mimic common/Console and common/Perf).
// ---------------------------------------------------------------------------

#[derive(Default)]
pub struct PerfSection {
    pub name: String,
}

impl PerfSection {
    pub fn register(&self, _base: *const u8, _size: usize, _key: u32) {}
}

pub struct Perf {
    pub vif: PerfSection,
    pub any: PerfSection,
}

pub mod perf {
    use super::Perf;
    // Single global instance (constructed lazily in `init`).
    static mut PERF: Perf = Perf {
        vif: super::PerfSection { name: String::new() },
        any: super::PerfSection { name: String::new() },
    };

    pub fn vif() -> &'static mut super::PerfSection {
        unsafe { &mut PERF.vif }
    }

    pub fn any() -> &'static mut super::PerfSection {
        unsafe { &mut PERF.any }
    }
}

pub mod console {
    use std::sync::Mutex;

    static STDERR_LOCK: Mutex<()> = Mutex::new(());

    pub struct ConsoleSink;

    impl ConsoleSink {
        pub fn error(&self, fmt: &str) {
            let _g = STDERR_LOCK.lock().unwrap();
            eprint!("[error] ");
            eprintln!("{}", fmt);
        }

        pub fn warning(&self, fmt: &str) {
            let _g = STDERR_LOCK.lock().unwrap();
            eprint!("[warning] ");
            eprintln!("{}", fmt);
        }
    }

    pub static Console: ConsoleSink = ConsoleSink;
}

pub mod devcon {
    use std::sync::Mutex;

    static STDOUT_LOCK: Mutex<()> = Mutex::new(());

    pub struct DevCon;

    impl DevCon {
        pub fn write_ln(&self, fmt: &str) {
            let _g = STDOUT_LOCK.lock().unwrap();
            print!("[devcon] ");
            println!("{}", fmt);
        }
    }

    pub static DEV_CON: DevCon = DevCon;
}

pub mod host_sys {
    pub fn begin_code_write() {}
    pub fn end_code_write() {}
    pub fn flush_instruction_cache(_ptr: *mut u8, _size: usize) {}
}

pub fn px_assert(cond: bool) {
    debug_assert!(cond);
}

pub fn px_assert_msg(cond: bool, msg: &str) {
    if !cond {
        eprintln!("px_assert_msg failed: {}", msg);
    }
}

pub fn px_fail_rel(msg: &str) -> ! {
    eprintln!("pxFailRel: {}", msg);
    std::process::abort();
}

pub fn assume(cond: bool) {
    debug_assert!(cond);
}

pub fn align_up_pow2(value: u32, alignment: u32) -> u32 {
    (value + alignment - 1) & !(alignment - 1)
}

// ---------------------------------------------------------------------------
// VIXL placeholder types.
//
// The real VIXL macro-assembler is a complex C++ library.  In this Rust
// translation we declare thin wrapper types and method signatures sufficient
// for the dynarec code paths we care about.  A complete port would replace
// these with bindings generated by `bindgen` or by an in-tree `vixl` crate.
// ---------------------------------------------------------------------------

pub mod a64 {
    use super::*;

    pub type MemOperand = MemOperandKind;
    pub type Register = GpRegister;
    pub type WRegister = GpRegister;
    pub type VRegister = VectorRegister;
    pub type CPURegister = CpuRegister;
    pub type Condition = u8;

    // Placeholder constants for the vixl aarch64 conditions.
    pub const EQ: Condition = 0;
    pub const NE: Condition = 1;
    pub const CS: Condition = 2;
    pub const HS: Condition = 2;
    pub const CC: Condition = 3;
    pub const LO: Condition = 3;
    pub const MI: Condition = 4;
    pub const PL: Condition = 5;
    pub const VS: Condition = 6;
    pub const VC: Condition = 7;
    pub const HI: Condition = 8;
    pub const LS: Condition = 9;
    pub const GE: Condition = 10;
    pub const LT: Condition = 11;
    pub const GT: Condition = 12;
    pub const LE: Condition = 13;
    pub const AL: Condition = 14;
    pub const NV: Condition = 15;

    pub fn invert_condition(c: Condition) -> Condition {
        // Roughly: invert the lower three bits with respect to AL/NV.
        match c & 0xF {
            14 | 15 => c,
            x => x ^ 0x1,
        }
    }

    pub const COMPARE_BRANCH_TYPE: u8 = 0;
    pub const COND_BRANCH_TYPE: u8 = 1;
    pub const COMPARE_BRANCH_TYPE_: u8 = COMPARE_BRANCH_TYPE;
    pub const COND_BRANCH_TYPE_: u8 = COND_BRANCH_TYPE;
    pub type CompareBranchType = ();
    pub type CondBranchType = ();

    pub fn is_int26(v: i64) -> bool {
        v >= -(1i64 << 25) && v < (1i64 << 25)
    }

    pub fn is_int21(v: i64) -> bool {
        v >= -(1i64 << 20) && v < (1i64 << 20)
    }

    pub const NO_SHIFT: u8 = 0;
    pub const OFFSET: u8 = 0;

    /// A 32-bit ARM64 general-purpose register reference.
    #[derive(Clone, Copy)]
    pub struct GpRegister {
        pub code: u8,
    }

    impl GpRegister {
        pub const fn new(code: u8) -> Self {
            Self { code }
        }
        pub const fn get_code(&self) -> u8 { self.code }
        pub const fn is_x(&self) -> bool { self.code < 32 }
        pub const fn is_valid(&self) -> bool { self.code < 32 }
        pub const fn x(&self) -> GpRegister { GpRegister::new(self.code) }
    }

    /// A SIMD/FP vector register reference.
    #[derive(Clone, Copy)]
    pub struct VectorRegister {
        pub code: u8,
        pub size: u8,
        pub lanes: u8,
    }

    impl VectorRegister {
        pub const fn new(code: u8, size: u8, lanes: u8) -> Self {
            Self { code, size, lanes }
        }
        pub const fn get_code(&self) -> u8 { self.code }
        pub const fn v16b(&self) -> VectorRegister { VectorRegister::new(self.code, 128, 16) }
        pub const fn v8h(&self) -> VectorRegister { VectorRegister::new(self.code, 64, 8) }
        pub const fn v4s(&self) -> VectorRegister { VectorRegister::new(self.code, 64, 4) }
        pub const fn v2d(&self) -> VectorRegister { VectorRegister::new(self.code, 64, 2) }
        pub const fn v8b(&self) -> VectorRegister { VectorRegister::new(self.code, 64, 8) }
        pub const fn v4h(&self) -> VectorRegister { VectorRegister::new(self.code, 64, 4) }
        pub const fn s(&self) -> GpRegister { GpRegister::new(self.code) }
        pub const fn d(&self) -> GpRegister { GpRegister::new(self.code) }
        pub const fn q(&self) -> VectorRegister { *self }
        pub const fn b(&self) -> GpRegister { GpRegister::new(self.code) }
        pub const fn h(&self) -> GpRegister { GpRegister::new(self.code) }
        pub const fn w(&self) -> GpRegister { GpRegister::new(self.code) }
        pub const fn x(&self) -> GpRegister { GpRegister::new(self.code) }
    }

    /// A CPU register (general or vector).
    #[derive(Clone, Copy)]
    pub enum CpuRegister {
        Gp(GpRegister),
        Vec(VectorRegister),
    }

    impl CpuRegister {
        pub const fn from_gp(r: GpRegister) -> Self { Self::Gp(r) }
        pub const fn from_vec(r: VectorRegister) -> Self { Self::Vec(r) }
    }

    /// Memory operand variants matching the VIXL memory addressing modes used
    /// by the dynarec.
    #[derive(Clone, Copy)]
    pub enum MemOperandKind {
        Offset { base: GpRegister, offset: i64, addr_mode: u8 },
        PostIndex { base: GpRegister, offset: i64 },
        PreIndex { base: GpRegister, offset: i64 },
    }

    impl MemOperandKind {
        pub const fn new(base: GpRegister) -> Self {
            MemOperandKind::Offset { base, offset: 0, addr_mode: OFFSET }
        }
        pub const fn new_offset(base: GpRegister, offset: i64, addr_mode: u8) -> Self {
            MemOperandKind::Offset { base, offset, addr_mode }
        }
        pub fn get_base_register(&self) -> GpRegister {
            match self {
                MemOperandKind::Offset { base, .. } => *base,
                MemOperandKind::PostIndex { base, .. } => *base,
                MemOperandKind::PreIndex { base, .. } => *base,
            }
        }
        pub fn get_offset(&self) -> i64 {
            match self {
                MemOperandKind::Offset { offset, .. } => *offset,
                MemOperandKind::PostIndex { offset, .. } => *offset,
                MemOperandKind::PreIndex { offset, .. } => *offset,
            }
        }
        pub fn get_addr_mode(&self) -> u8 {
            match self {
                MemOperandKind::Offset { addr_mode, .. } => *addr_mode,
                MemOperandKind::PostIndex { .. } => 1,
                MemOperandKind::PreIndex { .. } => 2,
            }
        }
        pub fn get_shift(&self) -> u8 { NO_SHIFT }
    }

    pub const POST_INDEX: u8 = 1;
    pub const PRE_INDEX: u8 = 2;

    /// Placeholder for a forward label.
    pub type Label = usize;

    pub struct Instruction;
    impl Instruction {
        pub fn is_valid_imm_pc_offset(_branch_type: u8, _offset: i64) -> bool { true }
    }

    /// A single-emission check scope guarding the macro-assembler.
    pub struct SingleEmissionCheckScope<'a> { pub _asm: &'a MacroAssembler }
    pub struct MacroEmissionCheckScope<'a> { pub _asm: &'a MacroAssembler }

    impl<'a> Drop for SingleEmissionCheckScope<'a> { fn drop(&mut self) {} }
    impl<'a> Drop for MacroEmissionCheckScope<'a> { fn drop(&mut self) {} }

    // The well-known ARM64 general purpose register aliases.
    pub const W0: GpRegister = GpRegister::new(0);
    pub const W1: GpRegister = GpRegister::new(1);
    pub const W2: GpRegister = GpRegister::new(2);
    pub const W3: GpRegister = GpRegister::new(3);
    pub const W4: GpRegister = GpRegister::new(4);
    pub const W16: GpRegister = GpRegister::new(16);
    pub const W17: GpRegister = GpRegister::new(17);
    pub const WZR: GpRegister = GpRegister::new(31);

    pub const X0: GpRegister = GpRegister::new(0);
    pub const X1: GpRegister = GpRegister::new(1);
    pub const X2: GpRegister = GpRegister::new(2);
    pub const X3: GpRegister = GpRegister::new(3);
    pub const X16: GpRegister = GpRegister::new(16);
    pub const X17: GpRegister = GpRegister::new(17);
    pub const X19: GpRegister = GpRegister::new(19);
    pub const X20: GpRegister = GpRegister::new(20);
    pub const X21: GpRegister = GpRegister::new(21);
    pub const X22: GpRegister = GpRegister::new(22);
    pub const X23: GpRegister = GpRegister::new(23);
    pub const X24: GpRegister = GpRegister::new(24);
    pub const X25: GpRegister = GpRegister::new(25);
    pub const X26: GpRegister = GpRegister::new(26);
    pub const X27: GpRegister = GpRegister::new(27);
    pub const X28: GpRegister = GpRegister::new(28);
    pub const X29: GpRegister = GpRegister::new(29);
    pub const X30: GpRegister = GpRegister::new(30);
    pub const XLR: GpRegister = GpRegister::new(30);
    pub const XSP: GpRegister = GpRegister::new(31);
    pub const XZR: GpRegister = GpRegister::new(31);
    pub const SP: GpRegister = XSP;

    // Vector register aliases.
    pub const Q0: VectorRegister = VectorRegister::new(0, 128, 16);
    pub const Q1: VectorRegister = VectorRegister::new(1, 128, 16);
    pub const Q2: VectorRegister = VectorRegister::new(2, 128, 16);
    pub const Q3: VectorRegister = VectorRegister::new(3, 128, 16);
    pub const Q4: VectorRegister = VectorRegister::new(4, 128, 16);
    pub const Q5: VectorRegister = VectorRegister::new(5, 128, 16);
    pub const Q6: VectorRegister = VectorRegister::new(6, 128, 16);
    pub const Q7: VectorRegister = VectorRegister::new(7, 128, 16);
    pub const Q29: VectorRegister = VectorRegister::new(29, 128, 16);
    pub const Q30: VectorRegister = VectorRegister::new(30, 128, 16);
    pub const Q31: VectorRegister = VectorRegister::new(31, 128, 16);

    pub const D0: GpRegister = GpRegister::new(0);
    pub const D8: GpRegister = GpRegister::new(8);
    pub const D9: GpRegister = GpRegister::new(9);
    pub const D10: GpRegister = GpRegister::new(10);
    pub const D11: GpRegister = GpRegister::new(11);
    pub const D12: GpRegister = GpRegister::new(12);
    pub const D13: GpRegister = GpRegister::new(13);
    pub const D14: GpRegister = GpRegister::new(14);
    pub const D15: GpRegister = GpRegister::new(15);

    pub const WZR_CONST: GpRegister = WZR;
    pub const wzr: GpRegister = WZR;

    // The vixl `w0..w31` and `x0..x31` style constants.
    macro_rules! gp_const {
        ($($name:ident = $code:expr),+ $(,)?) => {
            $(pub const $name: GpRegister = GpRegister::new($code);)+
        };
    }

    gp_const!(
        w0 = 0, w1 = 1, w2 = 2, w3 = 3, w4 = 4, w5 = 5, w6 = 6, w7 = 7,
        w8 = 8, w9 = 9, w10 = 10, w11 = 11, w12 = 12, w13 = 13, w14 = 14, w15 = 15,
        w16 = 16, w17 = 17, w18 = 18, w19 = 19, w20 = 20, w21 = 21, w22 = 22, w23 = 23,
        w24 = 24, w25 = 25, w26 = 26, w27 = 27, w28 = 28, w29 = 29, w30 = 30, w31 = 31,
        x0 = 0, x1 = 1, x2 = 2, x3 = 3, x4 = 4, x5 = 5, x6 = 6, x7 = 7,
        x8 = 8, x9 = 9, x10 = 10, x11 = 11, x12 = 12, x13 = 13, x14 = 14, x15 = 15,
        x16 = 16, x17 = 17, x18 = 18, x19 = 19, x20 = 20, x21 = 21, x22 = 22, x23 = 23,
        x24 = 24, x25 = 25, x26 = 26, x27 = 27, x28 = 28, x29 = 29, x30 = 30, x31 = 31,
    );

    macro_rules! vec_const {
        ($($name:ident = $code:expr),+ $(,)?) => {
            $(pub const $name: VectorRegister = VectorRegister::new($code, 128, 16);)+
        };
    }

    vec_const!(
        q0 = 0, q1 = 1, q2 = 2, q3 = 3, q4 = 4, q5 = 5, q6 = 6, q7 = 7,
        q8 = 8, q9 = 9, q10 = 10, q11 = 11, q12 = 12, q13 = 13, q14 = 14, q15 = 15,
        q16 = 16, q17 = 17, q18 = 18, q19 = 19, q20 = 20, q21 = 21, q22 = 22, q23 = 23,
        q24 = 24, q25 = 25, q26 = 26, q27 = 27, q28 = 28, q29 = 29, q30 = 30, q31 = 31,
    );

    /// Placeholder for the VIXL macro-assembler.  Records every emitted
    /// instruction as a debug-only trace string; the real back-end would
    /// encode bytes into a code buffer.
    #[derive(Default)]
    pub struct MacroAssembler {
        pub code: Vec<u8>,
        pub log: Vec<String>,
    }

    impl MacroAssembler {
        pub fn new(_buf: *mut u8, _capacity: usize) -> Self {
            Self::default()
        }

        pub fn finalize_code(&mut self) {}
        pub fn get_size_of_code_generated(&self) -> usize { self.code.len() }
        pub fn get_cursor_offset(&self) -> usize { self.code.len() }

        // -- Instruction emitters (no-op loggers) -----------------------------

        pub fn mov(&mut self, _dst: impl Operand, _src: impl Operand) { self.log.push("mov".into()); }
        pub fn br(&mut self, _reg: GpRegister) { self.log.push("br".into()); }
        pub fn blr(&mut self, _reg: GpRegister) { self.log.push("blr".into()); }
        pub fn b(&mut self, _off: i64) { self.log.push("b".into()); }
        pub fn b_cond(&mut self, _off: i64, _cond: Condition) { self.log.push("b.<cond>".into()); }
        pub fn bl(&mut self, _off: i64) { self.log.push("bl".into()); }
        pub fn cbz(&mut self, _reg: GpRegister, _lbl: &Label) { self.log.push("cbz".into()); }
        pub fn cbnz(&mut self, _reg: GpRegister, _off: i64) { self.log.push("cbnz".into()); }
        pub fn bind(&mut self, _lbl: &mut Label) { self.log.push("bind".into()); }

        pub fn add(&mut self, dst: impl Operand, src1: impl Operand, src2: impl Operand) {
            let _ = (dst, src1, src2);
            self.log.push("add".into());
        }
        pub fn sub(&mut self, dst: GpRegister, src1: GpRegister, src2: GpRegister) {
            let _ = (dst, src1, src2);
            self.log.push("sub".into());
        }
        pub fn adrp(&mut self, _reg: GpRegister, _off: i64) { self.log.push("adrp".into()); }
        pub fn orr(&mut self, _dst: GpRegister, _src1: GpRegister, _src2: impl Operand) { self.log.push("orr".into()); }
        pub fn ldr(&mut self, _dst: impl Operand, _mem: impl Operand) { self.log.push("ldr".into()); }
        pub fn ldr_imm(&mut self, _dst: impl Operand, _mem: impl Operand) { self.log.push("ldr".into()); }
        pub fn str(&mut self, _src: impl Operand, _mem: impl Operand) { self.log.push("str".into()); }
        pub fn ldp(&mut self, _a: impl Operand, _b: impl Operand, _mem: impl Operand) { self.log.push("ldp".into()); }
        pub fn stp(&mut self, _a: impl Operand, _b: impl Operand, _mem: impl Operand) { self.log.push("stp".into()); }
        pub fn ldrh(&mut self, _dst: GpRegister, _mem: impl Operand) { self.log.push("ldrh".into()); }
        pub fn lsl(&mut self, _dst: GpRegister, _src: GpRegister, _shift: u32) { self.log.push("lsl".into()); }
        pub fn lsr(&mut self, _dst: GpRegister, _src: GpRegister, _shift: u32) { self.log.push("lsr".into()); }
        pub fn shl(&mut self, _dst: impl Operand, _src: impl Operand, _shift: u32) { self.log.push("shl".into()); }
        pub fn ushl(&mut self, _dst: impl Operand, _src: impl Operand, _shift: u32) { self.log.push("ushl".into()); }
        pub fn sshl(&mut self, _dst: impl Operand, _src: impl Operand, _shift: u32) { self.log.push("sshl".into()); }
        pub fn sshll(&mut self, _dst: impl Operand, _src: impl Operand, _shift: u32) { self.log.push("sshll".into()); }
        pub fn ushll(&mut self, _dst: impl Operand, _src: impl Operand, _shift: u32) { self.log.push("ushll".into()); }
        pub fn ushr(&mut self, _dst: impl Operand, _src: impl Operand, _shift: u32) { self.log.push("ushr".into()); }
        pub fn sshr(&mut self, _dst: impl Operand, _src: impl Operand, _shift: u32) { self.log.push("sshr".into()); }
        pub fn dup(&mut self, _dst: impl Operand, _src: impl Operand) { self.log.push("dup".into()); }
        pub fn dup_lane(&mut self, _dst: impl Operand, _src: impl Operand, _lane: u32) { self.log.push("dup.lane".into()); }
        pub fn ins(&mut self, _dst: impl Operand, _idx: u32, _src: impl Operand) { self.log.push("ins".into()); }
        pub fn ins_imm(&mut self, _dst: impl Operand, _idx: u32, _src: GpRegister) { self.log.push("ins".into()); }
        pub fn movi(&mut self, _dst: impl Operand, _imm: i64) { self.log.push("movi".into()); }
        pub fn tbl(&mut self, _dst: impl Operand, _src: impl Operand) { self.log.push("tbl".into()); }
        pub fn tbl3(&mut self, _dst: impl Operand, _a: impl Operand, _b: impl Operand) { self.log.push("tbl3".into()); }
        pub fn st1(&mut self, _src: impl Operand, _lane: u32, _mem: impl Operand) { self.log.push("st1".into()); }
        pub fn and(&mut self, _dst: impl Operand, _a: impl Operand, _b: impl Operand) { self.log.push("and".into()); }
        pub fn orr_v(&mut self, _dst: impl Operand, _a: impl Operand, _b: impl Operand) { self.log.push("orr".into()); }
        pub fn ret(&mut self) { self.log.push("ret".into()); }

        // is_imm_add_sub / is_imm_logical helpers for armMoveAddressToReg.
        pub fn is_imm_add_sub(_imm: u32) -> bool { true }
        pub fn is_imm_logical(_imm: u32, _width: u32) -> bool { true }
    }

    /// Trait that the vixl types (GpRegister, VectorRegister, u64, MemOperand)
    /// implement so we can pass them to the macro-assembler emitters.
    pub trait Operand: Copy {}
    impl Operand for GpRegister {}
    impl Operand for VectorRegister {}
    impl Operand for u64 {}
    impl Operand for MemOperandKind {}
    impl Operand for CpuRegister {}
    impl Operand for i64 {}
    impl Operand for u32 {}
}

// ---------------------------------------------------------------------------
// Thread-local state for the dynarec context.
// ---------------------------------------------------------------------------

use std::cell::UnsafeCell;
use std::sync::Once;

thread_local! {
    static ARM_CTX: UnsafeCell<ArmContext> = UnsafeCell::new(ArmContext::new());
}

struct ArmContext {
    asm: Option<a64::MacroAssembler>,
    asm_ptr: *mut u8,
    asm_capacity: usize,
    constant_pool: Option<*mut ArmConstantPool>,
}

impl ArmContext {
    const fn new() -> Self {
        Self {
            asm: None,
            asm_ptr: std::ptr::null_mut(),
            asm_capacity: 0,
            constant_pool: None,
        }
    }
}

unsafe impl Send for ArmContext {}
unsafe impl Sync for ArmContext {}

fn with_ctx<F, R>(f: F) -> R
where
    F: FnOnce(&mut ArmContext) -> R,
{
    ARM_CTX.with(|c| {
        let ctx = c.get();
        // SAFETY: this is a thread_local cell, only this thread accesses it.
        f(unsafe { &mut *ctx })
    })
}

// Convenience accessors matching the C++ globals.
pub fn arm_asm() -> Option<&'static mut a64::MacroAssembler> {
    with_ctx(|c| c.asm.as_mut().map(|a| {
        // SAFETY: caller must ensure no aliasing across the asm reference.
        unsafe { &mut *(a as *mut a64::MacroAssembler) }
    }))
}

pub fn arm_asm_ptr() -> *mut u8 { with_ctx(|c| c.asm_ptr) }
pub fn arm_asm_capacity() -> usize { with_ctx(|c| c.asm_capacity) }
pub fn arm_constant_pool() -> Option<&'static mut ArmConstantPool> {
    with_ctx(|c| c.constant_pool.and_then(|p| if p.is_null() { None } else { Some(unsafe { &mut *p }) }))
}

// ---------------------------------------------------------------------------
// Register macros re-implemented as inline functions and constants.
// ---------------------------------------------------------------------------

pub const fn rw_ret() -> a64::GpRegister { a64::W0 }
pub const fn rx_ret() -> a64::GpRegister { a64::X0 }
pub const fn rq_ret() -> a64::VectorRegister { a64::Q0 }
pub const fn rx_arg1() -> a64::GpRegister { a64::X0 }
pub const fn rx_arg2() -> a64::GpRegister { a64::X1 }
pub const fn rx_arg3() -> a64::GpRegister { a64::X2 }
pub const fn rx_arg4() -> a64::GpRegister { a64::X3 }
pub const fn rx_vixl_scratch() -> a64::GpRegister { a64::X16 }
pub const fn rw_vixl_scratch() -> a64::GpRegister { a64::W16 }
pub const fn r_scratch_addr() -> a64::GpRegister { a64::X17 }

pub const fn rq_scratch() -> a64::VectorRegister { a64::Q30 }
pub const fn rq_scratch2() -> a64::VectorRegister { a64::Q31 }
pub const fn rq_scratch3() -> a64::VectorRegister { a64::Q29 }

pub const fn rq_scratch_i() -> a64::VectorRegister { a64::VectorRegister::new(30, 128, 16) }
pub const fn rq_scratch_f() -> a64::VectorRegister { a64::VectorRegister::new(30, 128, 4) }
pub const fn rq_scratch_d() -> a64::VectorRegister { a64::VectorRegister::new(30, 128, 2) }
pub const fn rq_scratch2_i() -> a64::VectorRegister { a64::VectorRegister::new(31, 128, 16) }
pub const fn rq_scratch2_f() -> a64::VectorRegister { a64::VectorRegister::new(31, 128, 4) }
pub const fn rq_scratch2_d() -> a64::VectorRegister { a64::VectorRegister::new(31, 128, 2) }

pub const SP_SCRATCH_OFFSET: u32 = 0;

// ---------------------------------------------------------------------------
// PCSX2 register arrays: armWRegister / armXRegister / armSRegister / ...
// ---------------------------------------------------------------------------

pub fn arm_w_register(n: i32) -> a64::GpRegister { a64::GpRegister::new(n as u8) }
pub fn arm_x_register(n: i32) -> a64::GpRegister { a64::GpRegister::new(n as u8) }
pub fn arm_s_register(n: i32) -> a64::VectorRegister { a64::VectorRegister::new(n as u8, 32, 4) }
pub fn arm_d_register(n: i32) -> a64::VectorRegister { a64::VectorRegister::new(n as u8, 64, 2) }
pub fn arm_q_register(n: i32) -> a64::VectorRegister { a64::VectorRegister::new(n as u8, 128, 16) }

// ---------------------------------------------------------------------------
// Block setup / teardown.
// ---------------------------------------------------------------------------

pub fn arm_set_asm_ptr(ptr: *mut u8, capacity: usize, pool: Option<&mut ArmConstantPool>) {
    with_ctx(|c| {
        debug_assert!(c.asm.is_none(), "arm_asm already set on this thread");
        c.asm_ptr = ptr;
        c.asm_capacity = capacity;
        c.constant_pool = pool.map(|p| p as *mut _);
    });
}

pub fn arm_align_asm_ptr() {
    with_ctx(|c| {
        const ALIGNMENT: usize = 16;
        let cur = c.asm_ptr as usize;
        let new = (cur + ALIGNMENT - 1) & !(ALIGNMENT - 1);
        let pad = new - cur;
        c.asm_capacity = c.asm_capacity.saturating_sub(pad);
        c.asm_ptr = new as *mut u8;
    });
}

pub fn arm_has_block() -> bool {
    with_ctx(|c| c.asm.is_some())
}

pub fn arm_get_current_code_pointer() -> *mut u8 {
    with_ctx(|c| unsafe {
        let off = c.asm.as_ref().map(|a| a.get_cursor_offset()).unwrap_or(0);
        c.asm_ptr.add(off)
    })
}

pub fn arm_get_asm_ptr() -> *mut u8 { with_ctx(|c| c.asm_ptr) }

pub fn arm_start_block() -> *mut u8 {
    arm_align_asm_ptr();
    host_sys::begin_code_write();
    let ptr = with_ctx(|c| {
        debug_assert!(c.asm.is_none());
        c.asm = Some(a64::MacroAssembler::new(c.asm_ptr, c.asm_capacity));
        c.asm_ptr
    });
    // Mirror the C++ behavior: reserve scratch register 31 / 17.
    if let Some(asm) = arm_asm() {
        let _ = asm; // would call GetScratchVRegisterList()->Remove(31) here
    }
    ptr
}

pub fn arm_end_block() -> *mut u8 {
    let (ptr, size) = with_ctx(|c| {
        let size = c.asm.as_ref().map(|a| a.get_size_of_code_generated()).unwrap_or(0);
        if let Some(mut asm) = c.asm.take() {
            asm.finalize_code();
        }
        let new_ptr = unsafe { c.asm_ptr.add(size) };
        c.asm_capacity = c.asm_capacity.saturating_sub(size);
        c.asm_ptr = new_ptr;
        (new_ptr, size)
    });
    host_sys::end_code_write();
    host_sys::flush_instruction_cache(ptr, size);
    ptr
}

pub fn arm_disassemble_and_dump_code(_ptr: *const u8, _size: usize) {
    console::Console.error("armDisassembleAndDumpCode: not implemented in Rust port");
}

// ---------------------------------------------------------------------------
// Branch / call / move helpers.
// ---------------------------------------------------------------------------

pub fn get_pc_displacement(current: *const u8, target: *const u8) -> i64 {
    let diff = (target as isize) - (current as isize);
    (diff >> 2) as i64
}

pub fn arm_emit_jmp(target: *const u8, force_inline: bool) {
    let mut displacement = get_pc_displacement(arm_get_current_code_pointer(), target);
    let mut use_blr = !a64::is_int26(displacement);
    if use_blr {
        if let Some(pool) = arm_constant_pool() {
            if !force_inline {
                if let Some(trampoline) = pool.get_jump_trampoline(target) {
                    displacement = get_pc_displacement(arm_get_current_code_pointer(), trampoline);
                    use_blr = !a64::is_int26(displacement);
                }
            }
        }
    }

    let asm = arm_asm().expect("no active block");
    if use_blr {
        asm.mov(rx_vixl_scratch(), target as u64);
        asm.br(rx_vixl_scratch());
    } else {
        asm.b(displacement);
    }
}

pub fn arm_emit_call(target: *const u8, force_inline: bool) {
    let mut displacement = get_pc_displacement(arm_get_current_code_pointer(), target);
    let mut use_blr = !a64::is_int26(displacement);
    if use_blr {
        if let Some(pool) = arm_constant_pool() {
            if !force_inline {
                if let Some(trampoline) = pool.get_jump_trampoline(target) {
                    displacement = get_pc_displacement(arm_get_current_code_pointer(), trampoline);
                    use_blr = !a64::is_int26(displacement);
                }
            }
        }
    }

    let asm = arm_asm().expect("no active block");
    if use_blr {
        asm.mov(rx_vixl_scratch(), target as u64);
        asm.blr(rx_vixl_scratch());
    } else {
        asm.bl(displacement);
    }
}

pub fn arm_emit_cbnz(reg: a64::GpRegister, target: *const u8) {
    let jump_distance = (target as isize) - (arm_get_current_code_pointer() as isize);
    if a64::Instruction::is_valid_imm_pc_offset(a64::COMPARE_BRANCH_TYPE_, jump_distance as i64 / 4) {
        let asm = arm_asm().expect("no active block");
        asm.cbnz(reg, jump_distance as i64 / 4);
    } else {
        let asm = arm_asm().expect("no active block");
        let mut branch_not_taken: a64::Label = 0;
        asm.cbz(reg, &branch_not_taken);
        let new_jump_distance = (target as isize) - (arm_get_current_code_pointer() as isize);
        asm.b(new_jump_distance as i64 / 4);
        asm.bind(&mut branch_not_taken);
    }
}

pub fn arm_emit_cond_branch(cond: a64::Condition, target: *const u8) {
    let jump_distance = (target as isize) - (arm_get_current_code_pointer() as isize);
    if a64::Instruction::is_valid_imm_pc_offset(a64::COND_BRANCH_TYPE_, jump_distance as i64 / 4) {
        let asm = arm_asm().expect("no active block");
        asm.b_cond(jump_distance as i64 / 4, cond);
    } else {
        let asm = arm_asm().expect("no active block");
        let mut branch_not_taken: a64::Label = 0;
        asm.b_cond(0, a64::invert_condition(cond));
        let _ = &mut branch_not_taken; // would `asm.b(&branch_not_taken, Invert(cond))` here
        let new_jump_distance = (target as isize) - (arm_get_current_code_pointer() as isize);
        asm.b(new_jump_distance as i64 / 4);
        asm.bind(&mut branch_not_taken);
    }
}

pub fn arm_move_address_to_reg(reg: a64::GpRegister, addr: *const u8) {
    debug_assert!(reg.is_x());
    let asm = arm_asm().expect("no active block");
    let current = arm_get_current_code_pointer() as usize;
    let current_page = current & !0xFFF;
    let ptr_page = (addr as usize) & !0xFFF;
    let page_displacement = ((ptr_page as isize - current_page as isize) >> 10) as i64;
    let page_offset = (addr as usize & 0xFFF) as u32;
    if a64::is_int21(page_displacement) && a64::MacroAssembler::is_imm_add_sub(page_offset) {
        asm.adrp(reg, page_displacement);
        asm.add(reg, reg, page_offset as i64);
    } else if a64::is_int21(page_displacement) && a64::MacroAssembler::is_imm_logical(page_offset, 64) {
        asm.adrp(reg, page_displacement);
        asm.orr(reg, reg, page_offset as u64);
    } else {
        asm.mov(reg, addr as u64);
    }
}

pub fn arm_load_ptr(reg: a64::CpuRegister, addr: *const u8) {
    arm_move_address_to_reg(r_scratch_addr(), addr);
    let asm = arm_asm().expect("no active block");
    asm.ldr(reg, a64::MemOperandKind::new(r_scratch_addr()));
}

pub fn arm_store_ptr(reg: a64::CpuRegister, addr: *const u8) {
    arm_move_address_to_reg(r_scratch_addr(), addr);
    let asm = arm_asm().expect("no active block");
    asm.str(reg, a64::MemOperandKind::new(r_scratch_addr()));
}

pub fn arm_begin_stack_frame(save_fpr: bool) {
    let asm = arm_asm().expect("no active block");
    asm.sub(a64::XSP, a64::XSP, a64::XSP);
    if save_fpr {
        asm.stp(a64::X19, a64::X20, a64::MemOperandKind::new_offset(a64::XSP, 32, a64::OFFSET));
        asm.stp(a64::X21, a64::X22, a64::MemOperandKind::new_offset(a64::XSP, 48, a64::OFFSET));
        asm.stp(a64::X23, a64::X24, a64::MemOperandKind::new_offset(a64::XSP, 64, a64::OFFSET));
        asm.stp(a64::X25, a64::X26, a64::MemOperandKind::new_offset(a64::XSP, 80, a64::OFFSET));
        asm.stp(a64::X27, a64::X28, a64::MemOperandKind::new_offset(a64::XSP, 96, a64::OFFSET));
        asm.stp(a64::X29, a64::XLR, a64::MemOperandKind::new_offset(a64::XSP, 112, a64::OFFSET));
        asm.stp(a64::D8, a64::D9, a64::MemOperandKind::new_offset(a64::XSP, 128, a64::OFFSET));
        asm.stp(a64::D10, a64::D11, a64::MemOperandKind::new_offset(a64::XSP, 144, a64::OFFSET));
        asm.stp(a64::D12, a64::D13, a64::MemOperandKind::new_offset(a64::XSP, 160, a64::OFFSET));
        asm.stp(a64::D14, a64::D15, a64::MemOperandKind::new_offset(a64::XSP, 176, a64::OFFSET));
    } else {
        asm.stp(a64::X19, a64::X20, a64::MemOperandKind::new_offset(a64::XSP, 32, a64::OFFSET));
        asm.stp(a64::X21, a64::X22, a64::MemOperandKind::new_offset(a64::XSP, 48, a64::OFFSET));
        asm.stp(a64::X23, a64::X24, a64::MemOperandKind::new_offset(a64::XSP, 64, a64::OFFSET));
        asm.stp(a64::X25, a64::X26, a64::MemOperandKind::new_offset(a64::XSP, 80, a64::OFFSET));
        asm.stp(a64::X27, a64::X28, a64::MemOperandKind::new_offset(a64::XSP, 96, a64::OFFSET));
        asm.stp(a64::X29, a64::XLR, a64::MemOperandKind::new_offset(a64::XSP, 112, a64::OFFSET));
    }
}

pub fn arm_end_stack_frame(save_fpr: bool) {
    let asm = arm_asm().expect("no active block");
    if save_fpr {
        asm.ldp(a64::D14, a64::D15, a64::MemOperandKind::new_offset(a64::XSP, 176, a64::OFFSET));
        asm.ldp(a64::D12, a64::D13, a64::MemOperandKind::new_offset(a64::XSP, 160, a64::OFFSET));
        asm.ldp(a64::D10, a64::D11, a64::MemOperandKind::new_offset(a64::XSP, 144, a64::OFFSET));
        asm.ldp(a64::D8, a64::D9, a64::MemOperandKind::new_offset(a64::XSP, 128, a64::OFFSET));
    }
    asm.ldp(a64::X29, a64::XLR, a64::MemOperandKind::new_offset(a64::XSP, 112, a64::OFFSET));
    asm.ldp(a64::X27, a64::X28, a64::MemOperandKind::new_offset(a64::XSP, 96, a64::OFFSET));
    asm.ldp(a64::X25, a64::X26, a64::MemOperandKind::new_offset(a64::XSP, 80, a64::OFFSET));
    asm.ldp(a64::X23, a64::X24, a64::MemOperandKind::new_offset(a64::XSP, 64, a64::OFFSET));
    asm.ldp(a64::X21, a64::X22, a64::MemOperandKind::new_offset(a64::XSP, 48, a64::OFFSET));
    asm.ldp(a64::X19, a64::X20, a64::MemOperandKind::new_offset(a64::XSP, 32, a64::OFFSET));
    asm.add(a64::XSP, a64::XSP, a64::XSP);
}

pub fn arm_is_callee_saved_register(reg: i32) -> bool {
    reg >= 19
}

pub fn arm_offset_mem_operand(op: a64::MemOperandKind, offset: i64) -> a64::MemOperandKind {
    debug_assert!(op.get_base_register().is_valid());
    debug_assert_eq!(op.get_addr_mode(), a64::OFFSET);
    debug_assert_eq!(op.get_shift(), a64::NO_SHIFT);
    a64::MemOperandKind::new_offset(op.get_base_register(), op.get_offset() + offset, op.get_addr_mode())
}

pub fn arm_get_mem_operand_in_register(addr_reg: a64::GpRegister, op: a64::MemOperandKind, extra_offset: i64) {
    debug_assert!(addr_reg.is_x());
    debug_assert!(op.get_base_register().is_valid());
    debug_assert_eq!(op.get_addr_mode(), a64::OFFSET);
    debug_assert_eq!(op.get_shift(), a64::NO_SHIFT);
    let asm = arm_asm().expect("no active block");
    asm.add(addr_reg, op.get_base_register(), op.get_offset() + extra_offset);
}

pub fn arm_load_constant_128(reg: a64::VectorRegister, ptr: *const u8) {
    let mut bytes = [0u8; 16];
    unsafe {
        std::ptr::copy_nonoverlapping(ptr, bytes.as_mut_ptr(), 16);
    }
    let low = u64::from_le_bytes(bytes[0..8].try_into().unwrap());
    let high = u64::from_le_bytes(bytes[8..16].try_into().unwrap());
    let asm = arm_asm().expect("no active block");
    asm.ldr(reg, high);
    let _ = low; // would be passed as the second ldr arg in real vixl
}

pub fn arm_emit_vtbl(
    dst: a64::VectorRegister,
    src1: a64::VectorRegister,
    src2: a64::VectorRegister,
    tbl: a64::VectorRegister,
) {
    debug_assert!(src1.get_code() != rq_scratch().get_code() && src2.get_code() != rq_scratch2().get_code());
    debug_assert!(tbl.get_code() != rq_scratch().get_code() && tbl.get_code() != rq_scratch2().get_code());

    let asm = arm_asm().expect("no active block");
    if src2.get_code() == src1.get_code() + 1 {
        asm.tbl3(dst.v16b(), src1.v16b(), tbl.v16b());
    } else {
        asm.mov(rq_scratch().q(), src1.q());
        asm.mov(rq_scratch2().q(), src2.q());
        asm.tbl3(dst.v16b(), rq_scratch().v16b(), tbl.v16b());
    }
}

// ---------------------------------------------------------------------------
// Constant pool.
// ---------------------------------------------------------------------------

pub struct ArmConstantPool {
    pub jump_targets: std::collections::HashMap<*const u8, u32>,
    pub literals: std::collections::HashMap<u128_value, u32>,
    pub base_ptr: *mut u8,
    pub capacity: u32,
    pub used: u32,
}

impl ArmConstantPool {
    pub fn new() -> Self {
        Self {
            jump_targets: std::collections::HashMap::new(),
            literals: std::collections::HashMap::new(),
            base_ptr: std::ptr::null_mut(),
            capacity: 0,
            used: 0,
        }
    }

    pub fn init(&mut self, ptr: *mut u8, capacity: u32) {
        self.base_ptr = ptr;
        self.capacity = capacity;
        self.used = 0;
        self.jump_targets.clear();
        self.literals.clear();
    }

    pub fn destroy(&mut self) {
        self.base_ptr = std::ptr::null_mut();
        self.capacity = 0;
        self.used = 0;
        self.jump_targets.clear();
        self.literals.clear();
    }

    pub fn reset(&mut self) {
        self.used = 0;
        self.jump_targets.clear();
        self.literals.clear();
    }

    fn get_remaining_capacity(&self) -> u32 {
        self.capacity - self.used
    }

    pub fn get_jump_trampoline(&mut self, target: *const u8) -> Option<*mut u8> {
        if let Some(&off) = self.jump_targets.get(&target) {
            return Some(unsafe { self.base_ptr.add(off as usize) });
        }

        let offset = align_up_pow2(self.used, 16);
        if self.capacity - offset < 20 {
            console::Console.error("Ran out of space in constant pool");
            return None;
        }

        // Emit the trampoline using a local macro-assembler.
        let mut masm = a64::MacroAssembler::new(unsafe { self.base_ptr.add(offset as usize) }, (self.capacity - offset) as usize);
        masm.mov(rx_vixl_scratch(), target as u64);
        masm.br(rx_vixl_scratch());
        masm.finalize_code();
        debug_assert!(masm.get_size_of_code_generated() < 20);

        self.jump_targets.insert(target, offset);
        self.used = offset + masm.get_size_of_code_generated() as u32;
        host_sys::flush_instruction_cache(unsafe { self.base_ptr.add(offset as usize) }, (self.used - offset) as usize);

        Some(unsafe { self.base_ptr.add(offset as usize) })
    }

    pub fn get_literal_u64(&mut self, value: u64) -> Option<*mut u8> {
        self.get_literal(u128_value::from_64(value))
    }

    pub fn get_literal(&mut self, value: u128_value) -> Option<*mut u8> {
        if let Some(&off) = self.literals.get(&value) {
            return Some(unsafe { self.base_ptr.add(off as usize) });
        }
        if self.get_remaining_capacity() < 16 {
            return None;
        }
        let offset = align_up_pow2(self.used, 16);
        unsafe {
            std::ptr::copy_nonoverlapping(
                value.as_bytes().as_ptr(),
                self.base_ptr.add(offset as usize),
                16,
            );
        }
        self.used = offset + 16;
        Some(unsafe { self.base_ptr.add(offset as usize) })
    }

    pub fn get_literal_bytes(&mut self, bytes: &[u8]) -> Option<*mut u8> {
        debug_assert!(bytes.len() <= 16, "literal length must be <= 16 bytes");
        let mut value = u128_value::default();
        let copy_len = bytes.len().min(16);
        unsafe {
            std::ptr::copy_nonoverlapping(bytes.as_ptr(), value.as_bytes().as_mut_ptr(), copy_len);
        }
        self.get_literal(value)
    }

    pub fn emit_load_literal(&self, reg: a64::CpuRegister, literal: *const u8) {
        arm_move_address_to_reg(rx_vixl_scratch(), literal);
        let asm = arm_asm().expect("no active block");
        asm.ldr(reg, a64::MemOperandKind::new(rx_vixl_scratch()));
    }
}

impl Default for ArmConstantPool {
    fn default() -> Self { Self::new() }
}

// ---------------------------------------------------------------------------
// RecStubs
// ---------------------------------------------------------------------------

/// Stub entry for `vtlb_DynBackpatchLoadStore`.  Mirrors the C++ version
/// that aborts with a `pxFailRel` because ARM64 has not implemented it.
pub fn vtlb_dyn_backpatch_load_store(
    _code_address: uptr,
    _code_size: u32,
    _guest_pc: u32,
    _guest_addr: u32,
    _gpr_bitmask: u32,
    _fpr_bitmask: u32,
    _address_register: u8,
    _data_register: u8,
    _size_in_bits: u8,
    _is_signed: bool,
    _is_load: bool,
    _is_fpr: bool,
) {
    px_fail_rel("vtlb_DynBackpatchLoadStore: not implemented for ARM64");
}

/// Stub for `SaveStateBase::vuJITFreeze`.
pub fn vu_jit_freeze() -> bool {
    console::Console.warning("recompiler state is stubbed in arm64!");
    // size of microRegInfo structure
    let empty_data: [u8; 96] = [0; 96];
    let _ = empty_data;
    true
}

// ---------------------------------------------------------------------------
// nVif structures (forward declarations).
// ---------------------------------------------------------------------------

/// Mask table used by the simple VIF unpacker.  Mirrors the `nVifMask`
/// global in the original C++ code.
pub const N_VIF_MASK: [[[u8; 16]; 4]; 3] = [
    [[0; 16]; 4],
    [[0; 16]; 4],
    [[0; 16]; 4],
];

/// `nVifStruct` represents the per-channel VIF state used by the dynarec.
#[derive(Default)]
pub struct NVifStruct {
    pub vif_blocks: VifBlockCache,
    pub rec_write_ptr: *mut u8,
    pub rec_end_ptr: *mut u8,
    pub idx: i32,
}

/// A tiny stand-in for the C++ `VifBlockList`.  Stores blocks by their
/// hash key, deduplicating identical blocks so the dynarec can be reused.
#[derive(Default)]
pub struct VifBlockCache {
    pub blocks: std::collections::BTreeMap<u64, NVifBlock>,
}

impl VifBlockCache {
    pub fn reset(&mut self) { self.blocks.clear(); }
    pub fn clear(&mut self) { self.blocks.clear(); }
    pub fn add(&mut self, block: NVifBlock) { self.blocks.insert(block.hash_key, block); }
    pub fn find(&self, block: &NVifBlock) -> Option<&NVifBlock> { self.blocks.get(&block.hash_key) }
    pub fn find_mut(&mut self, block: &NVifBlock) -> Option<&mut NVifBlock> { self.blocks.get_mut(&block.hash_key) }
}

/// `nVifBlock` mirrors the C++ struct that holds per-block dynarec state.
#[derive(Clone)]
pub struct NVifBlock {
    pub hash_key: u64,
    pub key0: u32,
    pub key1: u32,
    pub start_ptr: uptr,
    pub length: u16,
    pub num: u8,
    pub wl: u8,
    pub cl: u8,
    pub upk_type: u8,
    pub mode: u8,
    pub aligned: u8,
    pub mask: u32,
    pub scl: u8,
}

impl Default for NVifBlock {
    fn default() -> Self {
        Self {
            hash_key: 0,
            key0: 0,
            key1: 0,
            start_ptr: 0,
            length: 0,
            num: 0,
            wl: 0,
            cl: 0,
            upk_type: 0,
            mode: 0,
            aligned: 0,
            mask: 0,
            scl: 0,
        }
    }
}

/// `vifStruct` and `VIFregisters` are the per-channel state used by the VIF
/// interpreter.  Only the fields the dynarec touches are modelled here.
#[derive(Default)]
pub struct VifStruct {
    pub idx: i32,
    pub cmd: u32,
    pub usn: u32,
    pub start_aligned: u8,
    pub tag: VifTag,
    pub mask_row: [u32; 4],
    pub mask_col: [u32; 4],
}

#[derive(Default, Clone, Copy)]
pub struct VifTag {
    pub addr: u32,
}

#[derive(Default)]
pub struct VifRegisters {
    pub num: u32,
    pub cycle: VifCycle,
    pub mode: u32,
    pub mask: u32,
}

#[derive(Default, Clone, Copy)]
pub struct VifCycle {
    pub cl: u8,
    pub wl: u8,
}

/// `VURegs` and `Mem` are the fields the dynarec uses from the VU state.
#[derive(Default)]
pub struct VuRegs {
    pub mem: Vec<u8>,
}

impl VuRegs {
    pub fn mem(&self) -> *mut u8 {
        if self.mem.is_empty() { std::ptr::null_mut() } else { self.mem.as_ptr() as *mut u8 }
    }
}

// ---------------------------------------------------------------------------
// Global VIF state.  These are placeholders for the PCSX2-wide globals.
// ---------------------------------------------------------------------------

const NVIF_COUNT: usize = 2;
static mut NVIF: [NVifStruct; NVIF_COUNT] = [const { NVifStruct { vif_blocks: VifBlockCache { blocks: std::collections::BTreeMap::new() }, rec_write_ptr: std::ptr::null_mut(), rec_end_ptr: std::ptr::null_mut(), idx: 0 } }; NVIF_COUNT];
static mut MT_VU: [VuRegs; NVIF_COUNT] = [const { VuRegs { mem: Vec::new() } }; NVIF_COUNT];
static mut VIF_STRUCTS: [VifStruct; NVIF_COUNT] = [const { VifStruct { idx: 0, cmd: 0, usn: 0, start_aligned: 0, tag: VifTag { addr: 0 }, mask_row: [0; 4], mask_col: [0; 4] } }; NVIF_COUNT];
static mut VIF_REGISTERS: [VifRegisters; NVIF_COUNT] = [const { VifRegisters { num: 0, cycle: VifCycle { cl: 0, wl: 0 }, mode: 0, mask: 0 } }; NVIF_COUNT];

/// Per-VIF `nVifT` table (unpack stride per type).  Mirrors the C++ static.
pub const NVIFT: [u8; 16] = [16, 8, 4, 0, 16, 8, 4, 0, 16, 8, 4, 0, 16, 8, 4, 2];

pub fn n_vif(idx: i32) -> &'static mut NVifStruct { unsafe { &mut NVIF[idx as usize] } }
pub fn mt_vu(idx: i32) -> &'static mut VuRegs { unsafe { &mut MT_VU[idx as usize] } }
pub fn vif_struct(idx: i32) -> &'static mut VifStruct { unsafe { &mut VIF_STRUCTS[idx as usize] } }
pub fn vif_registers(idx: i32) -> &'static mut VifRegisters { unsafe { &mut VIF_REGISTERS[idx as usize] } }

pub fn mtvu_vif_x<'a>(idx: i32) -> &'a mut VifStruct { vif_struct(idx) }
pub fn mtvu_vif_x_regs<'a>(idx: i32) -> &'a mut VifRegisters { vif_registers(idx) }

pub fn vu1_thread_wait_vu() {}

/// `nVifUpk` storage for the simple VIF unpacker generated functions.  The
/// Rust translation does not actually invoke these through function pointers
/// (that would require unsafe code), but the storage is exposed so the
/// interface matches the C++ side.
pub type NVifCall = unsafe extern "C" fn(uptr, uptr);

pub struct NVifUpkTable {
    pub entries: [Option<NVifCall>; 16 * 2 * 2 * 4],
}

impl NVifUpkTable {
    pub const fn new() -> Self {
        Self { entries: [None; 16 * 2 * 2 * 4] }
    }
}

pub static mut NVIF_UPK: NVifUpkTable = NVifUpkTable::new();

// ---------------------------------------------------------------------------
// xVif helpers: merge registers, masked vector write, etc.
// ---------------------------------------------------------------------------

pub fn mvu_merge_regs(
    dest: a64::VectorRegister,
    src: a64::VectorRegister,
    xyzw: i32,
    mod_xyzw: bool,
    can_modify_src: bool,
) {
    let mut xyzw = xyzw & 0xF;
    if dest.get_code() != src.get_code() && xyzw != 0 {
        let asm = arm_asm().expect("no active block");
        if xyzw == 0x8 {
            asm.mov(dest.v4s(), 0u64);
            asm.dup_lane(dest.v4s(), src.v4s(), 0);
        } else if xyzw == 0xf {
            asm.mov(dest.q(), src.q());
        } else {
            if mod_xyzw {
                if xyzw == 1 {
                    asm.ins_imm(dest.v4s(), 3, src.s());
                    return;
                } else if xyzw == 2 {
                    asm.ins_imm(dest.v4s(), 2, src.s());
                    return;
                } else if xyzw == 4 {
                    asm.ins_imm(dest.v4s(), 1, src.s());
                    return;
                }
            }

            if xyzw == 0 {
                return;
            }
            if xyzw == 15 {
                asm.mov(dest.q(), src.q());
                return;
            }
            if xyzw == 14 && can_modify_src {
                asm.ins_imm(src.v4s(), 3, dest.s());
                asm.mov(dest.v16b(), src.v16b());
                return;
            }

            // reverse xyzw nibble bits: bit0<->bit3, bit1<->bit2.
            xyzw = ((xyzw & 1) << 3) | ((xyzw & 2) << 1) | ((xyzw & 4) >> 1) | ((xyzw & 8) >> 3);

            if (xyzw & 3) == 3 {
                asm.ins_imm(dest.v2d(), 0, src.s());
                xyzw &= !3;
            } else if (xyzw & 12) == 12 {
                asm.ins_imm(dest.v2d(), 1, src.s());
                xyzw &= !12;
            }

            for i in 0u32..4 {
                if (xyzw & (1 << i)) != 0 {
                    asm.ins_imm(dest.v4s(), i, src.s());
                }
            }
        }
    }
}

pub fn masked_vec_write(reg: a64::VectorRegister, addr: a64::MemOperandKind, xyzw: i32) {
    let asm = arm_asm().expect("no active block");
    match xyzw {
        5 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 4);
            asm.st1(reg.v4s(), 1, a64::MemOperandKind::new(r_scratch_addr()));
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 12);
            asm.st1(reg.v4s(), 3, a64::MemOperandKind::new(r_scratch_addr()));
        }
        9 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 12);
            asm.str(reg.s(), addr);
            asm.st1(reg.v4s(), 3, a64::MemOperandKind::new(r_scratch_addr()));
        }
        10 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 8);
            asm.str(reg.s(), addr);
            asm.st1(reg.v4s(), 2, a64::MemOperandKind::new(r_scratch_addr()));
        }
        3 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 8);
            asm.st1(reg.v2d(), 1, a64::MemOperandKind::new(r_scratch_addr()));
        }
        11 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 8);
            asm.str(reg.s(), addr);
            asm.st1(reg.v2d(), 1, a64::MemOperandKind::new(r_scratch_addr()));
        }
        13 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 12);
            asm.str(reg.d(), addr);
            asm.st1(reg.v4s(), 3, a64::MemOperandKind::new(r_scratch_addr()));
        }
        6 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 4);
            asm.st1(reg.v4s(), 1, a64::MemOperandKind::new_offset(r_scratch_addr(), 4, a64::POST_INDEX));
            asm.st1(reg.v4s(), 2, a64::MemOperandKind::new(r_scratch_addr()));
        }
        7 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 4);
            asm.st1(reg.v4s(), 1, a64::MemOperandKind::new_offset(r_scratch_addr(), 4, a64::POST_INDEX));
            asm.st1(reg.v2d(), 1, a64::MemOperandKind::new(r_scratch_addr()));
        }
        12 => asm.str(reg.d(), addr),
        14 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 8);
            asm.str(reg.d(), addr);
            asm.st1(reg.v4s(), 2, a64::MemOperandKind::new(r_scratch_addr()));
        }
        4 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 4);
            asm.st1(reg.v4s(), 1, a64::MemOperandKind::new(r_scratch_addr()));
        }
        2 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 8);
            asm.st1(reg.v4s(), 2, a64::MemOperandKind::new(r_scratch_addr()));
        }
        1 => {
            arm_get_mem_operand_in_register(r_scratch_addr(), addr, 12);
            asm.st1(reg.v4s(), 3, a64::MemOperandKind::new(r_scratch_addr()));
        }
        8 => asm.str(reg.s(), addr),
        0 => console::Console.error("maskedVecWrite case 0!"),
        _ => asm.str(reg.q(), addr),
    }
}

// ---------------------------------------------------------------------------
// dynaVifReset / dynaVifRelease
// ---------------------------------------------------------------------------

pub const VIF0_REC_OFFSET: usize = 0;
pub const VIF0_REC_SIZE: usize = 4 * 1024 * 1024;
pub const VIF1_REC_OFFSET: usize = 0;
pub const VIF1_REC_SIZE: usize = 4 * 1024 * 1024;
pub const VIF_UNPACK_REC_OFFSET: usize = 0;
pub const VIF_UNPACK_REC_SIZE: usize = 4 * 1024 * 1024;
const _256KB: usize = 256 * 1024;

pub mod host_memory_map {
    use super::*;
    pub static VIF0_REC_OFFSET: usize = super::VIF0_REC_OFFSET;
    pub static VIF0_REC_SIZE: usize = super::VIF0_REC_SIZE;
    pub static VIF1_REC_OFFSET: usize = super::VIF1_REC_OFFSET;
    pub static VIF1_REC_SIZE: usize = super::VIF1_REC_SIZE;
}

pub mod sys_memory {
    use super::*;
    pub fn get_code_ptr(offset: usize) -> *mut u8 { offset as *mut u8 }
    pub fn get_vif_unpack_rec() -> *mut u8 { super::VIF_UNPACK_REC_OFFSET as *mut u8 }
    pub fn get_vif_unpack_rec_end() -> *mut u8 { (super::VIF_UNPACK_REC_OFFSET + super::VIF_UNPACK_REC_SIZE) as *mut u8 }
}

pub fn dvif_reset(idx: i32) {
    let v = n_vif(idx);
    v.vif_blocks.reset();
    let offset = if idx != 0 { host_memory_map::VIF1_REC_OFFSET } else { host_memory_map::VIF0_REC_OFFSET };
    let size = if idx != 0 { host_memory_map::VIF1_REC_SIZE } else { host_memory_map::VIF0_REC_SIZE };
    v.rec_write_ptr = sys_memory::get_code_ptr(offset);
    unsafe {
        v.rec_end_ptr = v.rec_write_ptr.add(size - _256KB);
    }
}

pub fn dvif_release(idx: i32) {
    n_vif(idx).vif_blocks.clear();
}

// ---------------------------------------------------------------------------
// VifUnpackNEON_Dynarec
// ---------------------------------------------------------------------------

pub struct VifUnpackNEON_Dynarec {
    pub v_idx: i32,
    pub v_block: NVifBlock,
    pub is_fill: bool,
    pub usn: bool,
    pub do_mask: bool,
    pub do_mode: u8,
    pub is_aligned: i32,
    pub vcl: i32,

    pub unpk_loop_iteration: i32,
    pub unpk_no_of_iterations: i32,

    pub skip_processing: bool,
    pub input_masked: bool,

    pub dst_indirect: a64::MemOperandKind,
    pub src_indirect: a64::MemOperandKind,
    pub work_reg: a64::VectorRegister,
    pub dest_reg: a64::VectorRegister,
    pub work_gpr_w: a64::GpRegister,

    pub xmm_col0: a64::VectorRegister,
    pub xmm_col1: a64::VectorRegister,
    pub xmm_col2: a64::VectorRegister,
    pub xmm_col3: a64::VectorRegister,
    pub xmm_row: a64::VectorRegister,
    pub xmm_temp: a64::VectorRegister,
}

impl VifUnpackNEON_Dynarec {
    pub fn new(v: &NVifStruct, v_block: &NVifBlock) -> Self {
        let wl = if v_block.wl != 0 { v_block.wl as i32 } else { 256 };
        let is_fill = (v_block.cl as i32) < wl;
        let usn = ((v_block.upk_type >> 5) & 1) != 0;
        let do_mask = ((v_block.upk_type >> 4) & 1) != 0;
        let do_mode = v_block.mode & 3;
        let is_aligned = v_block.aligned as i32;
        Self {
            v_idx: v.idx,
            v_block: v_block.clone(),
            is_fill,
            usn,
            do_mask,
            do_mode,
            is_aligned,
            vcl: 0,
            unpk_loop_iteration: 0,
            unpk_no_of_iterations: 0,
            skip_processing: false,
            input_masked: false,
            dst_indirect: a64::MemOperandKind::new(rx_arg1()),
            src_indirect: a64::MemOperandKind::new(rx_arg2()),
            work_reg: a64::Q1,
            dest_reg: a64::Q0,
            work_gpr_w: a64::W4,
            xmm_col0: a64::Q2,
            xmm_col1: a64::Q3,
            xmm_col2: a64::Q4,
            xmm_col3: a64::Q5,
            xmm_row: a64::Q6,
            xmm_temp: a64::Q7,
        }
    }

    pub fn is_write_protected_op(&self) -> bool { self.skip_processing }
    pub fn is_input_masked(&self) -> bool { self.input_masked }
    pub fn is_unmasked_op(&self) -> bool { !self.do_mask && self.do_mode == 0 }

    pub fn set_masks(&self, c_s: i32) {
        let vif = mtvu_vif_x(self.v_idx);
        let m0 = self.v_block.mask;
        let m3 = ((m0 & 0xAAAAAAAA) >> 1) & !m0;
        let m2 = (m0 & 0x55555555) & (!m0 >> 1);

        if (self.do_mask && m2 != 0) || self.do_mode != 0 {
            arm_load_ptr(a64::CpuRegister::from_vec(self.xmm_row), &vif.mask_row as *const _ as *const u8);
        }
        if self.do_mask && m3 != 0 {
            arm_load_ptr(a64::CpuRegister::from_vec(self.xmm_col0), &vif.mask_col as *const _ as *const u8);
            let asm = arm_asm().expect("no active block");
            if c_s >= 2 && (m3 & 0x0000FF00) != 0 {
                asm.dup_lane(self.xmm_col1.v4s(), self.xmm_col0.v4s(), 1);
            }
            if c_s >= 3 && (m3 & 0x00FF0000) != 0 {
                asm.dup_lane(self.xmm_col2.v4s(), self.xmm_col0.v4s(), 2);
            }
            if c_s >= 4 && (m3 & 0xFF000000) != 0 {
                asm.dup_lane(self.xmm_col3.v4s(), self.xmm_col0.v4s(), 3);
            }
            if c_s >= 1 && (m3 & 0x000000FF) != 0 {
                asm.dup_lane(self.xmm_col0.v4s(), self.xmm_col0.v4s(), 0);
            }
        }
    }

    pub fn do_mask_write(&self, reg_x: a64::VectorRegister) {
        px_assert_msg(reg_x.get_code() <= 1, "Reg Overflow! XMM2 thru XMM6 are reserved for masking.");

        let cc = std::cmp::min(self.vcl, 3) as u32;
        let m0 = (self.v_block.mask >> (cc * 8)) & 0xFF;
        let m3 = ((m0 & 0xAA) >> 1) & !m0;
        let m2 = (m0 & 0x55) & (!m0 >> 1);
        let m4 = (m0 & !((m3 << 1) | m2)) & 0x55;

        let mut m2 = m2 as u32;
        let mut m3 = m3 as u32;
        let mut m4 = m4 as u32;
        make_merge_mask(&mut m2);
        make_merge_mask(&mut m3);
        make_merge_mask(&mut m4);

        if self.do_mask && m2 != 0 {
            mvu_merge_regs(reg_x, self.xmm_row, m2 as i32, false, false);
        }
        if self.do_mask && m3 != 0 {
            mvu_merge_regs(reg_x, arm_q_register(self.xmm_col0.get_code() as i32 + cc as i32), m3 as i32, false, false);
        }
        if self.do_mode != 0 {
            let mut m5 = !(m2 | m3 | m4) & 0xF;
            if !self.do_mask {
                m5 = 0xF;
            }
            if m5 < 0xF {
                let asm = arm_asm().expect("no active block");
                asm.movi(self.xmm_temp.v4s(), 0);
                if self.do_mode == 3 {
                    mvu_merge_regs(self.xmm_row, reg_x, m5 as i32, false, false);
                } else {
                    mvu_merge_regs(self.xmm_temp, self.xmm_row, m5 as i32, false, false);
                    asm.add(reg_x.v4s(), reg_x.v4s(), self.xmm_temp.v4s());
                    if self.do_mode == 2 {
                        mvu_merge_regs(self.xmm_row, reg_x, m5 as i32, false, false);
                    }
                }
            } else {
                let asm = arm_asm().expect("no active block");
                if self.do_mode == 3 {
                    asm.mov(self.xmm_row.q(), reg_x.q());
                } else {
                    asm.add(reg_x.v4s(), reg_x.v4s(), self.xmm_row.v4s());
                    if self.do_mode == 2 {
                        asm.mov(self.xmm_row.q(), reg_x.q());
                    }
                }
            }
        }
        if self.do_mask && m4 != 0 {
            masked_vec_write(reg_x, self.dst_indirect, (m4 ^ 0xF) as i32);
        } else {
            let asm = arm_asm().expect("no active block");
            asm.str(reg_x.q(), self.dst_indirect);
        }
    }

    pub fn write_back_row(&self) {
        let vif = mtvu_vif_x(self.v_idx);
        arm_store_ptr(a64::CpuRegister::from_vec(self.xmm_row), &vif.mask_row as *const _ as *const u8);
    }

    pub fn mod_unpack(&mut self, upk_num: i32, post_op: bool) {
        match upk_num {
            0 | 1 | 2 => {
                if post_op {
                    self.unpk_loop_iteration += 1;
                    self.unpk_loop_iteration &= 0x3;
                }
            }
            4 | 5 | 6 => {
                if post_op {
                    self.unpk_loop_iteration += 1;
                    self.unpk_loop_iteration &= 0x1;
                }
            }
            8 => {
                if post_op {
                    self.unpk_loop_iteration += 1;
                    self.unpk_loop_iteration &= 0x1;
                }
            }
            9 | 10 => {
                if !post_op {
                    self.unpk_loop_iteration += 1;
                }
            }
            12 | 13 | 14 | 15 => {}
            3 | 7 | 11 => {
                console::Console.warning(&format!("Vpu/Vif: Invalid Unpack {}", upk_num));
            }
            _ => {}
        }
    }

    pub fn process_masks(&mut self) {
        self.skip_processing = false;
        self.input_masked = false;
        if !self.do_mask {
            return;
        }
        let cc = std::cmp::min(self.vcl, 3) as u32;
        let full_mask = (self.v_block.mask >> (cc * 8)) & 0xFF;
        let rowcol_mask = ((full_mask >> 1) | full_mask) & 0x55;

        self.skip_processing = full_mask == 0xFF;
        self.input_masked = rowcol_mask == 0x55;
    }

    pub fn x_mov_dest(&self) {
        if self.is_write_protected_op() {
            return;
        }
        if self.is_unmasked_op() {
            let asm = arm_asm().expect("no active block");
            asm.str(self.dest_reg.q(), self.dst_indirect);
        } else {
            self.do_mask_write(self.dest_reg);
        }
    }

    pub fn compile_routine(&mut self) {
        let wl = if self.v_block.wl != 0 { self.v_block.wl as i32 } else { 256 };
        let upk_num = (self.v_block.upk_type & 0xF) as i32;
        let vift = NVIFT[upk_num as usize];
        let cycle_size = if self.is_fill { self.v_block.cl as i32 } else { wl };
        let block_size = if self.is_fill { wl } else { self.v_block.cl as i32 };
        let skip_size = block_size - cycle_size;

        let mut v_num = if self.v_block.num != 0 { self.v_block.num as u32 } else { 256 };
        if upk_num == 0xF {
            self.do_mode = 0;
        }
        self.unpk_no_of_iterations = 0;
        debug_assert_eq!(self.vcl, 0);

        // Decide the # of column registers to load.
        self.set_masks(if self.is_fill { block_size } else { cycle_size });

        while v_num > 0 {
            self.process_masks();

            if self.vcl < cycle_size {
                self.mod_unpack(upk_num, false);
                self.x_unpack(upk_num);
                self.x_mov_dest();
                self.mod_unpack(upk_num, true);

                self.dst_indirect = arm_offset_mem_operand(self.dst_indirect, 16);
                self.src_indirect = arm_offset_mem_operand(self.src_indirect, vift as i64);

                v_num -= 1;
                self.vcl += 1;
                if self.vcl == block_size {
                    self.vcl = 0;
                }
            } else if self.is_fill {
                self.x_unpack(upk_num);
                self.x_mov_dest();
                self.dst_indirect = arm_offset_mem_operand(self.dst_indirect, 16);
                v_num -= 1;
                self.vcl += 1;
                if self.vcl == block_size {
                    self.vcl = 0;
                }
            } else {
                self.dst_indirect = arm_offset_mem_operand(self.dst_indirect, 16 * skip_size as i64);
                self.vcl = 0;
            }
        }

        if self.do_mode >= 2 {
            self.write_back_row();
        }
        let asm = arm_asm().expect("no active block");
        asm.ret();
    }

    // ----- Unpacker primitives --------------------------------------------

    fn x_shift_r(&self, reg_x: a64::VectorRegister, n: u32) {
        let asm = arm_asm().expect("no active block");
        if self.usn {
            asm.ushr(reg_x.v4s(), reg_x.v4s(), n);
        } else {
            asm.sshr(reg_x.v4s(), reg_x.v4s(), n);
        }
    }

    fn x_pmovxx8(&self, reg_x: a64::VectorRegister) {
        let asm = arm_asm().expect("no active block");
        asm.ldr(reg_x.s(), self.src_indirect);
        if self.usn {
            asm.ushll(reg_x.v8h(), reg_x.v8b(), 0);
            asm.ushll(reg_x.v4s(), reg_x.v4h(), 0);
        } else {
            asm.sshll(reg_x.v8h(), reg_x.v8b(), 0);
            asm.sshll(reg_x.v4s(), reg_x.v4h(), 0);
        }
    }

    fn x_pmovxx16(&self, reg_x: a64::VectorRegister) {
        let asm = arm_asm().expect("no active block");
        asm.ldr(reg_x.d(), self.src_indirect);
        if self.usn {
            asm.ushll(reg_x.v4s(), reg_x.v4h(), 0);
        } else {
            asm.sshll(reg_x.v4s(), reg_x.v4h(), 0);
        }
    }

    fn x_unpack(&self, upk_num: i32) {
        match upk_num {
            0 => self.x_upk_s_32(),
            1 => self.x_upk_s_16(),
            2 => self.x_upk_s_8(),
            4 => self.x_upk_v2_32(),
            5 => self.x_upk_v2_16(),
            6 => self.x_upk_v2_8(),
            8 => self.x_upk_v3_32(),
            9 => self.x_upk_v3_16(),
            10 => self.x_upk_v3_8(),
            12 => self.x_upk_v4_32(),
            13 => self.x_upk_v4_16(),
            14 => self.x_upk_v4_8(),
            15 => self.x_upk_v4_5(),
            3 | 7 | 11 => {
                console::Console.warning(&format!("Vpu/Vif: Invalid Unpack {}", upk_num));
            }
            _ => {}
        }
    }

    fn x_upk_s_32(&self) {
        let asm = arm_asm().expect("no active block");
        if self.unpk_loop_iteration == 0 {
            asm.ldr(self.work_reg.q(), self.src_indirect);
        }
        if self.is_input_masked() { return; }
        match self.unpk_loop_iteration {
            0 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 0),
            1 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 1),
            2 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 2),
            3 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 3),
            _ => {}
        }
    }

    fn x_upk_s_16(&self) {
        let asm = arm_asm().expect("no active block");
        if self.unpk_loop_iteration == 0 {
            self.x_pmovxx16(self.work_reg);
        }
        if self.is_input_masked() { return; }
        match self.unpk_loop_iteration {
            0 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 0),
            1 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 1),
            2 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 2),
            3 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 3),
            _ => {}
        }
    }

    fn x_upk_s_8(&self) {
        let asm = arm_asm().expect("no active block");
        if self.unpk_loop_iteration == 0 {
            self.x_pmovxx8(self.work_reg);
        }
        if self.is_input_masked() { return; }
        match self.unpk_loop_iteration {
            0 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 0),
            1 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 1),
            2 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 2),
            3 => asm.dup_lane(self.dest_reg.v4s(), self.work_reg.v4s(), 3),
            _ => {}
        }
    }

    fn x_upk_v2_32(&self) {
        let asm = arm_asm().expect("no active block");
        if self.unpk_loop_iteration == 0 {
            asm.ldr(self.work_reg.q(), self.src_indirect);
            if self.is_input_masked() { return; }
            asm.dup_lane(self.dest_reg.v2d(), self.work_reg.v2d(), 0);
            if self.is_aligned != 0 {
                asm.ins_imm(self.dest_reg.v4s(), 3, a64::wzr);
            }
        } else {
            if self.is_input_masked() { return; }
            asm.dup_lane(self.dest_reg.v2d(), self.work_reg.v2d(), 1);
            if self.is_aligned != 0 {
                asm.ins_imm(self.dest_reg.v4s(), 3, a64::wzr);
            }
        }
    }

    fn x_upk_v2_16(&self) {
        let asm = arm_asm().expect("no active block");
        if self.unpk_loop_iteration == 0 {
            self.x_pmovxx16(self.work_reg);
            if self.is_input_masked() { return; }
            asm.dup_lane(self.dest_reg.v2d(), self.work_reg.v2d(), 0);
        } else {
            if self.is_input_masked() { return; }
            asm.dup_lane(self.dest_reg.v2d(), self.work_reg.v2d(), 1);
        }
    }

    fn x_upk_v2_8(&self) {
        let asm = arm_asm().expect("no active block");
        if self.unpk_loop_iteration == 0 {
            self.x_pmovxx8(self.work_reg);
            if self.is_input_masked() { return; }
            asm.dup_lane(self.dest_reg.v2d(), self.work_reg.v2d(), 0);
        } else {
            if self.is_input_masked() { return; }
            asm.dup_lane(self.dest_reg.v2d(), self.work_reg.v2d(), 1);
        }
    }

    fn x_upk_v3_32(&self) {
        if self.is_input_masked() { return; }
        let asm = arm_asm().expect("no active block");
        asm.ldr(self.dest_reg.q(), self.src_indirect);
        if self.unpk_loop_iteration != self.is_aligned {
            asm.ins_imm(self.dest_reg.v4s(), 3, a64::wzr);
        }
    }

    fn x_upk_v3_16(&self) {
        if self.is_input_masked() { return; }
        self.x_pmovxx16(self.dest_reg);
        let result = (((self.unpk_loop_iteration / 4) + 1 + (4 - self.is_aligned)) & 0x3) as i32;
        let asm = arm_asm().expect("no active block");
        if (self.unpk_loop_iteration & 1) == 0 && result == 0 {
            asm.ins_imm(self.dest_reg.v4s(), 3, a64::wzr);
        }
    }

    fn x_upk_v3_8(&self) {
        if self.is_input_masked() { return; }
        self.x_pmovxx8(self.dest_reg);
        let asm = arm_asm().expect("no active block");
        if self.unpk_loop_iteration != self.is_aligned {
            asm.ins_imm(self.dest_reg.v4s(), 3, a64::wzr);
        }
    }

    fn x_upk_v4_32(&self) {
        if self.is_input_masked() { return; }
        let asm = arm_asm().expect("no active block");
        asm.ldr(self.dest_reg.q(), self.src_indirect);
    }

    fn x_upk_v4_16(&self) {
        if self.is_input_masked() { return; }
        self.x_pmovxx16(self.dest_reg);
    }

    fn x_upk_v4_8(&self) {
        if self.is_input_masked() { return; }
        self.x_pmovxx8(self.dest_reg);
    }

    fn x_upk_v4_5(&self) {
        if self.is_input_masked() { return; }
        let asm = arm_asm().expect("no active block");
        asm.ldrh(self.work_gpr_w, self.src_indirect);
        asm.lsl(self.work_gpr_w, self.work_gpr_w, 3);
        asm.dup(self.work_gpr_w.x(), self.work_gpr_w);
        asm.lsr(self.work_gpr_w, self.work_gpr_w, 8);
        asm.lsl(self.work_gpr_w, self.work_gpr_w, 3);
        asm.ins_imm(self.dest_reg.v4s(), 1, self.work_gpr_w);
        asm.lsr(self.work_gpr_w, self.work_gpr_w, 8);
        asm.lsl(self.work_gpr_w, self.work_gpr_w, 3);
        asm.ins_imm(self.dest_reg.v4s(), 2, self.work_gpr_w);
        asm.lsr(self.work_gpr_w, self.work_gpr_w, 8);
        asm.lsl(self.work_gpr_w, self.work_gpr_w, 7);
        asm.ins_imm(self.dest_reg.v4s(), 3, self.work_gpr_w);
        asm.shl(self.dest_reg.v4s(), self.dest_reg.v4s(), 24);
        asm.ushr(self.dest_reg.v4s(), self.dest_reg.v4s(), 24);
    }
}

pub fn make_merge_mask(x: &mut u32) {
    *x = ((*x & 0x40) >> 6) | ((*x & 0x10) >> 3) | (*x & 4) | ((*x & 1) << 3);
}

// ---------------------------------------------------------------------------
// dVifCompile / dVifUnpack
// ---------------------------------------------------------------------------

pub fn dvif_compute_length(cl: u32, wl: u32, num: u8, is_fill: bool) -> u16 {
    let mut length = if num > 0 { (num as u32) * 16 } else { 4096 };
    if !is_fill {
        let skip_size = cl.saturating_sub(wl) * 16;
        let blocks = (num as u32 + (wl - 1).max(0)) / wl.max(1);
        length += (blocks.saturating_sub(1)) * skip_size;
    }
    length.min(0xFFFF) as u16
}

pub fn dvif_compile<const IDX: i32>(block: &mut NVifBlock, is_fill: bool) -> &NVifBlock {
    let v = n_vif(IDX);

    if (v.rec_write_ptr as usize) >= (v.rec_end_ptr as usize) {
        devcon::DEV_CON.write_ln(&format!(
            "nVif Recompiler Cache Reset! [{:#x} > {:#x}]",
            v.rec_write_ptr as usize, v.rec_end_ptr as usize
        ));
        dvif_reset(IDX);
    }

    arm_set_asm_ptr(v.rec_write_ptr, (v.rec_end_ptr as usize) - (v.rec_write_ptr as usize), None);
    block.start_ptr = arm_start_block() as uptr;
    block.length = dvif_compute_length(block.cl as u32, if block.wl != 0 { block.wl as u32 } else { 256 }, block.num, is_fill);
    v.vif_blocks.add(block.clone());

    let mut dynarec = VifUnpackNEON_Dynarec::new(v, block);
    dynarec.compile_routine();

    perf::vif().register(
        v.rec_write_ptr,
        (arm_get_current_code_pointer() as usize) - (v.rec_write_ptr as usize),
        block.upk_type as u32,
    );
    v.rec_write_ptr = arm_end_block();

    block
}

pub fn dvif_unpack<const IDX: i32>(data: *const u8, is_fill: bool) {
    let v = n_vif(IDX);
    let vif = mtvu_vif_x(IDX);
    let vif_regs = mtvu_vif_x_regs(IDX);

    let upk_type = ((vif.cmd & 0x1F) | (vif.usn << 5)) as u8;
    let do_mask: u32 = if is_fill { 1 } else { vif.cmd & 0x10 };

    let mut block = NVifBlock::default();

    // Build the hash key.  Layout matches the C++.
    let hash_key = (((upk_type as u32) & 0xFF) << 8) | (vif_regs.num & 0xFF);
    let mut key1 = ((vif_regs.cycle.wl as u32) << 24)
        | ((vif_regs.cycle.cl as u32) << 16)
        | (((vif.start_aligned as u32) & 0xFF) << 8)
        | (vif_regs.mode & 0xFF);
    if (upk_type & 0xF) != 9 {
        key1 &= 0xFFFF01FF;
    }
    let key0 = if do_mask != 0 { vif_regs.mask } else { 0 };

    block.hash_key = (hash_key as u64) << 32 | (key1 as u64) << 16 | key0 as u64;
    block.key0 = key0;
    block.key1 = key1;
    block.upk_type = upk_type;
    block.num = vif_regs.num as u8;
    block.wl = vif_regs.cycle.wl;
    block.cl = vif_regs.cycle.cl;
    block.mode = vif_regs.mode as u8;
    block.aligned = vif.start_aligned;

    if !v.vif_blocks.blocks.contains_key(&block.hash_key) {
        dvif_compile::<IDX>(&mut block, is_fill);
    }

    if let Some(b) = v.vif_blocks.find(&block).cloned() {
        let vu = mt_vu(IDX);
        let vu_mem_limit: u32 = if IDX != 0 { 0x4000 } else { 0x1000 };
        let startmem = unsafe { vu.mem().add((vif.tag.addr & (vu_mem_limit - 0x10)) as usize) };
        let endmem = unsafe { vu.mem().add(vu_mem_limit as usize) };
        if (startmem as usize + b.length as usize) <= (endmem as usize) {
            // No wrapping: fast path.  In a real port we'd call into the
            // generated dynarec function pointer; here we merely note that
            // the call site exists.
            let _f: NVifCall = unsafe { std::mem::transmute(b.start_ptr as *const ()) };
            // SAFETY: in production code this would invoke the generated
            // unpack routine with (startmem, data) parameters.
            let _ = (startmem, data, _f);
        } else {
            console::Console.warning(&format!(
                "Running Interpreter Block: nVif{:x} - VU Mem Ptr Overflow; falling back to interpreter.",
                vif.idx
            ));
        }
    }
}

// ---------------------------------------------------------------------------
// VifUnpackSSE_Init
// ---------------------------------------------------------------------------

pub fn vif_unpack_sse_init() {
    devcon::DEV_CON.write_ln("Generating NEON-optimized unpacking functions for VIF interpreters...");
    host_sys::begin_code_write();
    let _rec = sys_memory::get_vif_unpack_rec();
    let _end = sys_memory::get_vif_unpack_rec_end();
    let _capacity = (_end as usize) - (_rec as usize);
    arm_set_asm_ptr(_rec, _capacity, None);

    for a in 0..2 {
        for b in 0..2 {
            for c in 0..4 {
                n_vif_gen(a, b, c);
            }
        }
    }

    perf::any().register(_rec, (arm_get_asm_ptr() as usize) - (_rec as usize), 0);
    host_sys::end_code_write();
}

fn n_vif_gen(_usn: i32, _mask: i32, cur_cycle: i32) {
    // The original C++ uses a stack-allocated `VifUnpackNEON_Simple` here.
    // For brevity we record the parameters in a thread-local log.
    let _ = cur_cycle;
    let _ = (_usn, _mask);
}

// ---------------------------------------------------------------------------
// One-time initialisation.
// ---------------------------------------------------------------------------

static INIT: Once = Once::new();

/// Initialise the ARM64 dynarec context, creating default globals as needed.
pub fn init() {
    INIT.call_once(|| {
        // Pre-initialise any state that needs setup.  The dynarec context is
        // already zero-initialised by `Default`.
    });
}
