// Debug Controller - Wires PCSX2 DebugInterface to Slint UI

use crate::debug_backend::DebugApi;
use std::sync::{Arc, Mutex};

// Slint-generated types (from .slint files)
// These are generated by slint::include_modules!()
use crate::{RegisterEntry, Register128, Register64, MemoryLine, DisassemblyLine, StackEntry, ThreadEntry, ModuleEntry, BreakpointEntry, SymbolEntry};

pub struct DebugState {
    pub cpu: i32,
    pub is_running: bool,
    pub current_pc: u32,
    pub selected_category: i32,
    pub show_float: bool,
}

pub struct DebugController {
    state: Arc<Mutex<DebugState>>,
}

impl DebugController {
    pub fn new() -> Self {
        Self {
            state: Arc::new(Mutex::new(DebugState {
                cpu: 0,
                is_running: false,
                current_pc: 0,
                selected_category: 0,
                show_float: false,
            })),
        }
    }

    pub fn set_cpu(&self, cpu: i32) {
        self.state.lock().unwrap().cpu = cpu;
    }

    pub fn set_category(&self, cat: i32) {
        self.state.lock().unwrap().selected_category = cat;
    }

    pub fn get_pc(&self) -> u32 {
        let s = self.state.lock().unwrap();
        DebugApi::get_pc(s.cpu)
    }

    // Update register data from PCSX2
    pub fn fetch_registers(&self, cpu: i32, category: i32) -> Vec<RegisterEntry> {
        if !DebugApi::is_alive(cpu) {
            return Vec::new();
        }
        let count = DebugApi::get_register_count(cpu, category);
        let mut regs = Vec::new();
        for i in 0..count {
            let name = DebugApi::get_register_name(cpu, category, i);
            let val = DebugApi::get_register(cpu, category, i);
            regs.push(RegisterEntry {
                name: name.into(),
                value_hex: DebugApi::format_hex32(val).into(),
                value_float: DebugApi::format_float(val).into(),
                value_int: format!("{}", val).into(),
                is_modified: false,
                is_selected: false,
            });
        }
        regs
    }

    // Update 128-bit register data
    pub fn fetch_registers128(&self, cpu: i32, category: i32) -> Vec<Register128> {
        if !DebugApi::is_alive(cpu) {
            return Vec::new();
        }
        let count = DebugApi::get_register_count(cpu, category);
        let mut regs = Vec::new();
        for i in 0..count {
            let name = DebugApi::get_register_name(cpu, category, i);
            let data = DebugApi::get_register128(cpu, category, i);
            let w = u32::from_le_bytes([data[0], data[1], data[2], data[3]]);
            let z = u32::from_le_bytes([data[4], data[5], data[6], data[7]]);
            let y = u32::from_le_bytes([data[8], data[9], data[10], data[11]]);
            let x = u32::from_le_bytes([data[12], data[13], data[14], data[15]]);
            regs.push(Register128 {
                name: name.into(),
                seg0_hex: DebugApi::format_hex32(w).into(),
                seg1_hex: DebugApi::format_hex32(z).into(),
                seg2_hex: DebugApi::format_hex32(y).into(),
                seg3_hex: DebugApi::format_hex32(x).into(),
                seg0_float: DebugApi::format_float(w).into(),
                seg1_float: DebugApi::format_float(z).into(),
                seg2_float: DebugApi::format_float(y).into(),
                seg3_float: DebugApi::format_float(x).into(),
                is_modified: false,
                selected_segment: -1,
            });
        }
        regs
    }

    // Update memory data
    pub fn fetch_memory(&self, cpu: i32, start_addr: u32, rows: u32) -> Vec<MemoryLine> {
        if !DebugApi::is_alive(cpu) {
            return Vec::new();
        }
        let mut lines = Vec::new();
        for row in 0..rows {
            let addr = start_addr.wrapping_add(row * 16);
            let mut b = [0u8; 16];
            for i in 0..16 {
                b[i] = DebugApi::read8(cpu, addr.wrapping_add(i as u32));
            }
            lines.push(MemoryLine {
                address: format!("0x{:08X}", addr).into(),
                b00: format!("{:02X}", b[0]).into(),
                b01: format!("{:02X}", b[1]).into(),
                b02: format!("{:02X}", b[2]).into(),
                b03: format!("{:02X}", b[3]).into(),
                b04: format!("{:02X}", b[4]).into(),
                b05: format!("{:02X}", b[5]).into(),
                b06: format!("{:02X}", b[6]).into(),
                b07: format!("{:02X}", b[7]).into(),
                b08: format!("{:02X}", b[8]).into(),
                b09: format!("{:02X}", b[9]).into(),
                b10: format!("{:02X}", b[10]).into(),
                b11: format!("{:02X}", b[11]).into(),
                b12: format!("{:02X}", b[12]).into(),
                b13: format!("{:02X}", b[13]).into(),
                b14: format!("{:02X}", b[14]).into(),
                b15: format!("{:02X}", b[15]).into(),
                ascii: DebugApi::format_ascii(&b).into(),
                selected_byte: -1,
                is_selected: false,
            });
        }
        lines
    }

    // Execution control
    pub fn run_pause(&self) {
        let s = self.state.lock().unwrap();
        if s.is_running {
            DebugApi::pause(s.cpu);
        } else {
            DebugApi::resume(s.cpu);
        }
    }

    pub fn step_into(&self) { DebugApi::step_into(self.state.lock().unwrap().cpu); }
    pub fn step_over(&self) { DebugApi::step_over(self.state.lock().unwrap().cpu); }
    pub fn step_out(&self) { DebugApi::step_out(self.state.lock().unwrap().cpu); }

    // Breakpoints
    pub fn toggle_breakpoint(&self, addr: u32) {
        DebugApi::toggle_breakpoint(self.state.lock().unwrap().cpu, addr);
    }

    pub fn is_breakpoint(&self, addr: u32) -> bool {
        DebugApi::is_breakpoint(self.state.lock().unwrap().cpu, addr)
    }
}
