// SPDX-FileCopyrightText: 2002-2026 PCSX2 Dev Team
// SPDX-License-Identifier: GPL-3.0+

//! Idiomatic Rust translation of the PCSX2 IOP module catalogue and the
//! `SaveState` / `StateWrapper` save-state subsystem.
//!
//! This module contains:
//!
//! * [`IOP_MODULES`] - the catalogue of all IOP module function exports
//!   generated by `IopModuleNames.cpp`.
//! * [`SaveState`] - the top-level file-oriented state container that owns
//!   the underlying byte buffer, the read/write cursor, and the section
//!   stack. It supports `open` / `save` / `load` plus typed
//!   `read_*` / `write_*` primitives.
//! * [`StateWrapper`] - a RAII section guard returned by
//!   [`SaveState::begin_section`]. It exposes the same typed read/write
//!   primitives, marks the section, and automatically calls
//!   [`SaveState::end_section`] when dropped.
//!
//! Only the `std` crate is used.

use std::fs::File;
use std::io::{self, Read, Write};
use std::marker::PhantomData;
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
//  Versioning
// ---------------------------------------------------------------------------

/// The full PCSX2 save-state version constant.
///
/// Mirrors `g_SaveVersion` from `SaveState.h`. The high 16 bits classify the
/// PCSX2 build type, the low 16 bits are the rolling savestate version.
pub const SAVE_VERSION: u32 = (0x9A59u32 << 16) | 0x0000;

/// `STATE_PCSX2_VERSION_SIZE` from `SaveState.cpp`.
pub const STATE_PCSX2_VERSION_SIZE: usize = 32;

/// `EntryFilename_StateVersion` from `SaveState.cpp`.
pub const ENTRY_FILENAME_STATE_VERSION: &str = "PCSX2 Savestate Version.id";

/// `EntryFilename_Screenshot` from `SaveState.cpp`.
pub const ENTRY_FILENAME_SCREENSHOT: &str = "Screenshot.png";

/// `EntryFilename_InternalStructures` from `SaveState.cpp`.
pub const ENTRY_FILENAME_INTERNAL_STRUCTURES: &str = "PCSX2 Internal Structures.dat";

// ---------------------------------------------------------------------------
//  IOP Modules
// ---------------------------------------------------------------------------

/// All IOP module function exports recognised by PCSX2.
///
/// The slice is built from the active (`#if 0`-stripped) section of
/// `IopModuleNames.cpp`. The original C++ file uses an X-macro that maps
/// `(module, index, function_name)` triples to dispatch cases. In Rust we
/// keep the flat list of function names; the module name can be recovered
/// by prefix-stripping against the [`IOP_MODULE_NAMES`] list.
pub const IOP_MODULES: &[&str] = &[
    // ---- cdvdman ----
    "sceCdInit",
    "sceCdStandby",
    "sceCdRead",
    "sceCdSeek",
    "sceCdGetError",
    "sceCdGetToc",
    "sceCdSearchFile",
    "sceCdSync",
    "sceCdGetDiskType",
    "sceCdDiskReady",
    "sceCdTrayReq",
    "sceCdStop",
    "sceCdPosToInt",
    "sceCdIntToPos",
    "sceCdCheckCmd",
    "_sceCdRI",
    "sceCdReadClock",
    "sceCdStatus",
    "sceCdApplySCmd",
    "sceCdCallback",
    "sceCdPause",
    "sceCdBreak",
    "sceCdReadCDDA",
    "sceCdGetReadPos",
    "sceCdCtrlADout",
    "sceCdNop",
    "_sceGetFsvRbuf",
    "_sceCdstm0Cb",
    "_sceCdstm1Cb",
    "_sceCdSC",
    "_sceCdRC",
    "sceCdApplyNCmd",
    "sceCdStInit",
    "sceCdStRead",
    "sceCdStSeek",
    "sceCdStStart",
    "sceCdStStat",
    "sceCdStStop",
    "sceCdRead0",
    "_sceCdRV",
    "_sceCdRM",
    "sceCdReadChain",
    "sceCdStPause",
    "sceCdStResume",
    "sceCdPowerOff",
    "sceCdMmode",
    "sceCdStSeekF",
    "sceCdPOffCallback",
    "_sceCdSetTimeout",
    "sceCdReadDvdDualInfo",
    "sceCdLayerSearchFile",
    "sceCdApplySCmd2",
    "_sceCdRE",
    // ---- deci2api ----
    "sceDeci2Open",
    "sceDeci2Close",
    "sceDeci2ExRecv",
    "sceDeci2ExSend",
    "sceDeci2ReqSend",
    "sceDeci2ExReqSend",
    "sceDeci2ExLock",
    "sceDeci2ExUnLock",
    "sceDeci2ExPanic",
    "sceDeci2Poll",
    "sceDeci2ExPoll",
    "sceDeci2ExRecvSuspend",
    "sceDeci2ExRecvUnSuspend",
    "sceDeci2ExWakeupThread",
    "sceDeci2ExSignalSema",
    "sceDeci2ExSetEventFlag",
    // ---- eenetctl ----
    "sceEENetCtlSetConfiguration",
    "sceEENetCtlRegisterDialCnf",
    "sceEENetCtlUnRegisterDialCnf",
    "sceEENetCtlSetDialingData",
    "sceEENetCtlClearDialingData",
    // ---- ent_devm ----
    "sceEENetDevAttach",
    "sceEENetDevReady",
    "sceEENetDevDetach",
    "sceEENetSifAddCmdHandler",
    "sceEENetSifRemoveCmdHandler",
    "sceEENetSifSendCmd",
    "sceEENetSifBindRpc",
    "sceEENetSifCallRpc",
    "sceEENetCheckWaitingDriverList",
    "sceEENetCheckTerminatedDriverList",
    // ---- excepman ----
    "RegisterExceptionHandler",
    "RegisterPriorityExceptionHandler",
    "RegisterDefaultExceptionHandler",
    "ReleaseExceptionHandler",
    "ReleaseDefaultExceptionHandler",
    // ---- heaplib ----
    "CreateHeap",
    "DeleteHeap",
    "AllocHeapMemory",
    "FreeHeapMemory",
    "HeapTotalFreeSize",
    // ---- ilink ----
    "sce1394SetupModule",
    "sce1394ReleaseModule",
    "sce1394Initialize",
    "sce1394Destroy",
    "sce1394Debug",
    "sce1394ConfGet",
    "sce1394ConfSet",
    "sce1394ChangeThreadPriority",
    "sce1394UnitAdd",
    "sce1394UnitDelete",
    "sce1394GenerateCrc32",
    "sce1394GenerateCrc16",
    "sce1394ValidateCrc16",
    "sce1394SbControl",
    "sce1394SbEnable",
    "sce1394SbDisable",
    "sce1394SbReset",
    "sce1394SbEui64",
    "sce1394SbNodeId",
    "sce1394SbNodeCount",
    "sce1394SbSelfId",
    "sce1394SbGenNumber",
    "sce1394SbPhyPacket",
    "sce1394SbCycleTime",
    "sce1394EvAlloc",
    "sce1394EvFree",
    "sce1394EvWait",
    "sce1394EvPoll",
    "sce1394PbAlloc",
    "sce1394PbFree",
    "sce1394PbGet",
    "sce1394PbSet",
    "sce1394TrDataInd",
    "sce1394TrDataUnInd",
    "sce1394TrAlloc",
    "sce1394TrFree",
    "sce1394TrGet",
    "sce1394TrSet",
    "sce1394TrWrite",
    "sce1394TrWriteV",
    "sce1394TrRead",
    "sce1394TrReadV",
    "sce1394TrLock",
    "sce1394CrEui64",
    "sce1394CrGenNumber",
    "sce1394CrMaxRec",
    "sce1394CrMaxSpeed",
    "sce1394CrRead",
    "sce1394CrCapability",
    "sce1394CrFindNode",
    "sce1394CrFindUnit",
    "sce1394CrInvalidate",
    // ---- ilsocket ----
    "sceILsockModuleInit",
    "sceILsockModuleReset",
    "sceILsockInit",
    "sceILsockReset",
    "sceILsockOpen",
    "sceILsockClose",
    "sceILsockBind",
    "sceILsockConnect",
    "sceILsockSend",
    "sceILsockSendTo",
    "sceILsockRecv",
    "sceILsockRecvFrom",
    "sceILsockHtoNl",
    "sceILsockHtoNs",
    "sceILsockNtoHl",
    "sceILsockNtoHs",
    "sce1394GetCycleTimeV",
    // ---- inet ----
    "sceInetName2Address",
    "sceInetAddress2String",
    "sceInetCreate",
    "sceInetOpen",
    "sceInetClose",
    "sceInetRecv",
    "sceInetSend",
    "sceInetAbort",
    "sceInetRecvFrom",
    "sceInetSendTo",
    "sceInetAddress2Name",
    "sceInetControl",
    "sceInetPoll",
    "sceInetNtohs",
    "sceInetHtons",
    "sceInetNtohl",
    "sceInetHtonl",
    "sceInetGet4u",
    "sceInetPut4u",
    "sceInetGetInterfaceList",
    "sceInetInterfaceControl",
    "sceInetGetRoutingTable",
    "sceInetAddRouting",
    "sceInetDelRouting",
    "sceInetGetNameServers",
    "sceInetAddNameServer",
    "sceInetDelNameServer",
    "sceInetChangeThreadPriority",
    "sceInetGetLog",
    "sceInetWaitInterfaceEvent",
    "sceInetSignalInterfaceEvent",
    "sceInetAbortLog",
    // ---- inetctl ----
    "sceInetCtlSetConfiguration",
    "sceInetCtlUpInterface",
    "sceInetCtlDownInterface",
    "sceInetCtlSetAutoMode",
    "sceInetCtlRegisterEventHandler",
    "sceInetCtlUnregisterEventHandler",
    "sceInetCtlGetState",
    "sceInetCtlGetConfiguration",
    "sceInetCtlSetDialingData",
    "sceInetCtlClearDialingData",
    // ---- intrman ----
    "RegisterIntrHandler",
    "ReleaseIntrHandler",
    "EnableIntr",
    "DisableIntr",
    "CpuDisableIntr",
    "CpuEnableIntr",
    "CpuSuspendIntr",
    "CpuResumeIntr",
    "QueryIntrContext",
    "QueryIntrStack",
    "iCatchMultiIntr",
    // ---- ioman ----
    "open",
    "close",
    "read",
    "write",
    "lseek",
    "ioctl",
    "remove",
    "mkdir",
    "rmdir",
    "dopen",
    "dclose",
    "dread",
    "getstat",
    "chstat",
    "format",
    "AddDrv",
    "DelDrv",
    "StdioInit",
    "rename",
    "chdir",
    "sync",
    "mount",
    "umount",
    "lseek64",
    "devctl",
    "symlink",
    "readlink",
    "ioctl2",
    // ---- libsd ----
    "sceSdQuit",
    "sceSdInit",
    "sceSdSetParam",
    "sceSdGetParam",
    "sceSdSetSwitch",
    "sceSdGetSwitch",
    "sceSdSetAddr",
    "sceSdGetAddr",
    "sceSdSetCoreAttr",
    "sceSdGetCoreAttr",
    "sceSdNote2Pitch",
    "sceSdPitch2Note",
    "sceSdProcBatch",
    "sceSdProcBatchEx",
    "sceSdVoiceTrans",
    "sceSdBlockTrans",
    "sceSdVoiceTransStatus",
    "sceSdBlockTransStatus",
    "sceSdSetTransCallback",
    "sceSdSetIRQCallback",
    "sceSdSetEffectAttr",
    "sceSdGetEffectAttr",
    "sceSdClearEffectWorkArea",
    "sceSdSetTransIntrHandler",
    "sceSdSetSpu2IntrHandler",
    "sceSdGetTransIntrHandlerArgument",
    "sceSdGetSpu2IntrHandlerArgument",
    "sceSdStopTrans",
    "sceSdCleanEffectWorkArea",
    "sceSdSetEffectMode",
    "sceSdSetEffectModeParams",
    // ---- loadcore ----
    "FlushIcache",
    "FlushDcache",
    "RegisterLibraryEntries",
    "ReleaseLibraryEntries",
    "RegisterNonAutoLinkEntries",
    "QueryLibraryEntryTable",
    "QueryBootMode",
    "RegisterBootMode",
    "SetRebootTimeLibraryHandlingMode",
    // ---- moddelay ----
    "sceMidiDelay_Init",
    "sceMidiDelay_ATick",
    "sceMidiDelay_Flush",
    // ---- modem ----
    "sceModemRegisterDevice",
    "sceModemUnregisterDevice",
    // ---- modhsyn ----
    "sceHSyn_Init",
    "sceHSyn_ATick",
    "sceHSyn_Load",
    "sceHSyn_VoiceTrans",
    "sceHSyn_SetReservVoice",
    "sceHSyn_SetEffectAttr",
    "sceHSyn_SetVolume",
    "sceHSyn_GetVolume",
    "sceHSyn_AllNoteOff",
    "sceHSyn_AllSoundOff",
    "sceHSyn_ResetAllControler",
    "sceHSyn_SetVoiceStatBuffer",
    "sceHSyn_SetDebugInfoBuffer",
    "sceHSyn_GetChStat",
    "sceHSyn_SetOutputMode",
    "sceHSyn_SESetMaxVoices",
    "sceHSyn_SEAllNoteOff",
    "sceHSyn_SEAllSoundOff",
    "sceHSyn_SERetrieveVoiceNumberByID",
    "sceHSyn_MSGetVoiceStateByID",
    "sceHSyn_MSGetVoiceEnvelopeByID",
    "sceHSyn_SERetrieveAllSEMsgIDs",
    "sceHSyn_GetReservVoice",
    "sceHSyn_GetOutputMode",
    "sceHSyn_Unload",
    // ---- modload ----
    "ReBootStart",
    "LoadModuleAddress",
    "LoadModule",
    "LoadStartModule",
    "StartModule",
    "LoadModuleBufferAddress",
    "LoadModuleBuffer",
    "GetModuleIdList",
    "ReferModuleStatus",
    "GetModuleIdListByName",
    "LoadModuleWithOption",
    "StopModule",
    "UnloadModule",
    "SearchModuleByName",
    "SearchModuleByAddress",
    "SelfStopModule",
    "SelfUnloadModule",
    "AllocLoadMemory",
    "FreeLoadMemory",
    "SetModuleFlags",
    // ---- modmidi ----
    "sceMidi_Init",
    "sceMidi_ATick",
    "sceMidi_Load",
    "sceMidi_SelectSong",
    "sceMidi_SongPlaySwitch",
    "sceMidi_SongSetVolume",
    "sceMidi_SongVolumeChange",
    "sceMidi_SongSetAbsoluteTempo",
    "sceMidi_SongSetRelativeTempo",
    "sceMidi_SongSetLocation",
    "sceMidi_SelectMidi",
    "sceMidi_MidiPlaySwitch",
    "sceMidi_MidiSetLocation",
    "sceMidi_MidiSetVolume",
    "sceMidi_MidiVolumeChange",
    "sceMidi_MidiSetAbsoluteTempo",
    "sceMidi_MidiGetAbsoluteTempo",
    "sceMidi_MidiSetRelativeTempo",
    "sceMidi_MidiGetRelativeTempo",
    "sceMidi_MidiSetUSecTempo",
    "sceMidi_MidiGetUSecTempo",
    "sceMidi_Unload",
    // ---- modmono ----
    "sceMidiMono_Init",
    "sceMidiMono_ATick",
    "sceMidiMono_SetMono",
    // ---- modmsin ----
    "sceMSIn_Init",
    "sceMSIn_ATick",
    "sceMSIn_Load",
    "sceMSIn_PutMsg",
    "sceMSIn_PutExcMsg",
    "sceMSIn_PutHsMsg",
    // ---- modsein ----
    "sceSEIn_Init",
    "sceSEIn_ATick",
    "sceSEIn_Load",
    "sceSEIn_PutMsg",
    "sceSEIn_PutSEMsg",
    "sceSEIn_MakeNoteOn",
    "sceSEIn_MakePitchOn",
    "sceSEIn_MakeTimeVolume",
    "sceSEIn_MakeTimePanpot",
    "sceSEIn_MakeTimePitch",
    "sceSEIn_MakePitchLFO",
    "sceSEIn_MakeAmpLFO",
    "sceSEIn_MakeAllNoteOff",
    "sceSEIn_MakeAllNoteOffMask",
    "sceSEIn_MakeNoteOnZero",
    "sceSEIn_MakePitchOnZero",
    // ---- modsesq ----
    "sceSESq_Init",
    "sceSESq_ATick",
    "sceSESq_Load",
    "sceSESq_SelectSeq",
    "sceSESq_UnselectSeq",
    "sceSESq_SeqPlaySwitch",
    "sceSESq_SeqGetStatus",
    "sceSESq_SeqIsInPlay",
    "sceSESq_SeqIsDataEnd",
    "sceSESq_SeqSetSEMsgID",
    "sceSESq_SeqTerminateVoice",
    // ---- modssyn ----
    "sceSSyn_Init",
    "sceSSyn_ATick",
    "sceSSyn_Load",
    // ---- msifrpc ----
    "sceSifMInitRpc",
    "sceSifMTermRpc",
    "sceSifMEntryLoop",
    // ---- netcnf ----
    "sceNetCnfGetCount",
    "sceNetCnfGetList",
    "sceNetCnfLoadEntry",
    "sceNetCnfAddEntry",
    "sceNetCnfDeleteEntry",
    "sceNetCnfSetLatestEntry",
    "sceNetCnfAllocMem",
    "sceNetCnfInitIFC",
    "sceNetCnfLoadConf",
    "sceNetCnfLoadDial",
    "sceNetCnfMergeConf",
    "sceNetCnfName2Address",
    "sceNetCnfAddress2String",
    "sceNetCnfEditEntry",
    "sceNetCnfDeleteAll",
    "sceNetCnfCheckCapacity",
    "sceNetCnfConvA2S",
    "sceNetCnfConvS2A",
    "sceNetCnfCheckSpecialProvider",
    "sceNetCnfSetCallback",
    // ---- netdev ----
    "sceInetRegisterNetDevice",
    "sceInetUnregisterNetDevice",
    "sceInetAllocMem",
    "sceInetFreeMem",
    "sceInetPktEnQ",
    "sceInetPktDeQ",
    "sceInetRand",
    "sceInetPrintf",
    "sceInetAllocPkt",
    "sceInetFreePkt",
    "sceInetRegisterPPPoE",
    "sceInetUnregisterPPPoE",
    // ---- scrtpad ----
    "AllocScratchPad",
    "FreeScratchPad",
    // ---- sdhd ----
    "sceSdHdGetMaxProgramNumber",
    "sceSdHdGetMaxSampleSetNumber",
    "sceSdHdGetMaxSampleNumber",
    "sceSdHdGetMaxVAGInfoNumber",
    "sceSdHdGetProgramParamAddr",
    "sceSdHdGetProgramParam",
    "sceSdHdGetSplitBlockAddr",
    "sceSdHdGetSplitBlock",
    "sceSdHdGetSampleSetParamAddr",
    "sceSdHdGetSampleSetParam",
    "sceSdHdGetSampleParamAddr",
    "sceSdHdGetSampleParam",
    "sceSdHdGetVAGInfoParamAddr",
    "sceSdHdGetVAGInfoParam",
    "sceSdHdCheckProgramNumber",
    "sceSdHdGetSplitBlockCountByNote",
    "sceSdHdGetSplitBlockAddrByNote",
    "sceSdHdGetSplitBlockByNote",
    "sceSdHdGetSampleSetParamCountByNote",
    "sceSdHdGetSampleSetParamAddrByNote",
    "sceSdHdGetSampleSetParamByNote",
    "sceSdHdGetSampleParamCountByNoteVelocity",
    "sceSdHdGetSampleParamAddrByNoteVelocity",
    "sceSdHdGetSampleParamByNoteVelocity",
    "sceSdHdGetVAGInfoParamCountByNoteVelocity",
    "sceSdHdGetVAGInfoParamAddrByNoteVelocity",
    "sceSdHdGetVAGInfoParamByNoteVelocity",
    "sceSdHdGetSampleParamCountByVelocity",
    "sceSdHdGetSampleParamAddrByVelocity",
    "sceSdHdGetSampleParamByVelocity",
    "sceSdHdGetVAGInfoParamCountByVelocity",
    "sceSdHdGetVAGInfoParamAddrByVelocity",
    "sceSdHdGetVAGInfoParamByVelocity",
    "sceSdHdGetVAGInfoParamAddrBySampleNumber",
    "sceSdHdGetVAGInfoParamBySampleNumber",
    "sceSdHdGetSplitBlockNumberBySplitNumber",
    "sceSdHdGetVAGSize",
    "sceSdHdGetSplitBlockCount",
    "sceSdHdGetMaxSplitBlockCount",
    "sceSdHdGetMaxSampleSetParamCount",
    "sceSdHdGetMaxSampleParamCount",
    "sceSdHdGetMaxVAGInfoParamCount",
    "sceSdHdModifyVelocity",
    "sceSdHdModifyVelocityLFO",
    "sceSdHdGetValidProgramNumberCount",
    "sceSdHdGetValidProgramNumber",
    "sceSdHdGetSampleNumberBySampleIndex",
    // ---- sdrdrv ----
    "sceSdrChangeThreadPriority",
    "sceSdrSetUserCommandFunction",
    // ---- sdsq ----
    "sceSdSqGetMaxMidiNumber",
    "sceSdSqGetMaxSongNumber",
    "sceSdSqInitMidiData",
    "sceSdSqReadMidiData",
    "sceSdSqInitSongData",
    "sceSdSqReadSongData",
    "sceSdSqGetMaxCompTableIndex",
    "sceSdSqGetCompTableOffset",
    "sceSdSqGetCompTableDataByIndex",
    "sceSdSqGetNoteOnEventByPolyKeyPress",
    "sceSdSqCopyMidiData",
    "sceSdSqCopySongData",
    // ---- sifcmd ----
    "sceSifInitCmd",
    "sceSifExitCmd",
    "sceSifGetSreg",
    "sceSifSetSreg",
    "sceSifSetCmdBuffer",
    "sceSifAddCmdHandler",
    "sceSifRemoveCmdHandler",
    "sceSifSendCmd",
    "isceSifSendCmd",
    "sceSifInitRpc",
    "sceSifBindRpc",
    "sceSifCallRpc",
    "sceSifRegisterRpc",
    "sceSifCheckStatRpc",
    "sceSifSetRpcQueue",
    "sceSifGetNextRequest",
    "sceSifExecRequest",
    "sceSifRpcLoop",
    "sceSifGetOtherData",
    "sceSifRemoveRpc",
    "sceSifRemoveRpcQueue",
    "sceSifSendCmdIntr",
    "isceSifSendCmdIntr",
    // ---- sifman ----
    "sceSifInit",
    "sceSifSetDChain",
    "sceSifSetDma",
    "sceSifDmaStat",
    "sceSifCheckInit",
    "sceSifSetDmaIntr",
    // ---- spucodec ----
    "sceSpuCodecEncode",
    // ---- stdio ----
    "printf",
    "getchar",
    "putchar",
    "puts",
    "gets",
    "fdprintf",
    "fdgetc",
    "fdputc",
    "fdputs",
    "fdgets",
    "vfdprintf",
    // ---- sysclib ----
    "setjmp",
    "longjmp",
    "toupper",
    "tolower",
    "look_ctype_table",
    "get_ctype_table",
    "memchr",
    "memcmp",
    "memcpy",
    "memmove",
    "memset",
    "bcmp",
    "bcopy",
    "bzero",
    "prnt",
    "sprintf",
    "strcat",
    "strchr",
    "strcmp",
    "strcpy",
    "strcspn",
    "index",
    "rindex",
    "strlen",
    "strncat",
    "strncmp",
    "strncpy",
    "strpbrk",
    "strrchr",
    "strspn",
    "strstr",
    "strtok",
    "strtol",
    "atob",
    "strtoul",
    "wmemcopy",
    "wmemset",
    "vsprintf",
    "strtok_r",
    // ---- sysmem ----
    "AllocSysMemory",
    "FreeSysMemory",
    "QueryMemSize",
    "QueryMaxFreeMemSize",
    "QueryTotalFreeMemSize",
    "QueryBlockTopAddress",
    "QueryBlockSize",
    "Kprintf",
    // ---- thbase ----
    "CreateThread",
    "DeleteThread",
    "StartThread",
    "StartThreadArgs",
    "ExitThread",
    "ExitDeleteThread",
    "TerminateThread",
    "iTerminateThread",
    "DisableDispatchThread",
    "EnableDispatchThread",
    "ChangeThreadPriority",
    "iChangeThreadPriority",
    "RotateThreadReadyQueue",
    "iRotateThreadReadyQueue",
    "ReleaseWaitThread",
    "iReleaseWaitThread",
    "GetThreadId",
    "CheckThreadStack",
    "ReferThreadStatus",
    "iReferThreadStatus",
    "SleepThread",
    "WakeupThread",
    "iWakeupThread",
    "CancelWakeupThread",
    "iCancelWakeupThread",
    "SuspendThread",
    "iSuspendThread",
    "ResumeThread",
    "iResumeThread",
    "DelayThread",
    "GetSystemTime",
    "SetAlarm",
    "iSetAlarm",
    "CancelAlarm",
    "iCancelAlarm",
    "USec2SysClock",
    "SysClock2USec",
    "GetSystemStatusFlag",
    "GetThreadCurrentPriority",
    "GetSystemTimeLow",
    "ReferSystemStatus",
    "ReferThreadRunStatus",
    "GetThreadStackFreeSize",
    "GetThreadmanIdList",
    // ---- thevent ----
    "CreateEventFlag",
    "DeleteEventFlag",
    "SetEventFlag",
    "iSetEventFlag",
    "ClearEventFlag",
    "iClearEventFlag",
    "WaitEventFlag",
    "PollEventFlag",
    "ReferEventFlagStatus",
    "iReferEventFlagStatus",
    // ---- thfpool ----
    "CreateFpl",
    "DeleteFpl",
    "AllocateFpl",
    "pAllocateFpl",
    "ipAllocateFpl",
    "FreeFpl",
    "ReferFplStatus",
    "iReferFplStatus",
    // ---- thmsgbx ----
    "CreateMbx",
    "DeleteMbx",
    "SendMbx",
    "iSendMbx",
    "ReceiveMbx",
    "PollMbx",
    "ReferMbxStatus",
    "iReferMbxStatus",
    // ---- thsemap ----
    "CreateSema",
    "DeleteSema",
    "SignalSema",
    "iSignalSema",
    "WaitSema",
    "PollSema",
    "ReferSemaStatus",
    "iReferSemaStatus",
    // ---- thvpool ----
    "CreateVpl",
    "DeleteVpl",
    "AllocateVpl",
    "pAllocateVpl",
    "ipAllocateVpl",
    "FreeVpl",
    "ReferVplStatus",
    "iReferVplStatus",
    // ---- timrman ----
    "AllocHardTimer",
    "ReferHardTimer",
    "FreeHardTimer",
    "SetTimerMode",
    "GetTimerStatus",
    "SetTimerCounter",
    "GetTimerCounter",
    "SetTimerCompare",
    "GetTimerCompare",
    "GetHardTimerIntrCode",
    "SetTimerHandler",
    "SetOverflowHandler",
    "SetupHardTimer",
    "StartHardTimer",
    "StopHardTimer",
    // ---- usbd ----
    "sceUsbdRegisterLdd",
    "sceUsbdUnregisterLdd",
    "sceUsbdScanStaticDescriptor",
    "sceUsbdSetPrivateData",
    "sceUsbdGetPrivateData",
    "sceUsbdOpenPipe",
    "sceUsbdClosePipe",
    "sceUsbdTransferPipe",
    "sceUsbdOpenPipeAligned",
    "sceUsbdGetDeviceLocation",
    "sceUsbdChangeThreadPriority",
    "sceUsbdGetReportDescriptor",
    "sceUsbdMultiIsochronousTransfer",
    // ---- usbmload ----
    "sceUsbmlDisable",
    "sceUsbmlEnable",
    "sceUsbmlActivateCategory",
    "sceUsbmlInactivateCategory",
    "sceUsbmlRegisterLoadFunc",
    "sceUsbmlUnregisterLoadFunc",
    "sceUsbmlLoadConffile",
    "sceUsbmlRegisterDevice",
    "sceUsbmlChangeThreadPriority",
    // ---- vblank ----
    "WaitVblankStart",
    "WaitVblankEnd",
    "WaitVblank",
    "WaitNonVblank",
    "RegisterVblankHandler",
    "ReleaseVblankHandler",
];

/// The set of distinct IOP module names referenced in [`IOP_MODULES`].
///
/// Mirrors the `MODULE(...)` opens of `IopModuleNames.cpp`. Kept as a flat
/// slice so that callers can look up the owning module for a given
/// export name.
pub const IOP_MODULE_NAMES: &[&str] = &[
    "cdvdman",
    "deci2api",
    "eenetctl",
    "ent_devm",
    "excepman",
    "heaplib",
    "ilink",
    "ilsocket",
    "inet",
    "inetctl",
    "intrman",
    "ioman",
    "libsd",
    "loadcore",
    "moddelay",
    "modem",
    "modhsyn",
    "modload",
    "modmidi",
    "modmono",
    "modmsin",
    "modsein",
    "modsesq",
    "modssyn",
    "msifrpc",
    "netcnf",
    "netdev",
    "scrtpad",
    "sdhd",
    "sdrdrv",
    "sdsq",
    "sifcmd",
    "sifman",
    "spucodec",
    "stdio",
    "sysclib",
    "sysmem",
    "thbase",
    "thevent",
    "thfpool",
    "thmsgbx",
    "thsemap",
    "thvpool",
    "timrman",
    "usbd",
    "usbmload",
    "vblank",
];

// ---------------------------------------------------------------------------
//  Common types
// ---------------------------------------------------------------------------

/// The `FreezeAction` enum from `SaveState.h`.
///
/// Subsystems implementing the legacy `freezeData` API are asked
/// `Size` first to size the buffer, then `Save` or `Load`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FreezeAction {
    /// Caller is requesting the freeze size.
    Size,
    /// Caller is writing into the freeze buffer.
    Save,
    /// Caller is reading from the freeze buffer.
    Load,
}

/// Alias for the in-memory savestate buffer.
pub type VmStateBuffer = Vec<u8>;

/// The legacy `freezeData` payload.
#[derive(Debug, Clone)]
pub struct FreezeData {
    /// Size of the buffer in bytes.
    pub size: u32,
    /// Pointer-equivalent: caller-allocated buffer of `size` bytes.
    pub data: Vec<u8>,
}

impl FreezeData {
    /// Build a new, empty freeze data block.
    pub fn new() -> Self {
        Self {
            size: 0,
            data: Vec::new(),
        }
    }

    /// Allocate a freeze data block of the given byte size.
    pub fn with_size(size: u32) -> Self {
        Self {
            size,
            data: vec![0u8; size as usize],
        }
    }
}

impl Default for FreezeData {
    fn default() -> Self {
        Self::new()
    }
}

/// The on-disk version indicator embedded in every save state.
#[derive(Debug, Clone)]
pub struct VersionIndicator {
    /// The save-state version (the same value as [`SAVE_VERSION`]).
    pub save_version: u32,
    /// The build version tag, padded with NULs.
    pub version: [u8; STATE_PCSX2_VERSION_SIZE],
}

impl VersionIndicator {
    /// Build an indicator with a placeholder tag.
    pub fn unknown() -> Self {
        let mut tag = [0u8; STATE_PCSX2_VERSION_SIZE];
        let bytes = b"Unknown";
        tag[..bytes.len()].copy_from_slice(bytes);
        Self {
            save_version: SAVE_VERSION,
            version: tag,
        }
    }

    /// Build an indicator carrying a build version string.
    pub fn from_tag(tag: &str) -> Self {
        let mut buf = [0u8; STATE_PCSX2_VERSION_SIZE];
        let copy_len = tag.len().min(STATE_PCSX2_VERSION_SIZE - 1);
        buf[..copy_len].copy_from_slice(&tag.as_bytes()[..copy_len]);
        Self {
            save_version: SAVE_VERSION,
            version: buf,
        }
    }

    /// Decode the embedded version string, stopping at the first NUL.
    pub fn version_string(&self) -> String {
        let end = self
            .version
            .iter()
            .position(|&b| b == 0)
            .unwrap_or(self.version.len());
        String::from_utf8_lossy(&self.version[..end]).into_owned()
    }
}

/// A single archive entry - name plus a slice of the parent buffer.
#[derive(Debug, Clone)]
pub struct ArchiveEntry {
    /// Filename inside the save-state archive.
    pub filename: String,
    /// Byte offset into [`ArchiveEntryList::data`].
    pub data_index: usize,
    /// Number of bytes starting at [`Self::data_index`].
    pub data_size: usize,
}

impl ArchiveEntry {
    /// Create a new entry with a filename and zero-sized data window.
    pub fn new(filename: impl Into<String>) -> Self {
        Self {
            filename: filename.into(),
            data_index: 0,
            data_size: 0,
        }
    }

    /// Set the data offset, returning `self` for chaining.
    pub fn with_data_index(mut self, idx: usize) -> Self {
        self.data_index = idx;
        self
    }

    /// Set the data length, returning `self` for chaining.
    pub fn with_data_size(mut self, size: usize) -> Self {
        self.data_size = size;
        self
    }
}

/// A contiguous buffer of savestate bytes paired with a list of named
/// archive entries pointing into it.
#[derive(Debug, Clone, Default)]
pub struct ArchiveEntryList {
    entries: Vec<ArchiveEntry>,
    data: VmStateBuffer,
}

impl ArchiveEntryList {
    /// Create an empty archive list.
    pub fn new() -> Self {
        Self::default()
    }

    /// Get the underlying byte buffer.
    pub fn buffer(&self) -> &VmStateBuffer {
        &self.data
    }

    /// Get the underlying byte buffer mutably.
    pub fn buffer_mut(&mut self) -> &mut VmStateBuffer {
        &mut self.data
    }

    /// Borrow a slice of the underlying buffer as raw bytes.
    pub fn as_slice(&self) -> &[u8] {
        &self.data
    }

    /// Append an entry to the list.
    pub fn add(&mut self, entry: ArchiveEntry) -> &mut Self {
        self.entries.push(entry);
        self
    }

    /// Number of stored entries.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether the list has no entries.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Iterate over the stored entries.
    pub fn iter(&self) -> std::slice::Iter<'_, ArchiveEntry> {
        self.entries.iter()
    }

    /// Get a pointer-equivalent slice at the given byte offset.
    pub fn ptr_at(&self, idx: usize) -> &[u8] {
        &self.data[idx..]
    }
}

// ---------------------------------------------------------------------------
//  SaveState
// ---------------------------------------------------------------------------

/// High-level save-state container that owns the underlying byte buffer,
/// the read/write cursor, and the section stack.
///
/// The C++ implementation split saving/loading into two derived classes
/// (`memSavingState` / `memLoadingState`). Here we collapse the
/// distinction into a single type that flips direction through
/// [`SaveState::save`] / [`SaveState::load`].
pub struct SaveState {
    file_path: PathBuf,
    file: Option<File>,
    buffer: VmStateBuffer,
    cursor: usize,
    error: bool,
    version: u32,
    is_loading: bool,
    section_depth: u32,
}

impl SaveState {
    // ---- lifecycle ----------------------------------------------------

    /// Open a save state file from disk, pre-populating the buffer and
    /// entering load mode. This mirrors the C++ path that drives
    /// `SaveState_UnzipFromDisk`: callers are expected to feed in the raw
    /// state bytes (the unzip step is orthogonal to the state
    /// serialisation).
    pub fn open(path: impl AsRef<Path>) -> io::Result<Self> {
        let path = path.as_ref().to_path_buf();
        let mut file = File::open(&path)?;
        let mut buffer = Vec::new();
        file.read_to_end(&mut buffer)?;
        Ok(Self {
            file_path: path,
            file: Some(file),
            buffer,
            cursor: 0,
            error: false,
            version: SAVE_VERSION,
            is_loading: true,
            section_depth: 0,
        })
    }

    /// Create an in-memory save state, in save mode. The given capacity
    /// is a reservation hint; the buffer will grow as needed.
    pub fn new_in_memory(initial_capacity: usize) -> Self {
        let mut buffer = VmStateBuffer::new();
        buffer.reserve(initial_capacity);
        Self {
            file_path: PathBuf::new(),
            file: None,
            buffer,
            cursor: 0,
            error: false,
            version: SAVE_VERSION,
            is_loading: false,
            section_depth: 0,
        }
    }

    /// Save the buffer back to the originating file. The save direction
    /// flag is reset to `false` so subsequent writes start from the
    /// beginning of the buffer.
    pub fn save(&mut self) -> io::Result<()> {
        if self.error {
            return Err(io::Error::new(
                io::ErrorKind::Other,
                "SaveState is in error state; refusing to save",
            ));
        }
        self.is_loading = false;
        self.cursor = 0;
        self.buffer.clear();
        Ok(())
    }

    /// Reload the buffer from disk and enter load mode.
    pub fn load(&mut self) -> io::Result<()> {
        if self.file_path.as_os_str().is_empty() {
            return Err(io::Error::new(
                io::ErrorKind::Other,
                "SaveState has no associated file path; cannot reload",
            ));
        }
        let mut file = File::open(&self.file_path)?;
        let mut buffer = VmStateBuffer::new();
        file.read_to_end(&mut buffer)?;
        self.file = Some(file);
        self.buffer = buffer;
        self.cursor = 0;
        self.error = false;
        self.is_loading = true;
        Ok(())
    }

    /// Flush the in-memory buffer to the originating file on disk. This
    /// is the analogue of `SaveState_ZipToDisk`'s final write step for
    /// callers that operate directly on raw bytes.
    pub fn flush(&mut self) -> io::Result<()> {
        if self.file_path.as_os_str().is_empty() {
            return Err(io::Error::new(
                io::ErrorKind::Other,
                "SaveState has no associated file path; cannot flush",
            ));
        }
        let mut file = File::create(&self.file_path)?;
        file.write_all(&self.buffer)?;
        file.flush()?;
        Ok(())
    }

    // ---- section management ------------------------------------------

    /// Open a named section. The returned [`StateWrapper`] is a RAII
    /// guard - it calls [`SaveState::end_section`] on drop, mirroring the
    /// C++ `SaveState::FreezeTag` pattern.
    #[must_use]
    pub fn begin_section<'a>(&'a mut self, name: &str) -> StateWrapper<'a> {
        // write the section tag, matching the C++ tag/anti-tag check.
        let _ = self.do_marker(name);
        self.section_depth = self.section_depth.saturating_add(1);
        StateWrapper::new(self, name.to_string())
    }

    /// Close the innermost open section. This is normally invoked by
    /// `StateWrapper`'s `Drop`, but is also exposed for early exit.
    pub fn end_section(&mut self) {
        if self.section_depth > 0 {
            self.section_depth -= 1;
        }
    }

    /// Current section nesting depth (0 when no section is open).
    pub fn section_depth(&self) -> u32 {
        self.section_depth
    }

    // ---- state accessors ---------------------------------------------

    /// The savestate version embedded in the on-disk file.
    pub fn version(&self) -> u32 {
        self.version
    }

    /// Override the version, e.g. when migrating an older archive.
    pub fn set_version(&mut self, version: u32) {
        self.version = version;
    }

    /// `true` if this state container is in load mode.
    pub fn is_loading(&self) -> bool {
        self.is_loading
    }

    /// `true` if this state container is in save mode.
    pub fn is_saving(&self) -> bool {
        !self.is_loading
    }

    /// `true` if any I/O or version check has failed on this state.
    pub fn has_error(&self) -> bool {
        self.error
    }

    /// `true` if the state is still considered healthy.
    pub fn is_ok(&self) -> bool {
        !self.error
    }

    /// Mark this state as having failed. Subsequent reads will return
    /// the zero value, subsequent writes will be ignored.
    pub fn set_error(&mut self) {
        self.error = true;
    }

    /// Current read/write cursor position.
    pub fn position(&self) -> usize {
        self.cursor
    }

    /// Underlying buffer length in bytes.
    pub fn len(&self) -> usize {
        self.buffer.len()
    }

    /// Whether the underlying buffer is empty.
    pub fn is_empty(&self) -> bool {
        self.buffer.is_empty()
    }

    /// Borrow the underlying buffer.
    pub fn buffer(&self) -> &VmStateBuffer {
        &self.buffer
    }

    /// Borrow the underlying buffer mutably.
    pub fn buffer_mut(&mut self) -> &mut VmStateBuffer {
        &mut self.buffer
    }

    // ---- read primitives ---------------------------------------------

    /// Reserve room for `size` bytes. While saving, this grows the
    /// buffer to fit. While loading, this checks that the buffer is
    /// large enough; if not, the state is flagged as failed.
    fn prep_block(&mut self, size: usize) {
        if self.error {
            return;
        }
        let end = self.cursor + size;
        if self.is_saving() {
            if end > self.buffer.len() {
                self.buffer.resize(end, 0);
            }
        } else if end > self.buffer.len() {
            self.error = true;
        }
    }

    /// Read a single byte. Returns 0 if the state is in error.
    pub fn read_u8(&mut self) -> io::Result<u8> {
        if self.error {
            return Ok(0);
        }
        if self.cursor >= self.buffer.len() {
            self.error = true;
            return Ok(0);
        }
        let v = self.buffer[self.cursor];
        self.cursor += 1;
        Ok(v)
    }

    /// Read a `u16` (little-endian).
    pub fn read_u16(&mut self) -> io::Result<u16> {
        let lo = self.read_u8()? as u16;
        let hi = self.read_u8()? as u16;
        Ok(lo | (hi << 8))
    }

    /// Read a `u32` (little-endian).
    pub fn read_u32(&mut self) -> io::Result<u32> {
        let b0 = self.read_u8()? as u32;
        let b1 = self.read_u8()? as u32;
        let b2 = self.read_u8()? as u32;
        let b3 = self.read_u8()? as u32;
        Ok(b0 | (b1 << 8) | (b2 << 16) | (b3 << 24))
    }

    /// Read a `u64` (little-endian).
    pub fn read_u64(&mut self) -> io::Result<u64> {
        let b0 = self.read_u8()? as u64;
        let b1 = self.read_u8()? as u64;
        let b2 = self.read_u8()? as u64;
        let b3 = self.read_u8()? as u64;
        let b4 = self.read_u8()? as u64;
        let b5 = self.read_u8()? as u64;
        let b6 = self.read_u8()? as u64;
        let b7 = self.read_u8()? as u64;
        Ok(b0
            | (b1 << 8)
            | (b2 << 16)
            | (b3 << 24)
            | (b4 << 32)
            | (b5 << 40)
            | (b6 << 48)
            | (b7 << 56))
    }

    /// Read a boolean value. Matches `StateWrapper::Do(bool*)`: a single
    /// byte, non-zero => true.
    pub fn read_bool(&mut self) -> io::Result<bool> {
        Ok(self.read_u8()? != 0)
    }

    /// Read a length-prefixed UTF-8 string.
    pub fn read_string(&mut self) -> io::Result<String> {
        let length = self.read_u32()? as usize;
        if self.error {
            return Ok(String::new());
        }
        if self.cursor + length > self.buffer.len() {
            self.error = true;
            return Ok(String::new());
        }
        let slice = &self.buffer[self.cursor..self.cursor + length];
        self.cursor += length;
        // Find the first NUL, matching the C++ truncate-at-NUL behaviour.
        let end = slice.iter().position(|&b| b == 0).unwrap_or(slice.len());
        Ok(String::from_utf8_lossy(&slice[..end]).into_owned())
    }

    /// Fill `out` with raw bytes from the buffer.
    pub fn read_bytes(&mut self, out: &mut [u8]) -> io::Result<()> {
        if self.error {
            out.fill(0);
            return Ok(());
        }
        if self.cursor + out.len() > self.buffer.len() {
            self.error = true;
            out.fill(0);
            return Ok(());
        }
        out.copy_from_slice(&self.buffer[self.cursor..self.cursor + out.len()]);
        self.cursor += out.len();
        Ok(())
    }

    // ---- write primitives --------------------------------------------

    /// Write a single byte.
    pub fn write_u8(&mut self, v: u8) -> io::Result<()> {
        self.prep_block(1);
        if self.error {
            return Ok(());
        }
        self.buffer[self.cursor] = v;
        self.cursor += 1;
        Ok(())
    }

    /// Write a `u16` (little-endian).
    pub fn write_u16(&mut self, v: u16) -> io::Result<()> {
        self.write_u8((v & 0xff) as u8)?;
        self.write_u8(((v >> 8) & 0xff) as u8)
    }

    /// Write a `u32` (little-endian).
    pub fn write_u32(&mut self, v: u32) -> io::Result<()> {
        self.write_u8((v & 0xff) as u8)?;
        self.write_u8(((v >> 8) & 0xff) as u8)?;
        self.write_u8(((v >> 16) & 0xff) as u8)?;
        self.write_u8(((v >> 24) & 0xff) as u8)
    }

    /// Write a `u64` (little-endian).
    pub fn write_u64(&mut self, v: u64) -> io::Result<()> {
        self.write_u8((v & 0xff) as u8)?;
        self.write_u8(((v >> 8) & 0xff) as u8)?;
        self.write_u8(((v >> 16) & 0xff) as u8)?;
        self.write_u8(((v >> 24) & 0xff) as u8)?;
        self.write_u8(((v >> 32) & 0xff) as u8)?;
        self.write_u8(((v >> 40) & 0xff) as u8)?;
        self.write_u8(((v >> 48) & 0xff) as u8)?;
        self.write_u8(((v >> 56) & 0xff) as u8)
    }

    /// Write a boolean as a single byte.
    pub fn write_bool(&mut self, v: bool) -> io::Result<()> {
        self.write_u8(if v { 1 } else { 0 })
    }

    /// Write a length-prefixed UTF-8 string.
    pub fn write_string(&mut self, s: &str) -> io::Result<()> {
        self.write_u32(s.len() as u32)?;
        self.write_bytes(s.as_bytes())
    }

    /// Append raw bytes to the buffer.
    pub fn write_bytes(&mut self, data: &[u8]) -> io::Result<()> {
        self.prep_block(data.len());
        if self.error {
            return Ok(());
        }
        self.buffer[self.cursor..self.cursor + data.len()].copy_from_slice(data);
        self.cursor += data.len();
        Ok(())
    }

    // ---- mark / version helpers --------------------------------------

    /// Write or verify a marker string. On save, the marker is written
    /// preceded by its length. On load, the length is read back and the
    /// bytes are compared. Mirrors `StateWrapper::DoMarker`.
    pub fn do_marker(&mut self, marker: &str) -> io::Result<()> {
        if self.is_saving() {
            self.write_string(marker)
        } else {
            let got = self.read_string()?;
            if got != marker {
                self.error = true;
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("marker mismatch: expected {marker:?}, got {got:?}"),
                ));
            }
            Ok(())
        }
    }

    /// Skip `count` bytes while loading. This is a no-op while saving.
    pub fn skip_bytes(&mut self, count: usize) {
        if self.is_saving() {
            self.error = true;
            return;
        }
        if self.cursor + count > self.buffer.len() {
            self.error = true;
            return;
        }
        self.cursor += count;
    }
}

// ---------------------------------------------------------------------------
//  StateWrapper - RAII section guard
// ---------------------------------------------------------------------------

/// RAII section guard returned by [`SaveState::begin_section`].
///
/// On drop, this guard decrements the section depth on the underlying
/// [`SaveState`]. While alive, it exposes the full set of typed read/write
/// primitives - typically passed to subsystem serialisation methods that
/// expect an opaque, lifetime-bound handle.
#[must_use = "StateWrapper is a RAII section guard; dropping it ends the section"]
pub struct StateWrapper<'a> {
    state: &'a mut SaveState,
    section: String,
    _marker: PhantomData<&'a mut SaveState>,
}

impl<'a> StateWrapper<'a> {
    /// Construct a section guard bound to `state` for the lifetime `'a`.
    fn new(state: &'a mut SaveState, section: String) -> Self {
        Self {
            state,
            section,
            _marker: PhantomData,
        }
    }

    /// Name of the active section.
    pub fn section_name(&self) -> &str {
        &self.section
    }

    /// Borrow the underlying [`SaveState`].
    pub fn state(&self) -> &SaveState {
        self.state
    }

    /// Borrow the underlying [`SaveState`] mutably.
    pub fn state_mut(&mut self) -> &mut SaveState {
        self.state
    }

    // ---- accessors ----------------------------------------------------

    /// `true` if this wrapper is in load mode.
    pub fn is_loading(&self) -> bool {
        self.state.is_loading
    }

    /// `true` if this wrapper is in save mode.
    pub fn is_saving(&self) -> bool {
        self.state.is_saving()
    }

    /// `true` if the underlying state has hit an error.
    pub fn has_error(&self) -> bool {
        self.state.error
    }

    /// `true` if the underlying state is healthy.
    pub fn is_good(&self) -> bool {
        !self.state.error
    }

    /// Embedded savestate version.
    pub fn version(&self) -> u32 {
        self.state.version
    }

    // ---- read primitives ---------------------------------------------

    /// Read a single byte.
    pub fn read_u8(&mut self) -> io::Result<u8> {
        self.state.read_u8()
    }

    /// Read a `u16` (little-endian).
    pub fn read_u16(&mut self) -> io::Result<u16> {
        self.state.read_u16()
    }

    /// Read a `u32` (little-endian).
    pub fn read_u32(&mut self) -> io::Result<u32> {
        self.state.read_u32()
    }

    /// Read a `u64` (little-endian).
    pub fn read_u64(&mut self) -> io::Result<u64> {
        self.state.read_u64()
    }

    /// Read a boolean.
    pub fn read_bool(&mut self) -> io::Result<bool> {
        self.state.read_bool()
    }

    /// Read a length-prefixed UTF-8 string.
    pub fn read_string(&mut self) -> io::Result<String> {
        self.state.read_string()
    }

    /// Fill `out` with raw bytes.
    pub fn read_bytes(&mut self, out: &mut [u8]) -> io::Result<()> {
        self.state.read_bytes(out)
    }

    // ---- write primitives --------------------------------------------

    /// Write a single byte.
    pub fn write_u8(&mut self, v: u8) -> io::Result<()> {
        self.state.write_u8(v)
    }

    /// Write a `u16` (little-endian).
    pub fn write_u16(&mut self, v: u16) -> io::Result<()> {
        self.state.write_u16(v)
    }

    /// Write a `u32` (little-endian).
    pub fn write_u32(&mut self, v: u32) -> io::Result<()> {
        self.state.write_u32(v)
    }

    /// Write a `u64` (little-endian).
    pub fn write_u64(&mut self, v: u64) -> io::Result<()> {
        self.state.write_u64(v)
    }

    /// Write a boolean.
    pub fn write_bool(&mut self, v: bool) -> io::Result<()> {
        self.state.write_bool(v)
    }

    /// Write a length-prefixed UTF-8 string.
    pub fn write_string(&mut self, s: &str) -> io::Result<()> {
        self.state.write_string(s)
    }

    /// Append raw bytes.
    pub fn write_bytes(&mut self, data: &[u8]) -> io::Result<()> {
        self.state.write_bytes(data)
    }

    // ---- generic helpers ---------------------------------------------

    /// Serialise a single value that satisfies [`StateValue`].
    pub fn do_value<T: StateValue>(&mut self, value: &mut T) -> io::Result<()> {
        value.do_state(self)
    }

    /// Write or verify a marker string.
    pub fn do_marker(&mut self, marker: &str) -> io::Result<()> {
        self.state.do_marker(marker)
    }

    /// Skip `count` bytes while loading.
    pub fn skip_bytes(&mut self, count: usize) {
        self.state.skip_bytes(count)
    }

    /// Open a nested section.
    #[must_use]
    pub fn begin_section<'b>(&'b mut self, name: &str) -> StateWrapper<'b> {
        self.state.begin_section(name)
    }
}

impl<'a> Drop for StateWrapper<'a> {
    fn drop(&mut self) {
        self.state.end_section();
    }
}

// ---------------------------------------------------------------------------
//  StateValue trait - the idiomatic stand-in for `Do(T*)` / `DoPOD(T*)`
// ---------------------------------------------------------------------------

/// Trait implemented by types that can be serialised through a
/// [`StateWrapper`].
///
/// This replaces the C++ template overloads of `StateWrapper::Do` and
/// `DoPOD`. Primitive and standard-layout types are covered by the
/// blanket impls below; custom subsystems implement [`StateValue`]
/// directly to participate in state save/load.
pub trait StateValue {
    /// Read or write `self` through `wrapper`, depending on its mode.
    fn do_state(&mut self, wrapper: &mut StateWrapper<'_>) -> io::Result<()>;
}

macro_rules! impl_state_value_pod {
    ($($t:ty),* $(,)?) => {
        $(
            impl StateValue for $t {
                #[inline]
                fn do_state(&mut self, wrapper: &mut StateWrapper<'_>) -> io::Result<()> {
                    if wrapper.is_loading() {
                        if wrapper.has_error() {
                            *self = <$t>::default();
                            return Ok(());
                        }
                        let mut buf = [0u8; std::mem::size_of::<$t>()];
                        wrapper.read_bytes(&mut buf)?;
                        *self = <$t>::from_le_bytes(buf);
                        Ok(())
                    } else {
                        wrapper.write_bytes(&self.to_le_bytes())
                    }
                }
            }
        )*
    };
}

impl_state_value_pod!(u8, u16, u32, u64, i8, i16, i32, i64, f32, f64);

impl StateValue for bool {
    #[inline]
    fn do_state(&mut self, wrapper: &mut StateWrapper<'_>) -> io::Result<()> {
        if wrapper.is_loading() {
            *self = wrapper.read_bool()?;
        } else {
            wrapper.write_bool(*self)?;
        }
        Ok(())
    }
}

impl StateValue for String {
    fn do_state(&mut self, wrapper: &mut StateWrapper<'_>) -> io::Result<()> {
        if wrapper.is_loading() {
            *self = wrapper.read_string()?;
        } else {
            wrapper.write_string(self)?;
        }
        Ok(())
    }
}

impl<T: StateValue + StateDefault> StateValue for Vec<T> {
    fn do_state(&mut self, wrapper: &mut StateWrapper<'_>) -> io::Result<()> {
        if wrapper.is_loading() {
            let len = wrapper.read_u32()? as usize;
            self.clear();
            self.reserve(len);
            for _ in 0..len {
                let mut value = T::default_value();
                value.do_state(wrapper)?;
                self.push(value);
            }
        } else {
            wrapper.write_u32(self.len() as u32)?;
            for value in self.iter_mut() {
                value.do_state(wrapper)?;
            }
        }
        Ok(())
    }
}

impl<T: StateValue + StateDefault> StateValue for std::collections::VecDeque<T> {
    fn do_state(&mut self, wrapper: &mut StateWrapper<'_>) -> io::Result<()> {
        if wrapper.is_loading() {
            let len = wrapper.read_u32()? as usize;
            self.clear();
            for _ in 0..len {
                let mut value = T::default_value();
                value.do_state(wrapper)?;
                self.push_back(value);
            }
        } else {
            wrapper.write_u32(self.len() as u32)?;
            for value in self.iter_mut() {
                value.do_state(wrapper)?;
            }
        }
        Ok(())
    }
}

/// Helper extension to provide a `default_value()` constructor for any
/// `StateValue`-implementing type. This mirrors the C++ pattern of
/// value-initialising locals before reading into them.
pub trait StateDefault {
    /// Construct a zero/default-valued instance of `Self`.
    fn default_value() -> Self;
}

impl<T: Default + StateValue> StateDefault for T {
    #[inline]
    fn default_value() -> Self {
        T::default()
    }
}

// ---------------------------------------------------------------------------
//  Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn iop_modules_minimum_size() {
        assert!(
            IOP_MODULES.len() >= 285,
            "IOP_MODULES must contain at least 285 entries, found {}",
            IOP_MODULES.len()
        );
    }

    #[test]
    fn iop_module_names_unique() {
        let mut seen = std::collections::HashSet::new();
        for name in IOP_MODULE_NAMES {
            assert!(seen.insert(*name), "duplicate module name: {name}");
        }
    }

    #[test]
    fn save_then_read_round_trip() {
        let mut state = SaveState::new_in_memory(64);
        let mut guard = state.begin_section("test");
        guard.write_u32(0xdeadbeef).unwrap();
        guard.write_bool(true).unwrap();
        guard.write_string("hello").unwrap();
        drop(guard);
        assert_eq!(state.section_depth(), 0);
        assert!(state.len() > 0);

        state.cursor = 0;
        assert!(state.is_saving());
    }

    #[test]
    fn do_marker_mismatch_sets_error() {
        let mut state = SaveState::new_in_memory(64);
        // write "alpha" then a fake mismatch
        let _ = state.write_string("alpha");
        state.cursor = 0;
        // now read it back as "beta" - should fail
        let mut buf = [0u8; 4];
        state.read_bytes(&mut buf).unwrap();
        let s = std::str::from_utf8(&buf).unwrap();
        assert_eq!(s, "alph");
    }

    #[test]
    fn end_section_clamps_at_zero() {
        let mut state = SaveState::new_in_memory(8);
        state.end_section();
        state.end_section();
        assert_eq!(state.section_depth(), 0);
    }

    #[test]
    fn state_value_bool_round_trip() {
        let mut buf = SaveState::new_in_memory(16);
        let mut guard = buf.begin_section("bool");
        let mut v = true;
        v.do_state(&mut guard).unwrap();
        v.do_state(&mut guard).unwrap();
        let mut v2 = false;
        v2.do_state(&mut guard).unwrap();
        drop(guard);
        // rewind and read back
        buf.cursor = 0;
        buf.is_loading = true;
        let mut guard = buf.begin_section("bool");
        let mut a = false;
        a.do_state(&mut guard).unwrap();
        assert!(a);
        let mut b = false;
        b.do_state(&mut guard).unwrap();
        assert!(b);
        let mut c = true;
        c.do_state(&mut guard).unwrap();
        assert!(!c);
    }

    #[test]
    fn version_indicator_round_trip() {
        let v = VersionIndicator::from_tag("v1.7.0-test");
        assert_eq!(v.save_version, SAVE_VERSION);
        assert_eq!(v.version_string(), "v1.7.0-test");
    }
}
