#ifndef PCSX2_COMMON_RS_H
#define PCSX2_COMMON_RS_H

/* Auto-generated by cbindgen. Do not edit. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace pcsx2 {

/// Pi, matching the original C++ constant exactly (10 significant digits).
/// The C++ header uses `3.1415926545f`, so we mirror that bit-for-bit here
/// rather than `std::f32::consts::PI` (which is `3.14159274`) or
/// `std::f64::consts::PI`.
constexpr static const float PI = 3.1415926545;

/// `__pagesize - 1`. Useful for rounding an address down to a page
/// boundary: `addr & !__pagemask` -> aligned, `addr & __pagemask` ->
/// intra-page offset.
constexpr static const uint32_t __pagemask = (__pagesize - 1);

/// Page-alignment size used for globals. PCSX2 uses a fixed 4 KiB
/// alignment on both x86 and ARM64 because the latter can compute the
/// page address with a single `adrp` instruction.
constexpr static const uint32_t __pagealignsize = 4096;

/// 1 KiB.
constexpr static const intptr_t _1kb = 1024;

/// 4 KiB.
constexpr static const intptr_t _4kb = (_1kb * 4);

/// 16 KiB.
constexpr static const intptr_t _16kb = (_1kb * 16);

/// 32 KiB.
constexpr static const intptr_t _32kb = (_1kb * 32);

/// 64 KiB.
constexpr static const intptr_t _64kb = (_1kb * 64);

/// 128 KiB.
constexpr static const intptr_t _128kb = (_1kb * 128);

/// 256 KiB.
constexpr static const intptr_t _256kb = (_1kb * 256);

/// 1 MiB.
constexpr static const int64_t _1mb = (1024 * 1024);

/// 8 MiB.
constexpr static const int64_t _8mb = (_1mb * 8);

/// 16 MiB.
constexpr static const int64_t _16mb = (_1mb * 16);

/// 32 MiB.
constexpr static const int64_t _32mb = (_1mb * 32);

/// 64 MiB.
constexpr static const int64_t _64mb = (_1mb * 64);

/// 256 MiB.
constexpr static const int64_t _256mb = (_1mb * 256);

/// 1 GiB.
constexpr static const int64_t _1gb = (_1mb * 1024);

/// 4 GiB.
constexpr static const int64_t _4gb = (_1gb * 4);

constexpr static const uintptr_t SHADOW_STACK_SIZE = 32;

/// Number of valid rounding modes (excluding `MaxCount`).
///
/// The C++ enum has a `MaxCount` sentinel that we omit because the
/// `repr(u8)` type makes the array-bound `usize::from` cast cheap
/// and obvious at the call site. This constant exists so callers
/// iterating over all modes still have an upper bound.
constexpr static const uintptr_t FpRoundMode_COUNT = 4;

/// Frequency of the monotonic tick counter, in ticks per second.
///
/// Backed by `Instant` whose underlying source is a nanosecond-resolution
/// monotonic clock on every platform std supports, so 1_000_000_000 is the
/// canonical tick frequency.
constexpr static const uint64_t TICKS_PER_SECOND = 1000000000;

/// kCFStringEncodingUTF8 == 0x08000100. Hard-coded to avoid
/// pulling in another framework constant module.
constexpr static const uint32_t K_CF_STRING_ENCODING_UTF8 = 134217984;

/// 24-colour palette used by the console (and any host sink that wants to
/// preserve colour). The numeric values match the original C++
/// `ConsoleColors` enumeration so existing C++ call sites are source-
/// compatible via cbindgen.
enum class ConsoleColor : uint32_t {
  ConsoleColor_Default = 0,
  ConsoleColor_Black = 1,
  ConsoleColor_Green = 2,
  ConsoleColor_Red = 3,
  ConsoleColor_Blue = 4,
  ConsoleColor_Magenta = 5,
  ConsoleColor_Orange = 6,
  ConsoleColor_Gray = 7,
  ConsoleColor_Cyan = 8,
  ConsoleColor_Yellow = 9,
  ConsoleColor_White = 10,
  ConsoleColor_StrongBlack = 11,
  ConsoleColor_StrongRed = 12,
  ConsoleColor_StrongGreen = 13,
  ConsoleColor_StrongBlue = 14,
  ConsoleColor_StrongMagenta = 15,
  ConsoleColor_StrongOrange = 16,
  ConsoleColor_StrongGray = 17,
  ConsoleColor_StrongCyan = 18,
  ConsoleColor_StrongYellow = 19,
  ConsoleColor_StrongWhite = 20,
};

/// Severity / verbosity level for log messages.
///
/// Higher numeric values are *more* verbose (mirrors the original C++
/// `LOGLEVEL_NONE = 0, ..., LOGLEVEL_TRACE = 6`). A record is emitted only
/// when `record_level as u32 <= effective_max_level`.
enum class LogLevel : uint32_t {
  /// Silences all log traffic.
  LogLevel_None = 0,
  LogLevel_Error = 1,
  LogLevel_Warning = 2,
  LogLevel_Info = 3,
  /// PCSX2-internal developer-level logging (no direct mapping in the
  /// `log` crate; use [`write`] with this level explicitly).
  LogLevel_Dev = 4,
  LogLevel_Debug = 5,
  LogLevel_Trace = 6,
  /// One-past-the-end sentinel, matches C++ `LOGLEVEL_COUNT`.
  LogLevel_Count = 7,
};

/// Discriminator describing which platform's windowing primitives the
/// [`WindowInfo`] handles refer to.
///
/// Layout mirrors the C++ `enum class Type` exactly: `Surfaceless = 0`,
/// `Win32 = 1`, etc. The `#[repr(u32)]` is required for the FFI-compatible
/// ordering; the field in [`WindowInfo`] reads it back as a `u32`-sized
/// value so the struct layout matches the C++ aggregate.
enum class WindowType : uint32_t {
  /// No on-screen surface will be created.
  WindowType_Surfaceless = 0,
  /// Win32 (`HWND`) window.
  WindowType_Win32 = 1,
  /// X11 (`Window` on an X11 `Display*`).
  WindowType_X11 = 2,
  /// Wayland (`wl_surface*`).
  WindowType_Wayland = 3,
  /// macOS (`NSView*` / `CAMetalLayer*`).
  WindowType_MacOS = 4,
};

/// Equivalent of C++ `Console` (`ConsoleLogWriter<LOGLEVEL_INFO>`).
struct ConsoleWriter;

/// Equivalent of C++ `DevCon` (`ConsoleLogWriter<LOGLEVEL_DEV>`).
struct DevConWriter;

/// RAII handle to a dynamically-loaded shared library.
///
/// Wraps [`libloading::Library`]. Dropping unloads the library.
struct DynamicLibrary;

/// Mutable error container. The closest Rust equivalent to the C++
/// `class Error` — copy/move semantics, an `is_valid()` flag, mutating
/// `set_*` methods, and prefix/suffix decoration.
///
/// Internally `Error` caches the formatted description string so that
/// [`get_description`](Self::get_description) is allocation-free and so
/// that [`add_prefix`](Self::add_prefix) / [`add_suffix`](Self::add_suffix)
/// can mutate the cached text directly. The cache is rebuilt every
/// time a `set_*` method is called.
struct Error;

/// A non-local goto destination.
///
/// Holds the saved register state from a previous call to
/// [`FastJmp::setjmp`]. Calling [`FastJmp::longjmp`] jumps back to
/// that `setjmp` site, returning `val` (or 1 if `val == 0`, matching
/// the C standard).
///
/// `FastJmp` is a small, copy-cheap type. It is not `Sync`: a
/// `jmp_buf` is fundamentally single-threaded (the saved state
/// refers to a specific thread's stack), and `longjmp` is not safe
/// to call from a different thread than the one that called
/// `setjmp`. It is, however, `Send` only via a `&mut` reference,
/// which is the right shape: the buffer is mutated in place by
/// `setjmp` and read by `longjmp`.
///
/// The `UnsafeCell` wrapper documents that the buffer is mutated
/// through `&self` (longjmp rewrites the stack through the
/// pointer), and that we are responsible for upholding the
/// single-thread, single-`setjmp` invariants manually.
struct FastJmp;

/// MD5 message-digest context.
///
/// Construct with [`MD5Digest::new`], feed bytes with [`MD5Digest::update`],
/// then call [`MD5Digest::finalize`] (consuming `self`) to obtain the 16-byte
/// digest. A context may be reused via [`MD5Digest::reset`].
///
/// State layout (mirrors the original C++ class):
/// - `state`:   4-word running hash (`buf` in the C++ source).
/// - `bits`:    2-word total bit count (`bits[0]` = low, `bits[1]` = high).
/// - `buffer`:  64-byte block staging buffer (`in` in the C++ source).
/// - `buffer_len`: number of valid bytes currently in `buffer`.
struct MD5Digest;

/// In-memory [`SettingsInterface`] implementation.
///
/// All state lives in [`self.sections`](Self::sections). There is no
/// persistent backing; [`save`](SettingsInterface::save) is a no-op
/// per the task brief. A `Default` instance has zero sections.
struct MemorySettingsInterface;

template<typename T = void>
struct Option;

/// A counting semaphore built on `std::sync::Mutex` + `Condvar`.
///
/// `Mutex` (in this module) is just a re-export of [`std::sync::Mutex`].
/// The semaphore is fair to the extent that `Condvar::wait` is FIFO;
/// wake ordering follows the OS scheduler.
///
/// The implementation is intentionally simple and portable; for
/// workloads that need the fast userspace path of POSIX semaphores
/// the C++ code's `UserspaceSemaphore` should be ported in a
/// follow-up phase.
struct Semaphore;

struct String;

/// Streaming WAV (RIFF/WAVE) file writer for PCM audio capture.
///
/// Mirrors the C++ `Common::WAVWriter`:
///  - [`WavWriter::create`] opens the file and writes the header
///    with a placeholder `data_size` of zero.
///  - [`WavWriter::write_samples`] appends interleaved i16 samples
///    and accumulates the byte count.
///  - [`WavWriter::finalize`] consumes the writer, seeks back to the
///    start, rewrites the header with the real byte count, and
///    closes the file.
///
/// The writer holds the file open for the duration of its lifetime;
/// if it is dropped without `finalize` the file is closed but the
/// header is left with the placeholder size, producing a truncated
/// WAV. Callers that care about header correctness must call
/// `finalize` explicitly (the FFI `destroy` shim does so for them).
struct WavWriter;

/// Opaque assertion identifier returned by `IOPMAssertionCreateWithName`.
using IOPMAssertionID = uint32_t;

using JmpBuf = uint8_t[200];

/// Opaque handle to a `LruCache<String, u64>`.
///
/// Returned by [`pcsx2_lru_cache_u64_create`] and consumed by
/// [`pcsx2_lru_cache_u64_destroy`]. The C++ side treats this as an
/// opaque pointer; its layout is `#[repr(C)]` but its fields are
/// intentionally inaccessible from C++.
struct LruCacheStringU64 {
  uint8_t _private[0];
};

/// Manually-laid-out function pointer table for memory access.
///
/// We can't pass a `&dyn MemoryInterface` across the C ABI because a Rust
/// trait-object vtable has a Rust-specific layout (drop glue, alignment
/// padding, ...). Instead we declare an explicit `#[repr(C)]` struct of
/// `extern "C"` fn pointers and have Rust code fill it in from a real
/// implementor. The C++ side then sees a plain C struct of function
/// pointers — exactly the layout it would have produced for the C++
/// abstract class's vtable.
struct MemoryVTable {
  uint8_t (*read8)(void *ctx, uint32_t addr);
  uint16_t (*read16)(void *ctx, uint32_t addr);
  uint32_t (*read32)(void *ctx, uint32_t addr);
  uint64_t (*read64)(void *ctx, uint32_t addr);
  void (*write8)(void *ctx, uint32_t addr, uint8_t val);
  void (*write16)(void *ctx, uint32_t addr, uint16_t val);
  void (*write32)(void *ctx, uint32_t addr, uint32_t val);
  void (*write64)(void *ctx, uint32_t addr, uint64_t val);
  void (*read_bytes)(void *ctx, uint32_t addr, uint8_t *dst, uint32_t len);
  void (*write_bytes)(void *ctx, uint32_t addr, const uint8_t *src, uint32_t len);
  bool (*is_mapped)(void *ctx, uint32_t addr);
};

/// Opaque handle handed to C++: `*const MemoryHandle`.
///
/// `ctx` is an opaque cookie the C++ side never dereferences — it's only
/// forwarded back into the vtable entry points, where Rust reinterprets it
/// as the boxed implementor it originally wrapped.
struct MemoryHandle {
  const MemoryVTable *vtable;
  void *ctx;
};

/// A single resolved frame in a captured stack trace.
///
/// Mirrors a subset of the C++ `CallstackEntry` struct: we capture the
/// address, the demangled symbol name (if available), and optionally
/// file + line number.
struct StackFrame {
  /// Absolute instruction pointer for this frame.
  uint64_t address;
  /// Best-effort demangled symbol name. Empty if not resolvable.
  String symbol;
  /// Source file path, if known.
  Option<String> file;
  /// 1-based line number, if known.
  Option<uint32_t> line;
};

/// C-compatible opaque mirror of the C++ `Threading::ThreadHandle`.
///
/// The C++ class layout is platform-dependent:
///   - Windows:  `void* m_native_handle` (8 bytes on 64-bit)
///   - macOS:    `void* m_native_handle` (8 bytes)
///   - Linux:    `void* m_native_handle` + `unsigned int m_native_id`
///               (8 + 4 = 12 bytes, with 4 bytes of tail padding to a
///               16-byte aggregate on x86_64 System V)
///
/// We pack the fields into a single `[usize; 3]` blob so the type
/// has a stable, well-defined size on every platform. The blob is
/// 24 bytes on 64-bit targets — generous enough to cover the C++
/// layout including the Linux tail padding. Reading/writing past
/// the meaningful prefix bytes is harmless because the C++ side
/// never observes those bytes.
///
/// Using an opaque `[usize; 3]` array also lets us pass the handle
/// to C++ as a single pointer-sized argument (the C++ code can read
/// the array members directly via `reinterpret_cast<OpaqueThreadHandle*>`).
struct OpaqueThreadHandle {
  /// `m_native_handle` on every platform.
  uintptr_t native_handle;
  /// `m_native_id` on Linux, unused elsewhere. Stored as a full
  /// `usize` so the struct alignment is stable.
  uintptr_t native_id;
  /// Reserved pad word. Lets the struct cover the C++ tail
  /// padding on Linux without tripping the alignment requirements
  /// of the consumers.
  uintptr_t _reserved;
};

/// Contains the information required to create a graphics context in a window.
///
/// `#[repr(C)]` so the field order, sizes, and alignments match the C++
/// struct exactly. All three opaque handles are stored as `*mut c_void`
/// to remain type-agnostic — the actual interpretation depends on
/// [`WindowInfo::ty`] (e.g. on X11, [`WindowInfo::display_connection`] is
/// an `X11::Display*` and [`WindowInfo::window_handle`] is an X11 `Window`
/// cast to `uintptr_t`).
struct WindowInfo {
  /// The type of the surface. `Surfaceless` indicates it will not be
  /// displayed on screen at all.
  WindowType ty;
  /// Connection to the display server. On most platforms except
  /// X11/Wayland, this is implicit and `null`.
  void *display_connection;
  /// Abstract handle to the window. The interpretation depends on
  /// [`WindowInfo::ty`].
  void *window_handle;
  /// For platforms where a separate surface/layer handle is needed
  /// (e.g. macOS's `CAMetalLayer`), it is stored here.
  void *surface_handle;
  /// Width of the surface in pixels.
  uint32_t surface_width;
  /// Height of the surface in pixels.
  uint32_t surface_height;
  /// DPI scale for the surface.
  float surface_scale;
  /// Refresh rate of the surface, if available.
  float surface_refresh_rate;
};

struct time_value_t {
  int32_t seconds;
  int32_t microseconds;
};

struct thread_basic_info_data_t {
  time_value_t user_time;
  time_value_t system_time;
  int32_t cpu_usage;
  int32_t policy;
  int32_t run_state;
  int32_t flags;
  int32_t suspend_count;
  int32_t sleep_time;
};

using thread_info_t = thread_basic_info_data_t*;

using mach_msg_type_number_t = int;

using LOGICAL_PROCESSOR_RELATIONSHIP = uint32_t;





constexpr static const LOGICAL_PROCESSOR_RELATIONSHIP RelationCache = 2;

/// Global writer corresponding to `extern ConsoleLogWriter<LOGLEVEL_INFO> Console`.
constexpr static const ConsoleWriter Console = ConsoleWriter;

/// Global writer corresponding to `extern ConsoleLogWriter<LOGLEVEL_DEV> DevCon`.
constexpr static const DevConWriter DevCon = DevConWriter;

extern "C" {

extern const uint8_t pcsx2_IS_DEV_BUILD;

extern const uint8_t pcsx2_IS_DEBUG_BUILD;

extern const uint8_t pcsx2_ARCH_X86;

extern const uint8_t pcsx2_ARCH_ARM64;

extern const uint32_t pcsx2_PAGE_SIZE;

extern const uint32_t pcsx2_PAGE_MASK;

extern const uint32_t pcsx2_PAGE_SHIFT;

extern const uint32_t pcsx2_PAGE_SIZE_X86;

extern const uint32_t pcsx2_PAGE_SIZE_ARM64;

extern const uint32_t pcsx2_CACHE_LINE_SIZE;

extern const uint32_t pcsx2_CACHE_LINE_SIZE_X86;

extern const uint32_t pcsx2_CACHE_LINE_SIZE_ARM64;

extern const uint32_t pcsx2_PAGE_ALIGN_SIZE;

extern const intptr_t pcsx2_1KB;

extern const intptr_t pcsx2_4KB;

extern const intptr_t pcsx2_16KB;

extern const intptr_t pcsx2_32KB;

extern const intptr_t pcsx2_64KB;

extern const intptr_t pcsx2_128KB;

extern const intptr_t pcsx2_256KB;

extern const int64_t pcsx2_1MB;

extern const int64_t pcsx2_8MB;

extern const int64_t pcsx2_16MB;

extern const int64_t pcsx2_32MB;

extern const int64_t pcsx2_64MB;

extern const int64_t pcsx2_256MB;

extern const int64_t pcsx2_1GB;

extern const int64_t pcsx2_4GB;

/// `ProgressState::Normal` as a `u32` constant (= 0).
extern const uint32_t pcsx2_progress_callback_state_normal;

/// `ProgressState::Indeterminate` as a `u32` constant (= 1).
extern const uint32_t pcsx2_progress_callback_state_indeterminate;

/// `ProgressState::Paused` as a `u32` constant (= 2).
extern const uint32_t pcsx2_progress_callback_state_paused;

/// `ProgressState::Error` as a `u32` constant (= 3).
extern const uint32_t pcsx2_progress_callback_state_error;

extern void CFRelease(const void *cf);

extern const void *CFStringCreateWithCString(const void *alloc, const char *c_str, uint32_t encoding);

extern int32_t IOPMAssertionCreateWithName(const void *assertion_type, int32_t level, const void *name, IOPMAssertionID *assertion_id);

extern int32_t IOPMAssertionRelease(IOPMAssertionID assertion_id);

extern char *libc_strerror(int errnum);

extern void longjmp(JmpBuf *env, int val);

pcsx2_ uint32_t pcsx2_align_down_pow2_u32(uint32_t value, uint32_t alignment) ;

pcsx2_ uint64_t pcsx2_align_down_pow2_u64(uint64_t value, uint64_t alignment) ;

pcsx2_ uintptr_t pcsx2_align_down_pow2_usize(uintptr_t value, uintptr_t alignment) ;

pcsx2_ uint32_t pcsx2_align_down_u32(uint32_t value, uint32_t alignment) ;

pcsx2_ uint64_t pcsx2_align_down_u64(uint64_t value, uint64_t alignment) ;

pcsx2_ uintptr_t pcsx2_align_down_usize(uintptr_t value, uintptr_t alignment) ;

pcsx2_ uint32_t pcsx2_align_up_pow2_u32(uint32_t value, uint32_t alignment) ;

pcsx2_ uint64_t pcsx2_align_up_pow2_u64(uint64_t value, uint64_t alignment) ;

pcsx2_ uintptr_t pcsx2_align_up_pow2_usize(uintptr_t value, uintptr_t alignment) ;

pcsx2_ uint32_t pcsx2_align_up_u32(uint32_t value, uint32_t alignment) ;

pcsx2_ uint64_t pcsx2_align_up_u64(uint64_t value, uint64_t alignment) ;

pcsx2_ uintptr_t pcsx2_align_up_usize(uintptr_t value, uintptr_t alignment) ;

/// FFI wrapper for [`aligned_free`]. No-op on null.
pcsx2_ void pcsx2_aligned_free(void *ptr) ;

/// FFI wrapper for [`aligned_malloc`].
///
/// Returned pointer is null on failure. Must be released with
/// [`pcsx2_aligned_free`] (or a matching `_aligned_free` from MSVCRT
/// on Windows).
pcsx2_ void *pcsx2_aligned_malloc(uintptr_t size, uintptr_t alignment) ;

/// FFI wrapper for [`aligned_realloc`].
///
/// `old_size` must be the size of the existing allocation so the
/// implementation can copy the live bytes over before freeing the old
/// buffer.
pcsx2_ void *pcsx2_aligned_realloc(void *ptr, uintptr_t size, uintptr_t old_size, uintptr_t alignment) ;

/// Free a buffer previously allocated by `pcsx2_read_binary_file`.
///
/// `cap` is the original allocation capacity from the matching
/// `pcsx2_read_binary_file` call. We reconstruct the original `Vec`
/// and let it run its destructor; this is the safe path because the
/// global deallocator uses the `Layout` recorded by the allocator,
/// not the length we hand back.
pcsx2_ void pcsx2_buffer_free(uint8_t *ptr, uintptr_t len, uintptr_t cap) ;

/// FFI export: byte-swap a `__uint128_t` / `unsigned __int128`.
pcsx2_ u128 pcsx2_byteswap128(u128 val) ;

/// FFI export: byte-swap a `__int128` / `__int128_t`.
pcsx2_ i128 pcsx2_byteswap128_signed(i128 val) ;

/// FFI export: byte-swap a `uint16_t`.
pcsx2_ uint16_t pcsx2_byteswap16(uint16_t val) ;

/// FFI export: byte-swap an `int16_t`.
pcsx2_ int16_t pcsx2_byteswap16_signed(int16_t val) ;

/// FFI export: byte-swap a `uint32_t`.
pcsx2_ uint32_t pcsx2_byteswap32(uint32_t val) ;

/// FFI export: byte-swap an `int32_t`.
pcsx2_ int32_t pcsx2_byteswap32_signed(int32_t val) ;

/// FFI export: byte-swap a `uint64_t`.
pcsx2_ uint64_t pcsx2_byteswap64(uint64_t val) ;

/// FFI export: byte-swap an `int64_t`.
pcsx2_ int64_t pcsx2_byteswap64_signed(int64_t val) ;

/// Create an `NSWindow` with the given title, width and height. The
/// returned pointer is an opaque, owned handle that must be released
/// with `pcsx2_cocoa_destroy_window`. Returns null on non-macOS
/// platforms or on failure.
pcsx2_ void *pcsx2_cocoa_create_window(const char *title, uint32_t width, uint32_t height) ;

/// Release a window handle previously returned by
/// `pcsx2_cocoa_create_window`. Safe to call with a null pointer.
pcsx2_ void pcsx2_cocoa_destroy_window(void *window) ;

/// Run the Cocoa event loop on the calling thread until
/// `pcsx2_cocoa_stop_loop` is called. No-op on non-macOS platforms.
pcsx2_ void pcsx2_cocoa_run_loop() ;

/// Post the sentinel event that terminates a `pcsx2_cocoa_run_loop`
/// call. No-op on non-macOS platforms.
pcsx2_ void pcsx2_cocoa_stop_loop() ;

/// FFI: copy 16 bytes from `src` to `dest`.
///
/// `dest` and `src` must each point to at least 16 bytes. They may
/// alias; the operation is a `memcpy` and is well-defined for
/// overlapping ranges on stable Rust.
pcsx2_ void pcsx2_copy_qwc(uint8_t *dest, const uint8_t *src) ;

pcsx2_ uint32_t pcsx2_count_leading_sign_bits_s32(int32_t n) ;

/// `pcsx2_crash_handler_install` — install the global handler.
/// Mirrors `bool CrashHandler::Install()`.
pcsx2_ bool pcsx2_crash_handler_install() ;

/// `pcsx2_crash_handler_set_write_directory` — point the handler
/// at a directory. The string is copied into a `PathBuf` so the
/// caller can free the buffer immediately after the call returns.
pcsx2_ void pcsx2_crash_handler_set_write_directory(const char *dir) ;

/// `pcsx2_crash_handler_write_dump` — manually trigger a dump.
/// Mirrors `void CrashHandler::WriteDumpForCaller()`.
pcsx2_ void pcsx2_crash_handler_write_dump() ;

pcsx2_ bool pcsx2_create_directory(const char *path, bool recursive) ;

pcsx2_ bool pcsx2_delete_file(const char *path) ;

pcsx2_ bool pcsx2_directory_exists(const char *path) ;

/// Destroy a library handle (close + free).
///
/// # Safety
///
/// `lib` must be from `pcsx2_dynlib_load` or null (no-op).
pcsx2_ void pcsx2_dynlib_destroy(DynamicLibrary *lib) ;

/// Resolve a symbol from a loaded library.
/// Returns symbol address or null. Pointer borrowed — invalidated
/// when library is destroyed.
///
/// # Safety
///
/// `lib` must be valid (from `pcsx2_dynlib_load`). `name` must be a
/// valid C string. Caller casts the result to the correct type.
pcsx2_ void *pcsx2_dynlib_get_symbol(DynamicLibrary *lib, const char *name) ;

/// Load a shared library. Returns opaque handle or null.
/// Handle must be released with `pcsx2_dynlib_destroy`.
pcsx2_ DynamicLibrary *pcsx2_dynlib_load(const char *name) ;

/// FFI: bitwise AND.
pcsx2_ uint32_t pcsx2_enum_and_u32(uint32_t a, uint32_t b) ;

/// FFI: identity cast passthrough.
///
/// Useful from C++ when a generic `<T>` template would otherwise have to
/// dispatch on the type at the call site — `enum_cast` always widens to
/// `u32` here so the C++ side never has to know the Rust underlying type.
pcsx2_ uint32_t pcsx2_enum_cast_u32(uint32_t value) ;

/// FFI: bitwise NOT (one's complement).
pcsx2_ uint32_t pcsx2_enum_not_u32(uint32_t a) ;

/// FFI: bitwise OR.
pcsx2_ uint32_t pcsx2_enum_or_u32(uint32_t a, uint32_t b) ;

/// FFI: test if any bit of `b` is set in `a`.
///
/// Equivalent to C++ `!((a & b) == 0)`; the `bool` return type matches
/// the C `bool` ABI used by PCSX2 (single byte on every supported
/// platform).
pcsx2_ bool pcsx2_enum_test_u32(uint32_t a, uint32_t b) ;

/// FFI: bitwise XOR.
pcsx2_ uint32_t pcsx2_enum_xor_u32(uint32_t a, uint32_t b) ;

/// Mirror of C++ `Error::Clear`. A null pointer is a no-op.
pcsx2_ void pcsx2_error_clear(Error *err) ;

/// Allocate a fresh, empty `Error` on the heap and return an opaque
/// owning pointer. The C++ side stores this as `Error*`.
///
/// The caller must call [`pcsx2_error_destroy`] exactly once on the
/// returned pointer; double-free or use-after-free are the caller's
/// responsibility.
pcsx2_ Error *pcsx2_error_create() ;

/// Free an `Error` previously allocated by [`pcsx2_error_create`].
///
/// Passing a null pointer is a no-op (matches `free`). After this
/// returns, `err` must not be used again.
pcsx2_ void pcsx2_error_destroy(Error *err) ;

/// Copy the description into the caller's `out` buffer.
///
/// `out_len` is the size of `out` in bytes. The returned `u32` is the
/// number of bytes that *would* have been written (excluding the
/// trailing NUL); if it is greater than `out_len`, the result was
/// truncated and the caller should call again with a larger buffer.
///
/// A null `err` always writes an empty NUL-terminated string and
/// returns 0. A null `out` returns 0 without writing.
pcsx2_ unsigned int pcsx2_error_get_message(Error *err, char *out, unsigned int out_len) ;

/// Mirror of C++ `Error::IsValid`. A null pointer returns `false`.
pcsx2_ bool pcsx2_error_is_valid(Error *err) ;

/// Mirror of C++ `Error::SetErrno`. Silently no-ops on a null pointer.
pcsx2_ void pcsx2_error_set_errno(Error *err, int code) ;

/// Mirror of C++ `Error::SetHResult(Error*, std::string_view, long)`
/// (static with description). `description` must be a NUL-terminated C
/// string or null. A null `description` is treated as an empty prefix.
pcsx2_ void pcsx2_error_set_hresult(Error *err, const char *description, int hr) ;

/// Mirror of C++ `Error::SetHResult(long)` (instance method). A null
/// pointer is a no-op. `code` is a COM `HRESULT` (sign-extended 32-bit
/// value).
pcsx2_ void pcsx2_error_set_hresult_inst(Error *err, int code) ;

/// Mirror of C++ `Error::SetHResult(Error*, string_view, long)`.
/// `prefix` must be a NUL-terminated C string or null. A null `prefix`
/// is treated as an empty prefix.
pcsx2_ void pcsx2_error_set_hresult_prefix(Error *err, const char *prefix, int code) ;

/// Mirror of C++ `Error::SetString`. `msg` must be a NUL-terminated
/// C string or null. A null `msg` produces an empty user error.
pcsx2_ void pcsx2_error_set_string(Error *err, const char *msg) ;

/// Mirror of C++ `Error::SetWin32(Error*, unsigned long)` (static).
/// A null pointer is a no-op. `code` is the Win32 `DWORD` error code.
pcsx2_ void pcsx2_error_set_win32_code(Error *err, unsigned int code) ;

/// Mirror of C++ `Error::SetWin32(unsigned long)` (instance method).
/// A null pointer is a no-op. `code` is the Win32 `DWORD` error code
/// (e.g. returned by `GetLastError()`).
pcsx2_ void pcsx2_error_set_win32_inst(Error *err, unsigned int code) ;

/// Mirror of C++ `Error::SetWin32(Error*, string_view, unsigned long)`.
/// `prefix` must be a NUL-terminated C string or null. A null `prefix`
/// is treated as an empty prefix.
pcsx2_ void pcsx2_error_set_win32_prefix(Error *err, const char *prefix, unsigned int code) ;

/// Mirror of C++ `Error::SetWin32(Error*, std::string_view, unsigned long)`
/// (static with prefix). `description` must be a NUL-terminated C string
/// or null. A null `description` is treated as an empty prefix.
pcsx2_ void pcsx2_error_set_win32_static(Error *err, const char *description, unsigned int code) ;

/// FFI: free a `FastJmp` previously returned by
/// [`pcsx2_fastjmp_new`].
///
/// Passing a null pointer is a no-op (matches `Box::drop`'s
/// behaviour on the Rust side; on the C side it's the same as
/// `free(NULL)`).
///
/// # Safety
///
/// `handle` must either be null or a pointer previously returned
/// by `pcsx2_fastjmp_new`, and must not have been freed already.
pcsx2_ void pcsx2_fastjmp_drop(FastJmp *handle) ;

/// FFI: jump back to the most recent `pcsx2_fastjmp_set` on the
/// same `handle`.
///
/// This function never returns.
///
/// # Safety
///
/// `handle` must be a valid pointer to a `FastJmp` that has
/// already had `pcsx2_fastjmp_set` (or `FastJmp::setjmp`) called
/// on it. Calling this from a different thread than the matching
/// `setjmp` is undefined behaviour.
pcsx2_ void pcsx2_fastjmp_longjmp(FastJmp *handle, int32_t val) ;

/// FFI: allocate a new `FastJmp` and return an opaque handle.
///
/// The caller is responsible for eventually calling
/// [`pcsx2_fastjmp_drop`] on the returned pointer. The returned
/// pointer is non-null on success.
pcsx2_ FastJmp *pcsx2_fastjmp_new() ;

/// FFI: save the current execution context into the `FastJmp`
/// identified by `handle`.
///
/// Returns 0 on the first call. On a subsequent return via
/// [`pcsx2_fastjmp_longjmp`], returns the non-zero value passed to
/// that `longjmp`.
///
/// # Safety
///
/// `handle` must be a valid pointer to a `FastJmp` previously
/// returned by [`pcsx2_fastjmp_new`], and the call must be
/// associated with a frame that is still live on the current
/// thread's stack (i.e. you must still be inside the function
/// that wanted to longjmp *back* to this site).
pcsx2_ int32_t pcsx2_fastjmp_set(FastJmp *handle) ;

pcsx2_ bool pcsx2_file_exists(const char *path) ;

/// Returns `true` if `path` is a directory containing no entries
/// (or does not exist). Mirrors C++ `FileSystem::DirectoryIsEmpty`:
/// both the Linux `opendir() == nullptr` branch and the Windows
/// `FindFirstFileW == INVALID_HANDLE_VALUE` branch are folded into
/// the empty case, so a missing path returns `true` rather than
/// `false`.
pcsx2_ bool pcsx2_filesystem_directory_is_empty(const char *path) ;

/// Mirror of C++ `FileSystem::ReadFileWithPartialProgress`.
///
/// Like [`pcsx2_filesystem_read_file_with_progress`] but with explicit
/// `min_step` / `max_step` progress range bounds. `progress` and
/// `err` are opaque from Rust; see module-level TODO.
pcsx2_ uint64_t pcsx2_filesystem_read_file_with_partial_progress(void *fp, void *buffer, uint64_t size, void *_progress, int _min_step, int _max_step, void *_err, uint64_t _base_offset) ;

/// Mirror of C++ `FileSystem::ReadFileWithProgress`.
///
/// Reads up to `size` bytes from `fp` into `buffer` and returns the
/// number of bytes actually read. `progress` and `err` are opaque
/// from Rust; see module-level TODO.
pcsx2_ uint64_t pcsx2_filesystem_read_file_with_progress(void *fp, void *buffer, uint64_t size, void *_progress, void *_err, uint64_t _base_offset) ;

/// FFI: alignment-safe `u16` read from a raw byte buffer.
///
/// # Safety
///
/// `buffer` must point to at least `offset + 2` readable bytes.
pcsx2_ uint16_t pcsx2_get_buffer_u16(const uint8_t *buffer, uint32_t offset) ;

/// FFI: alignment-safe `u32` read from a raw byte buffer.
///
/// # Safety
///
/// `buffer` must point to at least `offset + 4` readable bytes.
pcsx2_ uint32_t pcsx2_get_buffer_u32(const uint8_t *buffer, uint32_t offset) ;

/// FFI: alignment-safe `u64` read from a raw byte buffer.
///
/// # Safety
///
/// `buffer` must point to at least `offset + 8` readable bytes.
pcsx2_ uint64_t pcsx2_get_buffer_u64(const uint8_t *buffer, uint32_t offset) ;

/// FFI: alignment-safe `u8` read from a raw byte buffer.
///
/// Matches the C++ `GetBufferU8(const u8*, u32)` `memcpy` semantics.
///
/// # Safety
///
/// `buffer` must point to at least `offset + 1` readable bytes.
pcsx2_ uint8_t pcsx2_get_buffer_u8(const uint8_t *buffer, uint32_t offset) ;

/// Write the running executable's path into `out`.
///
/// Returns the number of bytes written (NUL excluded), or 0 on
/// failure / unsupported platform. Always NUL-terminates when
/// `out_len > 0`.
pcsx2_ uint32_t pcsx2_get_program_path(char *out, uint32_t out_len) ;

/// Write the current working directory into `out`.
pcsx2_ uint32_t pcsx2_get_working_directory(char *out, uint32_t out_len) ;

/// FFI export: fold a null-terminated C string into the seed.
///
/// The string's bytes (excluding the trailing NUL terminator) are hashed.
/// A null pointer is treated as a no-op and returns `seed` unchanged.
pcsx2_ uint64_t pcsx2_hash_combine_str(uint64_t seed, const char *value) ;

/// FFI export: fold a `uint32_t` into the seed.
pcsx2_ uint64_t pcsx2_hash_combine_u32(uint64_t seed, uint32_t value) ;

/// FFI export: fold a `uint64_t` into the seed.
pcsx2_ uint64_t pcsx2_hash_combine_u64(uint64_t seed, uint64_t value) ;

/// FFI: available physical memory, in bytes.
pcsx2_ uint64_t pcsx2_host_available_memory() ;

pcsx2_ uint64_t pcsx2_host_available_memory() ;

pcsx2_ uint64_t pcsx2_host_available_memory() ;

/// FFI: L1 data cache line size, in bytes.
pcsx2_ uint32_t pcsx2_host_cache_line_size() ;

pcsx2_ uint32_t pcsx2_host_cache_line_size() ;

pcsx2_ uint32_t pcsx2_host_cache_line_size() ;

/// FFI: current value of the monotonic tick counter.
pcsx2_ uint64_t pcsx2_host_cpu_ticks() ;

pcsx2_ uint64_t pcsx2_host_cpu_ticks() ;

pcsx2_ uint64_t pcsx2_host_cpu_ticks() ;

/// FFI: change protection on a region.
///
/// `prot` is a bitmask: bit 0 = read, bit 1 = write, bit 2 = exec.
pcsx2_ bool pcsx2_host_mem_protect(uint8_t *base, uintptr_t size, uint32_t prot) ;

pcsx2_ bool pcsx2_host_mem_protect(uint8_t *_base, uintptr_t _size, uint32_t _prot) ;

/// FFI export: apply Win32 memory protection to a region.
///
/// `prot` is a bitfield compatible with the C++ `PageProtectionMode`:
/// - bit 0 (`0x1`): read
/// - bit 1 (`0x2`): write
/// - bit 2 (`0x4`): execute
///
/// Returns `true` on success.
pcsx2_ bool pcsx2_host_mem_protect(uint8_t *base, uintptr_t size, uint32_t prot) ;

/// FFI: write the OS version string into a caller-supplied buffer.
///
/// Returns the number of bytes that *would* have been written
/// (excluding the NUL). A return value `>= out_len` indicates
/// truncation.
pcsx2_ uint32_t pcsx2_host_os_version_string(char *out, uint32_t out_len) ;

pcsx2_ uint32_t pcsx2_host_os_version_string(char *out, uint32_t out_len) ;

pcsx2_ uint32_t pcsx2_host_os_version_string(uint8_t *out, uint32_t out_len) ;

/// FFI: runtime page size, in bytes.
pcsx2_ uint32_t pcsx2_host_page_size() ;

pcsx2_ uint32_t pcsx2_host_page_size() ;

pcsx2_ uint32_t pcsx2_host_page_size() ;

/// FFI: total physical memory, in bytes.
pcsx2_ uint64_t pcsx2_host_physical_memory() ;

pcsx2_ uint64_t pcsx2_host_physical_memory() ;

pcsx2_ uint64_t pcsx2_host_physical_memory() ;

/// FFI: tick frequency, in ticks per second.
pcsx2_ uint64_t pcsx2_host_tick_frequency() ;

pcsx2_ uint64_t pcsx2_host_tick_frequency() ;

pcsx2_ uint64_t pcsx2_host_tick_frequency() ;

/// Download a file from `url` to `dest_path` with no progress
/// reporting.
///
/// `url` and `dest_path` must be UTF-8 NUL-terminated C strings.
/// Returns `true` on success, `false` on any failure (bad URL, IO
/// error, non-2xx HTTP status, ...).
///
/// Equivalent of `download_file` exposed across the C ABI. The C++
/// wrapper is expected to be a thin shim that just calls this and
/// propagates the bool back to its caller.
pcsx2_ bool pcsx2_http_download(const char *url, const char *dest_path) ;

/// Download a file from `url` to `dest_path`, invoking `callback`
/// after every chunk with `(bytes_received, total_bytes)`.
///
/// `callback` may be `None` — in which case this behaves identically
/// to [`pcsx2_http_download`]. When non-null, the callback is invoked
/// synchronously from the download thread, so C++ implementations
/// must be cheap and must not block.
///
/// `total_bytes` is the value of the HTTP `Content-Length` response
/// header when present, and `0` for chunked transfers. `bytes_received`
/// is the cumulative count of bytes written to disk.
///
/// Returns `true` on success, `false` on any failure (bad URL, IO
/// error, non-2xx HTTP status, ...).
pcsx2_ bool pcsx2_http_download_with_progress(const char *url, const char *dest_path, void (*callback)(uint64_t, uint64_t)) ;

/// Free a pixel buffer previously returned by any `pcsx2_image_load_*` function.
pcsx2_ void pcsx2_image_free(uint8_t *pixels) ;

/// Load an image from an in-memory buffer. Format auto-detected.
/// Returns (width, height, malloc'd RGBA pixels) via out params.
/// Return value = total bytes (0 = failure).
///
/// Replaces `RGBA8Image::LoadFromBuffer(const char*, const void*, u64)`.
pcsx2_ uint32_t pcsx2_image_load_from_buffer(const uint8_t *buffer, uintptr_t buffer_size, uint32_t *out_width, uint32_t *out_height, uint8_t **out_pixels) ;

/// Load an image from file. Format auto-detected from content.
/// Returns (width, height, malloc'd RGBA pixels) via out params.
/// Return value = total bytes of pixel data (0 = failure).
///
/// Replaces `RGBA8Image::LoadFromFile(const char*)`.
pcsx2_ uint32_t pcsx2_image_load_from_file(const char *path, uint32_t *out_width, uint32_t *out_height, uint8_t **out_pixels) ;

/// Same as `pcsx2_image_load_png` — convenience alias.
pcsx2_ uint32_t pcsx2_image_load_jpeg(const char *path, uint32_t *out_width, uint32_t *out_height, uint8_t **out_pixels) ;

/// Load an image (any format, auto-detected) — named `png` for historical reasons.
/// Actually works for PNG, JPEG, WebP, BMP, etc.
pcsx2_ uint32_t pcsx2_image_load_png(const char *path, uint32_t *out_width, uint32_t *out_height, uint8_t **out_pixels) ;

/// Same as `pcsx2_image_load_png` — convenience alias.
pcsx2_ uint32_t pcsx2_image_load_webp(const char *path, uint32_t *out_width, uint32_t *out_height, uint8_t **out_pixels) ;

/// JPEG save.
pcsx2_ bool pcsx2_image_save_jpeg(const char *path, uint32_t width, uint32_t height, const uint8_t *pixels, uint32_t stride, uint8_t quality) ;

/// PNG save.
pcsx2_ bool pcsx2_image_save_png(const char *path, uint32_t width, uint32_t height, const uint8_t *pixels, uint32_t stride) ;

/// Save an RGBA8 pixel buffer to an in-memory buffer.
/// `format` = "png", "jpg", "jpeg", "webp", "bmp".
/// Returns a malloc'd buffer (caller must free with pcsx2_image_free).
/// Output: `out_size` = byte count of encoded data.
pcsx2_ uint8_t *pcsx2_image_save_to_buffer(uint32_t width, uint32_t height, const uint8_t *pixels, uint32_t stride, const char *format, uint8_t quality, uintptr_t *out_size) ;

/// Save an RGBA8 pixel buffer to file. Format auto-detected from extension.
///
/// Replaces `RGBA8Image::SaveToFile(const char*, u8)`.
pcsx2_ bool pcsx2_image_save_to_file(const char *path, uint32_t width, uint32_t height, const uint8_t *pixels, uint32_t stride, uint8_t quality) ;

/// WebP save (lossless).
pcsx2_ bool pcsx2_image_save_webp(const char *path, uint32_t width, uint32_t height, const uint8_t *pixels, uint32_t stride, uint8_t _lossy) ;

pcsx2_ bool pcsx2_is_aligned_pow2_u32(uint32_t value, uint32_t alignment) ;

pcsx2_ bool pcsx2_is_aligned_pow2_u64(uint64_t value, uint64_t alignment) ;

pcsx2_ bool pcsx2_is_aligned_pow2_usize(uintptr_t value, uintptr_t alignment) ;

pcsx2_ bool pcsx2_is_aligned_u32(uint32_t value, uint32_t alignment) ;

pcsx2_ bool pcsx2_is_aligned_u64(uint64_t value, uint64_t alignment) ;

pcsx2_ bool pcsx2_is_aligned_usize(uintptr_t value, uintptr_t alignment) ;

/// FFI: inhibit/uninhibit the screensaver.
pcsx2_ bool pcsx2_linux_inhibit_screensaver(bool inhibit) ;

/// FFI: play a sound asynchronously. The `path` must be a NUL-terminated UTF-8
/// C string. Returns `true` if a backend was successfully spawned.
pcsx2_ bool pcsx2_linux_play_sound_async(const char *path) ;

/// FFI: warp the mouse cursor.
pcsx2_ void pcsx2_linux_set_mouse_position(int32_t x, int32_t y) ;

/// Query the effective max level.
pcsx2_ LogLevel pcsx2_log_get_level() ;

/// Install a host callback. Pass `None` (null pointer from C) to clear.
///
/// Mirrors C++ `Log::SetHostOutputLevel(LOGLEVEL, HostCallbackType)`.
pcsx2_ void pcsx2_log_set_host_callback(LogLevel level, void (*callback)(LogLevel, ConsoleColor, const char*, uintptr_t)) ;

/// Overwrite the effective max level (highest of all per-sink levels).
pcsx2_ void pcsx2_log_set_level(LogLevel level) ;

/// Write a record from C/C++.
///
/// `msg` is a UTF-8 byte buffer (not necessarily NUL-terminated) of length
/// `len` bytes. Null `msg` is treated as an empty message.
pcsx2_ void pcsx2_log_write(LogLevel level, ConsoleColor color, const char *msg, uintptr_t len) ;

/// Create a new `LruCache<String, u64>` with the given capacity and
/// `manual_evict = false`. Returns a non-null handle on success, or
/// a null pointer on allocation failure.
pcsx2_ LruCacheStringU64 *pcsx2_lru_cache_u64_create(uint32_t capacity) ;

/// Free a cache previously returned by [`pcsx2_lru_cache_u64_create`].
/// Safe to call with a null pointer (no-op).
pcsx2_ void pcsx2_lru_cache_u64_destroy(LruCacheStringU64 *cache) ;

/// Insert `(key, value)` into the cache. Bumps `last_access` on the
/// new entry and evicts the oldest if the cap is exceeded.
///
/// `key` must be a NUL-terminated C string. Invalid UTF-8 is silently
/// dropped (the call is a no-op). Null `cache` or `key` is a no-op.
pcsx2_ void pcsx2_lru_cache_u64_insert(LruCacheStringU64 *cache, const char *key, uint64_t value) ;

/// Look up `key` in the cache. Bumps `last_access` on hit.
///
/// Returns `0` if the key was **not** present, `1` if it was. (The
/// 0/1 boolean is intentional: a `u64` value of 0 is a legitimate
/// cached value, so it cannot double as a "not found" sentinel. If
/// the C++ side needs the value, it should track it itself or extend
/// the API with a dedicated getter.)
pcsx2_ uint64_t pcsx2_lru_cache_u64_lookup(LruCacheStringU64 *cache, const char *key) ;

/// FFI export of [`inhibit_screensaver`].
pcsx2_ bool pcsx2_macos_inhibit_screensaver(bool inhibit) ;

/// FFI export of [`play_sound_async`]. `path` must be a NUL-terminated
/// UTF-8 C string; passing null returns `false`.
pcsx2_ bool pcsx2_macos_play_sound_async(const char *path) ;

/// FFI export of [`set_mouse_position`].
pcsx2_ void pcsx2_macos_set_mouse_position(int32_t x, int32_t y) ;

pcsx2_ void pcsx2_md5_destroy(MD5Digest *ctx) ;

pcsx2_ void pcsx2_md5_final(MD5Digest *ctx, uint8_t *out) ;

pcsx2_ void pcsx2_md5_hash(const uint8_t *data, uint32_t len, uint8_t *out) ;

pcsx2_ MD5Digest *pcsx2_md5_new() ;

pcsx2_ void pcsx2_md5_update(MD5Digest *ctx, const uint8_t *data, uint32_t len) ;

pcsx2_ bool pcsx2_mem_is_mapped(const MemoryHandle *handle, uint32_t addr) ;

pcsx2_ uint16_t pcsx2_mem_read16(const MemoryHandle *handle, uint32_t addr) ;

pcsx2_ uint32_t pcsx2_mem_read32(const MemoryHandle *handle, uint32_t addr) ;

pcsx2_ uint64_t pcsx2_mem_read64(const MemoryHandle *handle, uint32_t addr) ;

/// Read 8 bits. Returns 0 if the handle is null.
pcsx2_ uint8_t pcsx2_mem_read8(const MemoryHandle *handle, uint32_t addr) ;

/// Bulk read. `dst` is a caller-allocated buffer of length `len`.
///
/// # Safety
/// `dst` must point to at least `len` writable bytes.
pcsx2_ void pcsx2_mem_read_bytes(const MemoryHandle *handle, uint32_t addr, uint8_t *dst, uint32_t len) ;

/// Release a handle. After this call, the Rust-side `Box<ErasedMemory>`
/// is dropped and the implementor's destructor runs.
///
/// # Safety
/// `handle` must have been produced by [`MemoryHandle::from_box`] and must
/// not be used afterwards. The `handle` pointer itself is not freed — C++
/// owns the `MemoryHandle` struct and is responsible for deallocating it.
pcsx2_ void pcsx2_mem_release(const MemoryHandle *handle) ;

pcsx2_ void pcsx2_mem_write16(const MemoryHandle *handle, uint32_t addr, uint16_t val) ;

pcsx2_ void pcsx2_mem_write32(const MemoryHandle *handle, uint32_t addr, uint32_t val) ;

pcsx2_ void pcsx2_mem_write64(const MemoryHandle *handle, uint32_t addr, uint64_t val) ;

pcsx2_ void pcsx2_mem_write8(const MemoryHandle *handle, uint32_t addr, uint8_t val) ;

/// Bulk write. `src` is a caller-allocated buffer of length `len`.
///
/// # Safety
/// `src` must point to at least `len` readable bytes.
pcsx2_ void pcsx2_mem_write_bytes(const MemoryHandle *handle, uint32_t addr, const uint8_t *src, uint32_t len) ;

/// FFI wrapper for [`memcpy_wrapped_dest`].
///
/// Mirrors the C++ signature:
/// ```c
/// void pcsx2_memcpy_wrapped_dest(const u128* src,
///                                u128* destBase,
///                                uint* destStart,
///                                uint destSize,
///                                uint len);
/// ```
///
/// # Safety
///
/// - `src` must point to `len` readable `u128` elements.
/// - `dest_base` must point to `dest_size` writable `u128` elements.
/// - `dest_start` must point to a writable `u32`.
/// - All three pointers must be non-null for any non-zero `len`; null
///   pointers are silently ignored.
pcsx2_ void pcsx2_memcpy_wrapped_dest(const u128 *src, u128 *dest_base, uint32_t *dest_start, uint32_t dest_size, uint32_t len) ;

/// FFI wrapper for [`memcpy_wrapped_src`].
///
/// Mirrors the C++ signature:
/// ```c
/// void pcsx2_memcpy_wrapped_src(const u128* srcBase,
///                               uint* srcStart,
///                               uint srcSize,
///                               u128* dest,
///                               uint len);
/// ```
///
/// # Safety
///
/// - `src_base` must point to `src_size` readable `u128` elements.
/// - `src_start` must point to a writable `u32`.
/// - `dest` must point to `len` writable `u128` elements.
/// - All three pointers must be non-null for any non-zero `len`; null
///   pointers are silently ignored.
pcsx2_ void pcsx2_memcpy_wrapped_src(const u128 *src_base, uint32_t *src_start, uint32_t src_size, u128 *dest, uint32_t len) ;

pcsx2_ void pcsx2_memory_settings_clear(MemorySettingsInterface *s) ;

pcsx2_ void pcsx2_memory_settings_clear_section(MemorySettingsInterface *s, const char *section) ;

pcsx2_ bool pcsx2_memory_settings_contains_value(MemorySettingsInterface *s, const char *section, const char *key) ;

/// Allocate a new, empty [`MemorySettingsInterface`]. The caller owns
/// the returned pointer and must release it exactly once with
/// [`pcsx2_memory_settings_destroy`].
pcsx2_ MemorySettingsInterface *pcsx2_memory_settings_create() ;

pcsx2_ void pcsx2_memory_settings_delete_value(MemorySettingsInterface *s, const char *section, const char *key) ;

/// Free a handle previously returned by [`pcsx2_memory_settings_create`].
/// Passing a null pointer is a no-op.
pcsx2_ void pcsx2_memory_settings_destroy(MemorySettingsInterface *s) ;

pcsx2_ bool pcsx2_memory_settings_get_bool(MemorySettingsInterface *s, const char *section, const char *key, bool *out) ;

pcsx2_ bool pcsx2_memory_settings_get_double(MemorySettingsInterface *s, const char *section, const char *key, double *out) ;

pcsx2_ bool pcsx2_memory_settings_get_float(MemorySettingsInterface *s, const char *section, const char *key, float *out) ;

pcsx2_ bool pcsx2_memory_settings_get_int(MemorySettingsInterface *s, const char *section, const char *key, int32_t *out) ;

/// Copy the stored string for `(section, key)` into `buf`, NUL-terminating
/// it. `buf_len` is the capacity of `buf` in bytes (including the
/// trailing NUL slot).
///
/// Returns:
/// * `> 0` — the number of bytes written, **excluding** the trailing
///   NUL. The buffer is NUL-terminated on success.
/// * `-1`  — the key is missing, the buffer is too small, or any input
///   pointer is null / capacity is zero. On failure the buffer is left
///   untouched so the caller can detect truncation by comparing the
///   returned length to its original buffer size.
pcsx2_ int64_t pcsx2_memory_settings_get_string(MemorySettingsInterface *s, const char *section, const char *key, char *buf, uintptr_t buf_len) ;

pcsx2_ bool pcsx2_memory_settings_get_uint(MemorySettingsInterface *s, const char *section, const char *key, uint32_t *out) ;

pcsx2_ bool pcsx2_memory_settings_is_empty(MemorySettingsInterface *s) ;

pcsx2_ void pcsx2_memory_settings_remove_empty_sections(MemorySettingsInterface *s) ;

pcsx2_ void pcsx2_memory_settings_remove_section(MemorySettingsInterface *s, const char *section) ;

pcsx2_ bool pcsx2_memory_settings_save(MemorySettingsInterface *s) ;

pcsx2_ void pcsx2_memory_settings_set_bool(MemorySettingsInterface *s, const char *section, const char *key, bool value) ;

pcsx2_ void pcsx2_memory_settings_set_double(MemorySettingsInterface *s, const char *section, const char *key, double value) ;

pcsx2_ void pcsx2_memory_settings_set_float(MemorySettingsInterface *s, const char *section, const char *key, float value) ;

pcsx2_ void pcsx2_memory_settings_set_int(MemorySettingsInterface *s, const char *section, const char *key, int32_t value) ;

pcsx2_ void pcsx2_memory_settings_set_string(MemorySettingsInterface *s, const char *section, const char *key, const char *value) ;

pcsx2_ void pcsx2_memory_settings_set_uint(MemorySettingsInterface *s, const char *section, const char *key, uint32_t value) ;

/// FFI entry point for C++ `pxOnAssertFail(file, line, func, msg)`.
///
/// All four string parameters are borrowed C strings; they may be
/// `NULL`, in which case we substitute the placeholder `"<null>"` so
/// the resulting log line / panic message remains well-formed.
///
/// `#[no_mangle] pub extern "C"` makes this symbol visible to the C++
/// core with C linkage; cbindgen picks it up for header generation.
///
/// This symbol name intentionally matches the C++ `pxOnAssertFail`
/// ABI symbol (renamed to the snake_case Rust convention), so the
/// existing C++ call sites work without modification: when
/// `pxAssertRel` / `pxFailRel` in C++ invokes the symbol, the Rust
/// implementation handles it the same way (log + panic / abort).
///
/// # Panics
///
/// Always panics. This function does not return.
pcsx2_ void pcsx2_on_assert_fail(const char *file, int line, const char *func, const char *msg) ;

pcsx2_ uint32_t pcsx2_page_align_u32(uint32_t size) ;

pcsx2_ uint64_t pcsx2_page_align_u64(uint64_t size) ;

pcsx2_ uintptr_t pcsx2_page_align_usize(uintptr_t size) ;

/// FFI export: append `dir` to `base`, returning a newly-allocated
/// NUL-terminated C string.
///
/// Mirrors C++ `Path::AppendDirectory(string_view, string_view)`
/// returning a `std::string`. The caller frees the returned pointer
/// with `libc::free`. Returns a null pointer if either argument is
/// null or if the allocation fails.
pcsx2_ char *pcsx2_path_append_directory(const char *base, const char *dir) ;

/// FFI export: replace the file portion of `path` with `new_file_name`,
/// writing the result back into the caller-owned `path` buffer.
///
/// Mirrors C++ `Path::ChangeFileName(string*, string_view)`. The
/// caller is responsible for sizing `path` large enough to hold the
/// result plus a NUL terminator. Returns `false` (and leaves `path`
/// untouched) on null pointers or allocation failure.
pcsx2_ bool pcsx2_path_change_file_name(char *path, const char *new_file_name) ;

/// FFI export: combine two path components. Returns bytes written, or
/// `0` if the buffer is too small.
pcsx2_ uint32_t pcsx2_path_combine(char *out, uint32_t out_len, const char *base, const char *next) ;

/// FFI export: directory component of `path`.
pcsx2_ uint32_t pcsx2_path_get_directory(char *out, uint32_t out_len, const char *path) ;

/// FFI export: extension of `path`, including the leading `.`.
pcsx2_ uint32_t pcsx2_path_get_extension(char *out, uint32_t out_len, const char *path) ;

/// FFI export: file name component of `path`.
pcsx2_ uint32_t pcsx2_path_get_file_name(char *out, uint32_t out_len, const char *path) ;

/// FFI export: file title (file_name minus extension) of `path`.
pcsx2_ uint32_t pcsx2_path_get_file_title(char *out, uint32_t out_len, const char *path) ;

/// FFI export: returns 1 if `path` is absolute, 0 otherwise. (This
/// one is a scalar, no buffer required, so it breaks the pattern —
/// kept because the C++ side treats it as a `bool` query and the
/// caller doesn't need to allocate a throwaway buffer.)
pcsx2_ uint32_t pcsx2_path_is_absolute(const char *path) ;

/// FFI export: join `count` NUL-terminated path components into one
/// path using the platform's native separator.
///
/// Mirrors C++ `Path::JoinNativePath(vector<string_view> const&)`:
/// empty components are skipped, and `count == 0` (or all-empty
/// components) yields a single empty string. The caller frees the
/// returned pointer with `libc::free`.
pcsx2_ char *pcsx2_path_join_native_path(const char *const *parts, uintptr_t count) ;

/// FFI export: convert forward slashes to the platform's native
/// separator.
pcsx2_ uint32_t pcsx2_path_to_native_path(char *out, uint32_t out_len, const char *path) ;

pcsx2_ void pcsx2_perf_group_register(int32_t group, const void *addr, uint64_t size, const char *name) ;

pcsx2_ void pcsx2_perf_group_register_key(int32_t group, const void *addr, uint64_t size, uint64_t key, const char *name) ;

pcsx2_ void pcsx2_perf_group_register_pc(int32_t group, const void *addr, uint64_t size, uint32_t pc) ;

pcsx2_ bool pcsx2_perf_init() ;

pcsx2_ void pcsx2_perf_shutdown() ;

/// Free a [`NullProgressCallback`] previously returned by
/// [`pcsx2_progress_callback_null_create`].
///
/// `cb` must either be null (no-op) or a pointer returned by the
/// matching create function. Passing any other pointer, or
/// double-freeing, is undefined behaviour — exactly the contract
/// of `Box::from_raw`.
///
/// Safe to call from any thread; the underlying type is `Send`.
pcsx2_ void pcsx2_progress_callback_destroy(void *cb) ;

/// Heap-allocate a [`NullProgressCallback`] and return an opaque
/// handle for C++ to hold.
///
/// The returned pointer is a `*mut NullProgressCallback` widened to
/// `*mut c_void` for C-ABI compatibility. C++ should treat it as
/// `void*` and pass it back to
/// [`pcsx2_progress_callback_destroy`] when done. The pointer is
/// non-null on success; allocation failure is propagated as a
/// null pointer (the C++ caller checks for null, matching the
/// `std::make_unique` failure mode).
///
/// Ownership transfers: C++ does not own the allocation until it
/// receives the pointer, and from that point onward it is the
/// sole owner until it calls
/// [`pcsx2_progress_callback_destroy`]. Sharing the pointer across
/// threads is safe because [`NullProgressCallback`] is `Sync`
/// (every method takes `&self` / `&mut self` and the type holds
/// no interior state).
pcsx2_ void *pcsx2_progress_callback_null_create() ;

/// FFI: load a 128-bit value from `*src` into `*out`.
///
/// Both pointers must be non-null and point to at least 16 bytes. They
/// may alias; the load completes before the store.
pcsx2_ void pcsx2_r128_load(const uint32_t (*src)[4], uint32_t (*out)[4]) ;

/// FFI: store the 128-bit value at `*src` into `*dest`.
///
/// Both pointers must be non-null and point to at least 16 bytes. They
/// may alias; the load completes before the store.
pcsx2_ void pcsx2_r128_store(const uint32_t (*src)[4], uint32_t (*dest)[4]) ;

/// FFI: write a zero `R128` to `*out`.
///
/// `out` must be non-null and point to at least 16 writable bytes.
pcsx2_ void pcsx2_r128_zero(uint32_t (*out)[4]) ;

/// Read the file at `path` into a freshly-allocated buffer.
///
/// On success: returns `true` and writes the pointer + length to
/// `*out` / `*out_len`. The caller MUST release the buffer with
/// [`pcsx2_buffer_free`]. On failure: returns `false` and writes
/// `null` / `0` to the outputs.
pcsx2_ bool pcsx2_read_binary_file(const char *path, uint8_t **out, uintptr_t *out_len) ;

/// Free memory allocated by a COM API via `CoTaskMemFree`.
///
/// Wraps the Win32 `CoTaskMemFree` call.  Use with pointers
/// returned by COM methods that document "caller must free with
/// `CoTaskMemFree`".
///
/// # Safety
///
/// `ptr` must have been allocated by a COM API that uses the
/// task allocator.  Passing any other pointer is undefined
/// behaviour.
pcsx2_ void pcsx2_redtape_co_task_mem_free(void *ptr) ;

pcsx2_ bool pcsx2_rename_file(const char *old_path, const char *new_path) ;

/// Copy pixel data from the internal buffer to a pre-allocated destination.
/// Returns the number of bytes copied (0 if invalid or dst is null).
pcsx2_ uint32_t pcsx2_rgba_image_copy_pixels(const void *handle, uint8_t *dst, uint32_t dst_size) ;

/// Create an RGBA8Image (opaque handle = Box<Image>).
/// Returns null on OOM.
pcsx2_ void *pcsx2_rgba_image_create() ;

/// Destroy an RGBA8Image handle created by `pcsx2_rgba_image_create`.
pcsx2_ void pcsx2_rgba_image_destroy(void *handle) ;

/// Get image height.
pcsx2_ uint32_t pcsx2_rgba_image_get_height(const void *handle) ;

/// Returns the total byte count of the pixel buffer (width * height * 4).
pcsx2_ uint32_t pcsx2_rgba_image_get_pixel_count(const void *handle) ;

/// Get raw RGBA8 pixel pointer (internal buffer, do not free!).
/// Returns null if empty.
pcsx2_ const uint8_t *pcsx2_rgba_image_get_pixels(const void *handle) ;

/// Get image width.
pcsx2_ uint32_t pcsx2_rgba_image_get_width(const void *handle) ;

/// Returns true if the image has non-zero dimensions.
pcsx2_ bool pcsx2_rgba_image_is_valid(const void *handle) ;

/// Load image from buffer into an existing handle.
/// Replaces `RGBA8Image::LoadFromBuffer`.
/// Returns true on success.
pcsx2_ bool pcsx2_rgba_image_load_from_buffer(void *handle, const char *_format, const void *buffer, uint64_t size) ;

/// Load image from file into an existing handle.
/// Replaces `RGBA8Image::LoadFromFile`.
/// Returns true on success.
pcsx2_ bool pcsx2_rgba_image_load_from_file(void *handle, const char *path) ;

/// Save image from handle to an in-memory buffer.
/// Returns malloc'd buffer (caller must free with pcsx2_image_free).
/// `out_size` = byte count of encoded data.
/// Format auto-detected from extension string.
pcsx2_ uint8_t *pcsx2_rgba_image_save_to_buffer(void *handle, const char *format, uint8_t quality, uintptr_t *out_size) ;

/// Save image from handle to file.
/// Replaces `RGBA8Image::SaveToFile(const char*, u8)`.
/// Format auto-detected from extension.
pcsx2_ bool pcsx2_rgba_image_save_to_file(void *handle, const char *path, uint8_t quality) ;

/// Save image from handle to file (with FILE* — not supported, falls back to path).
/// Replaces `RGBA8Image::SaveToFile(const char*, FILE*, u8)`.
pcsx2_ bool pcsx2_rgba_image_save_to_file_ptr(void *handle, const char *path, void *_fp, uint8_t quality) ;

/// FFI export: sign-extend an `int32_t` to `__int128`.
///
/// Mirrors the C++ `s128::From32` static factory (which the C++ source
/// accidentally also labels `From64` — the Rust port fixes the name).
pcsx2_ i128 pcsx2_s128_from32(int32_t src) ;

/// FFI export: sign-extend an `int64_t` to `__int128`.
///
/// Mirrors the C++ `s128::From64` static factory.
pcsx2_ i128 pcsx2_s128_from64(int64_t src) ;

/// FFI export: allocate a new [`Semaphore`] with the given initial
/// count.
///
/// Returns a non-null pointer on success, or null if allocation
/// failed. The returned pointer must be released with
/// [`pcsx2_semaphore_destroy`].
pcsx2_ Semaphore *pcsx2_semaphore_create(int32_t initial) ;

/// FFI export: destroy a [`Semaphore`] previously created by
/// [`pcsx2_semaphore_create`].
///
/// Passing null is a no-op. Passing a double-freed or otherwise
/// invalid pointer is undefined behaviour.
pcsx2_ void pcsx2_semaphore_destroy(Semaphore *s) ;

/// FFI export: increment the semaphore counter by `count`, waking
/// waiters.
///
/// `count` is clamped at `i32::MAX` so the counter cannot overflow
/// silently. Negative values are treated as zero.
pcsx2_ void pcsx2_semaphore_post(Semaphore *s, int32_t count) ;

/// FFI export: block until the semaphore can be decremented, or
/// `timeout_ms` milliseconds have elapsed.
///
/// Returns true on success, false on timeout or invalid handle.
pcsx2_ bool pcsx2_semaphore_wait(Semaphore *s, uint32_t timeout_ms) ;

/// Set the current working directory.
pcsx2_ bool pcsx2_set_working_directory(const char *path) ;

/// FFI export: whether unaligned vector loads run at full speed.
///
/// Returns [`FAST_UNALIGNED`] as a C `bool`. The C++ side consumes
/// this alongside `pcsx2_simd_level` to decide which vector-emitter
/// path to take when unaligned memory is in play.
pcsx2_ bool pcsx2_simd_fast_unaligned() ;

/// FFI export: the highest SIMD ISA level this build supports.
///
/// Returns the packed `(major << 8) | minor` version, identical to
/// the `_M_SSE` macro value used by the C++ build. The C++ side can
/// compare the returned value against its own compile-time constant
/// to detect mismatches (e.g. Rust built with SSE 4.1 but C++ with
/// AVX2).
pcsx2_ uint32_t pcsx2_simd_level() ;

/// Allocate a new, empty `String` and return an opaque owning pointer.
///
/// The caller is responsible for calling
/// [`pcsx2_smallstring_destroy`] exactly once on the returned pointer.
pcsx2_ String *pcsx2_smallstring_create() ;

/// Return a pointer to the string's UTF-8 (NUL-terminated) payload.
///
/// The pointer is valid for the lifetime of the underlying `String`,
/// i.e. until the caller invokes
/// [`pcsx2_smallstring_destroy`] on the same handle. The C++ side
/// must not free or mutate the returned pointer; copying is fine.
pcsx2_ const char *pcsx2_smallstring_cstr(String *s) ;

/// Free a `String` previously allocated by
/// [`pcsx2_smallstring_create`] or
/// [`pcsx2_smallstring_from_cstr`].
///
/// Passing a null pointer is a no-op, matching the behaviour of `free`.
/// After this call, `s` must not be used again.
pcsx2_ void pcsx2_smallstring_destroy(String *s) ;

/// Allocate a new `String` initialised from a NUL-terminated C string
/// and return an opaque owning pointer.
///
/// Returns a null pointer if `s` is null.
pcsx2_ String *pcsx2_smallstring_from_cstr(const char *s) ;

/// Return the length of the string in bytes.
///
/// Returns 0 when `s` is null so the C++ side can probe uninitialised
/// handles without UB.
pcsx2_ uint32_t pcsx2_smallstring_length(String *s) ;

/// Capture up to `max_frames` stack frames and write them to a
/// heap-allocated buffer.
///
/// On success, allocates `count` `StackFrame` records, writes the
/// pointer into `*out_frames`, writes the count into `*out_count`,
/// and returns `true`.
///
/// The caller MUST release the buffer with [`pcsx2_stack_free`].
///
/// Returns `false` on invalid parameters or allocation failure.
pcsx2_ bool pcsx2_stack_capture(uint32_t max_frames, StackFrame **out_frames, uint32_t *out_count) ;

/// Free a buffer previously returned by [`pcsx2_stack_capture`].
///
/// Drops each `StackFrame` (freeing the inner `String` fields) and
/// deallocates the buffer. Passing `null` or `count == 0` is a no-op.
///
/// # Safety
///
/// `frames` must be a valid pointer from `pcsx2_stack_capture`, or null.
pcsx2_ void pcsx2_stack_free(StackFrame *frames, uint32_t count) ;

/// FFI: decode hex string.
pcsx2_ bool pcsx2_string_decode_hex(const char *input, uint8_t **out_data, uint32_t *out_len) ;

/// FFI: ellipsise (caller must free returned pointer).
pcsx2_ char *pcsx2_string_ellipsise(const char *str, uint32_t max_length, const char *ellipsis) ;

/// FFI: encode hex string (caller must free the returned pointer).
pcsx2_ char *pcsx2_string_encode_hex(const uint8_t *data, uint32_t length) ;

/// FFI: free a string allocated by Rust.
pcsx2_ void pcsx2_string_free(char *s) ;

/// FFI: free a byte buffer allocated by Rust.
pcsx2_ void pcsx2_string_free_buffer(uint8_t *buf, uint32_t len) ;

/// FFI: `from_chars_i32` for C strings.
pcsx2_ bool pcsx2_string_from_chars_i32(const char *s, int32_t *out) ;

/// FFI: format helper for C++ callers.
pcsx2_ uint32_t pcsx2_string_from_format(char *out, uint32_t out_len, const char *formatted) ;

/// FFI: case-insensitive compare for C strings.
pcsx2_ int32_t pcsx2_string_strcasecmp(const char *a, const char *b) ;

/// FFI: `strlcpy` for C strings.
pcsx2_ uint32_t pcsx2_string_strlcpy(char *dst, uint32_t dst_len, const char *src) ;

/// FFI: case-insensitive compare up to `n` bytes.
pcsx2_ int32_t pcsx2_string_strncasecmp(const char *a, const char *b, uint32_t n) ;

/// FFI: glob match for C strings.
pcsx2_ bool pcsx2_string_wildcard_match(const char *subject, const char *mask) ;

/// FFI: decompress a block-compressed image into a freshly allocated RGBA8
/// buffer.
///
/// Mirrors the C++ signature:
/// ```c
/// bool pcsx2_texture_decompress(uint32_t format,
///                               const uint8_t* src, uint32_t srcLen,
///                               uint32_t width, uint32_t height,
///                               uint8_t** out, uint32_t* outLen);
/// ```
///
/// On success `true` is returned and `*out` / `*outLen` are populated with
/// a heap allocation of `*outLen` bytes owned by the caller; free it with
/// [`pcsx2_texture_free`]. On failure (unknown format, null pointers, zero
/// dimensions, or a buffer-length mismatch) `false` is returned and the
/// out-parameters are left untouched so the caller can keep their previous
/// state.
///
/// # Safety
///
/// - `src` must point to `src_len` readable bytes (or be null with
///   `src_len == 0`).
/// - `out` and `out_len` must point to writable `*mut u8` / `*mut u32`
///   slots.
pcsx2_ bool pcsx2_texture_decompress(uint32_t format, const uint8_t *src, uint32_t src_len, uint32_t width, uint32_t height, uint8_t **out, uint32_t *out_len) ;

/// FFI: release an RGBA8 buffer previously returned by
/// [`pcsx2_texture_decompress`].
///
/// Mirrors the C++ signature:
/// ```c
/// void pcsx2_texture_free(uint8_t* data);
/// ```
///
/// The buffer is expected to be a payload pointer whose preceding 4 bytes
/// hold a little-endian `u32` length header (as written by
/// `pcsx2_texture_decompress`). Calling this with a null pointer is a
/// silent no-op, matching the C++ convention.
///
/// # Safety
///
/// `data` must either be null or a pointer previously returned by
/// [`pcsx2_texture_decompress`] that has not yet been freed. Double-freeing
/// the same pointer, or freeing an unrelated allocation, is undefined
/// behaviour.
pcsx2_ void pcsx2_texture_free(uint8_t *data) ;

/// FFI export: get the CPU time consumed by the current thread.
pcsx2_ uint64_t pcsx2_thread_get_cpu_time() ;

/// FFI: current thread's CPU time in microseconds (0 on failure).
pcsx2_ uint64_t pcsx2_thread_get_cpu_time() ;

/// FFI export: get the CPU time consumed by the current thread.
///
/// See [`get_thread_cpu_time`] for the unit convention.
pcsx2_ uint64_t pcsx2_thread_get_cpu_time() ;

/// FFI: current thread's CPU time in 100-ns FILETIME ticks.
///
/// Returns `0` on failure, matching the C++ source. Callers that
/// want seconds should divide by the value returned from
/// `pcsx2_thread_get_ticks_per_second()` (a separate FFI export
/// in the C++ source that lives in the platform-independent
/// `threading.rs` and is not re-implemented here).
pcsx2_ uint64_t pcsx2_thread_get_cpu_time() ;

/// FFI export: get the frequency of [`pcsx2_thread_get_cpu_time`].
pcsx2_ uint64_t pcsx2_thread_get_ticks_per_second() ;

/// FFI export: get the frequency of [`pcsx2_thread_get_cpu_time`].
///
/// Always 1_000_000 on Linux; see [`get_thread_ticks_per_second`].
pcsx2_ uint64_t pcsx2_thread_get_ticks_per_second() ;

/// FFI export: const-pointer variant of [`pcsx2_thread_handle_move`].
///
/// The C++ `ThreadHandle::operator=(const ThreadHandle&)` copies the
/// source by value, so callers may legitimately pass a `const
/// ThreadHandle*` on the source side. We expose both signatures so
/// both call sites (move ctor and copy assignment) resolve.
pcsx2_ void pcsx2_thread_handle_copy(void *dst, const void *src) ;

/// FFI export: move-construct a `Threading::ThreadHandle`.
///
/// Mirrors the C++ `Threading::ThreadHandle::ThreadHandle(ThreadHandle&&)`
/// move constructor. `dst` is a pointer to uninitialised memory of at
/// least `sizeof(ThreadHandle)` bytes; `src` is a pointer to the
/// source handle. After this call, `*dst` owns the OS handle and
/// `*src` is left in a valid-but-unspecified state (matching the
/// C++ post-condition of a moved-from object).
///
/// The C++ class layout is:
///   - `void* m_native_handle`  (8 bytes on 64-bit)
///   - `unsigned int m_native_id` on Linux only (4 bytes)
/// so `sizeof(ThreadHandle)` is 8 bytes on Windows/macOS and
/// 12 bytes on Linux. We copy `size_of::<usize>() + 4` bytes on
/// Linux, and `size_of::<usize>()` bytes elsewhere — covering the
/// full class without over-reading.
///
/// Passing either pointer as null is a no-op (we have no way to
/// report failure back to the caller, so we silently return).
pcsx2_ void pcsx2_thread_handle_move(void *dst, const void *src) ;

/// FFI export: set the current thread's name from a C string.
///
/// `name` must be a valid, null-terminated UTF-8 C string, or null.
/// A null pointer is treated as a no-op.
pcsx2_ void pcsx2_thread_set_name(const char *name) ;

/// FFI: set the current thread's name from a C string.
///
/// # Safety
/// `name` must be a valid NUL-terminated C string or null.
pcsx2_ void pcsx2_thread_set_name(const char *name) ;

/// FFI export: set the current thread's name from a C string.
///
/// `name` must be a valid, null-terminated UTF-8 C string, or null.
/// A null pointer is treated as a no-op. If the bytes are not valid
/// UTF-8 the call is also a no-op (the C++ side passes plain ASCII
/// in practice).
pcsx2_ void pcsx2_thread_set_name(const char *name) ;

/// FFI: set the current thread's name from a C string.
///
/// # Safety
/// `name` must be a valid NUL-terminated C string, or null (in
/// which case the call is a no-op).
pcsx2_ void pcsx2_thread_set_name(const char *name) ;

/// FFI export: sleep the current thread for `ms` milliseconds.
pcsx2_ void pcsx2_thread_sleep(uint32_t ms) ;

/// FFI: sleep the current thread for `ms` milliseconds.
pcsx2_ void pcsx2_thread_sleep(uint32_t ms) ;

/// FFI export: sleep the current thread for `ms` milliseconds.
pcsx2_ void pcsx2_thread_sleep(uint32_t ms) ;

/// FFI: sleep the current thread for `ms` milliseconds.
pcsx2_ void pcsx2_thread_sleep(uint32_t ms) ;

/// FFI export: sleep the current thread for `ticks` microseconds.
///
/// See [`sleep_until`] for the unit convention.
pcsx2_ void pcsx2_thread_sleep_until(uint64_t ticks) ;

/// FFI export: copy-construct a `OpaqueThreadHandle`.
///
/// Mirrors the C++ `Threading::ThreadHandle::ThreadHandle(const ThreadHandle&)`
/// copy constructor. The Windows copy ctor calls `DuplicateHandle`,
/// the POSIX version just copies the bytes; we replicate the POSIX
/// behaviour because the C++ side does the platform-specific work
/// via the `Threading` shim anyway.
///
/// `src` is a `*const` because the C++ copy ctor does not mutate
/// the source. Both pointers must be non-null and distinct.
pcsx2_ void pcsx2_threading_thread_handle_copy(OpaqueThreadHandle *dst, const OpaqueThreadHandle *src) ;

/// FFI export: release a `OpaqueThreadHandle` previously obtained
/// from [`pcsx2_threading_thread_handle_new`] (or a move/copy shim).
///
/// Passing null is a no-op. Passing a double-freed or otherwise
/// invalid pointer is undefined behaviour.
pcsx2_ void pcsx2_threading_thread_handle_destroy(OpaqueThreadHandle *h) ;

/// FFI export: move-construct a `OpaqueThreadHandle`.
///
/// Mirrors the C++ `Threading::ThreadHandle::ThreadHandle(ThreadHandle&&)`
/// move constructor. After this call `*dst` owns the OS handle and
/// `*src` is left in the default-constructed (zero) state, exactly
/// matching the post-condition of the C++ move ctor.
///
/// Both pointers must be non-null and point to distinct, valid
/// `OpaqueThreadHandle` instances. Passing null for either is a
/// silent no-op (we have no failure path back to the caller).
pcsx2_ void pcsx2_threading_thread_handle_move(OpaqueThreadHandle *dst, OpaqueThreadHandle *src) ;

/// FFI export: allocate a zero-initialised `OpaqueThreadHandle`.
///
/// Mirrors the C++ default-constructed `Threading::ThreadHandle`,
/// which has `m_native_handle = nullptr` and (on Linux) `m_native_id = 0`.
///
/// The returned pointer is owned by the caller and must be released
/// with [`pcsx2_threading_thread_handle_destroy`]. Returns null only
/// if the heap allocation fails (which the standard allocator never
/// does in practice on PCSX2-supported platforms).
pcsx2_ OpaqueThreadHandle *pcsx2_threading_thread_handle_new() ;

/// FFI export: blocking wait for work to be queued on a
/// `Threading::WorkSema`, spinning briefly before parking the
/// thread.
///
/// Mirrors `Threading::WorkSema::WaitForWorkWithSpin()`. The C++
/// implementation is a state machine on an `std::atomic<s32>` plus
/// two `KernelSemaphore` members; because the work-sema layout is
/// platform-dependent and not part of the FFI contract, we cannot
/// inspect the state directly from Rust.
///
/// The simplest correct body is a busy spin: the caller (the worker
/// thread) is blocked on this function until `NotifyOfWork` flips
/// the state. The C++ `NotifyOfWork` path runs on a producer
/// thread, not on the consumer, so a busy spin on the consumer
/// side is the safest placeholder. Once the producer has called
/// `NotifyOfWork`, the state transitions from `STATE_RUNNING_0` (or
/// similar) to `STATE_RUNNING_N` and the C++ side of the consumer
/// (which is the FFI caller, not this Rust function) reads the new
/// state and proceeds.
///
/// This stub satisfies the linker: the symbol exists with the
/// expected C calling convention, so C++ code compiled against the
/// Rust port will resolve `pcsx2_threading_work_sema_wait_for_work_with_spin`
/// without needing the C++ `common/Semaphore.cpp` translation unit.
/// The proper `Condvar`-backed implementation can be slotted in
/// later without changing the public FFI surface.
///
/// A null pointer is a silent no-op (the C++ version would crash
/// on a null deref, so this is strictly safer).
pcsx2_ void pcsx2_threading_work_sema_wait_for_work_with_spin(void *sema) ;

/// C ABI: returns the raw CPU cycle counter.
pcsx2_ uint64_t pcsx2_timer_get_cpu_ticks() ;

/// C ABI: returns the monotonic tick frequency (ticks per second).
pcsx2_ uint64_t pcsx2_timer_get_tick_frequency() ;

/// C ABI: returns the current monotonic tick value.
pcsx2_ uint64_t pcsx2_timer_get_ticks() ;

/// FFI export: zero-extend a `uint32_t` to `unsigned __int128`.
///
/// Mirrors the C++ `u128::From32` static factory.
pcsx2_ u128 pcsx2_u128_from32(uint32_t src) ;

/// FFI export: zero-extend a `uint64_t` to `unsigned __int128`.
///
/// Mirrors the C++ `u128::From64` static factory.
pcsx2_ u128 pcsx2_u128_from64(uint64_t src) ;

/// FFI: create a new [`WavWriter`] for the file at `path`.
///
/// Returns a non-null owning pointer on success and a null pointer
/// on any failure (invalid UTF-8 path, file-creation error, header
/// write error). Mirrors the C++ `Common::WAVWriter::Open`.
///
/// # Safety
///
/// - `path` must be a NUL-terminated C string or null. A null
///   pointer is treated as a failure (returns null) rather than
///   UB.
pcsx2_ WavWriter *pcsx2_wav_writer_create(const char *path, uint32_t sample_rate, uint16_t channels, uint16_t bits_per_sample) ;

/// FFI: finalize the writer, flushing the header to disk, and free
/// the box.
///
/// Equivalent to `Box::from_raw(w).finalize()` with a null-pointer
/// fast path. After this returns `w` is dangling and must not be
/// used again; the file on disk is closed and the RIFF header
/// reports the correct byte count.
///
/// Errors from `finalize` are silently swallowed (the file is
/// closed in either case). This mirrors the C++ destructor, which
/// also logs and continues rather than aborting on a failed
/// header rewrite.
///
/// # Safety
///
/// - `w` must be a pointer returned by
///   [`pcsx2_wav_writer_create`], or null (in which case the call
///   is a no-op).
pcsx2_ void pcsx2_wav_writer_destroy(WavWriter *w) ;

/// FFI: write `count` interleaved i16 samples to the writer.
///
/// Returns `true` on success and `false` on I/O error or invalid
/// arguments. Mirrors the C++ `Common::WAVWriter::WriteFrames`,
/// except that the success/failure of the write is propagated
/// instead of just being logged via `Console.Error`.
///
/// # Safety
///
/// - `w` must be a non-null pointer returned by
///   [`pcsx2_wav_writer_create`] and not yet passed to
///   [`pcsx2_wav_writer_destroy`].
/// - `samples` must point to `count` readable `i16` values, or be
///   null when `count == 0`. A null pointer with `count > 0` is
///   treated as a failure.
pcsx2_ bool pcsx2_wav_writer_write(WavWriter *w, const int16_t *samples, uint32_t count) ;

/// Heap-allocate a default [`WindowInfo`] and return an owning raw pointer.
///
/// The returned pointer must be released with
/// [`pcsx2_window_info_destroy`]. On allocation failure the C++ side's
/// allocator returns `null`, so callers must check the result.
///
/// This is the C-ABI twin of `new WindowInfo()` — the C++ side uses it
/// to construct instances without linking the Rust allocator into its
/// own heap.
pcsx2_ WindowInfo *pcsx2_window_info_create() ;

/// Free a [`WindowInfo`] previously allocated by
/// [`pcsx2_window_info_create`].
///
/// Passing `null` is a no-op so C++ callers don't have to special-case
/// the "wasn't allocated" path. Passing a pointer not produced by
/// [`pcsx2_window_info_create`] is undefined behaviour, matching
/// `delete` semantics.
pcsx2_ void pcsx2_window_info_destroy(WindowInfo *w) ;

/// Register (or acknowledge readiness for) the raw-input mouse
/// position callback.
///
/// The C++ side uses raw input messages (handled by the Windows
/// message loop) rather than a low-level mouse hook. This function
/// simply returns `true` to indicate the mechanism is available.
pcsx2_ bool pcsx2_windows_attach_mouse_position_cb() ;

/// Detach / unregister the mouse position callback.
///
/// The C++ side has no teardown work because it uses raw input
/// messages; this is a no-op.
pcsx2_ void pcsx2_windows_detach_mouse_position_cb() ;

/// Enable or disable the screensaver.
///
/// Mirrors the C++ `Common::InhibitScreensaver(bool inhibit)`.
/// When `inhibit` is `true`, calls `SetThreadExecutionState` with
/// `ES_CONTINUOUS | ES_DISPLAY_REQUIRED` to prevent the display
/// from powering off. Returns `true` on success.
pcsx2_ bool pcsx2_windows_inhibit_screensaver(bool inhibit) ;

/// Play a WAV file asynchronously through `PlaySoundW`.
///
/// Mirrors the C++ `Common::PlaySoundAsync(const char* path)`.
/// Expects a null-terminated UTF-8 path. Converts to wide chars
/// internally and calls `PlaySoundW` with `SND_ASYNC | SND_NODEFAULT`.
/// Returns `true` if the sound started successfully.
pcsx2_ bool pcsx2_windows_play_sound_async(const char *path) ;

/// Move the mouse cursor to the specified screen coordinates.
///
/// Mirrors the C++ `Common::SetMousePosition(int x, int y)`.
/// Calls `SetCursorPos` under the hood.
pcsx2_ void pcsx2_windows_set_mouse_position(int32_t x, int32_t y) ;

/// FFI export: wait for work to be queued on a `WorkSema`, with a
/// brief spin before sleeping.
///
/// Mirrors `Threading::WorkSema::WaitForWorkWithSpin()`. The C++
/// version spins on the atomic state a few times, then sleeps on
/// `m_sema` until `NotifyOfWork` is called.
///
/// Because the `WorkSema` is a C++-managed object whose internal
/// layout (two `KernelSemaphore` plus an `std::atomic<s32>`) is not
/// part of the FFI contract, we cannot inspect the state directly
/// from Rust. We instead provide a best-effort stub: emit a short
/// spin hint and return `true`, signalling to the caller that work
/// is available. The C++ side treats the return value as "got
/// work, proceed", which matches the contract when the producer
/// has already called `NotifyOfWork` before the consumer spins.
///
/// A null pointer returns `false` (the C++ version would crash on
/// a null deref, so this is strictly safer).
pcsx2_ bool pcsx2_work_sema_wait_for_work_with_spin(void *sema) ;

/// Write `len` bytes from `data` to `path`, overwriting if it exists.
pcsx2_ bool pcsx2_write_binary_file(const char *path, const uint8_t *data, uintptr_t len) ;

/// Free a buffer previously returned by [`pcsx2_yaml_load_file`].
///
/// Passing a null pointer is a no-op (matches the C convention used by
/// `free`).
///
/// # Safety
/// - `data` must either be null or have been allocated by
///   [`pcsx2_yaml_load_file`].
/// - `len` must match the length that was reported in `out_len`.
/// - After this call, `data` is invalid and must not be used.
pcsx2_ void pcsx2_yaml_free(uint8_t *data, uintptr_t len) ;

/// Read a UTF-8 file path and return its contents as a heap-allocated
/// UTF-8 byte buffer.
///
/// On success, the returned pointer points to a buffer of `*out_len` bytes
/// that the caller **must** release with [`pcsx2_yaml_free`]. On failure,
/// the function returns a null pointer.
///
/// # Safety
/// - `path` must be a valid null-terminated C string.
/// - `out_len` must be a valid, non-null pointer to a `usize`.
pcsx2_ uint8_t *pcsx2_yaml_load_file(const char *path, uintptr_t *out_len) ;

/// FFI: zero 16 bytes at `dest`.
///
/// `dest` must point to at least 16 writable bytes.
pcsx2_ void pcsx2_zero_qwc(uint8_t *dest) ;

pcsx2_ bool pcsx2_zip_extract(const char *archive, const char *dest_dir) ;

pcsx2_ bool pcsx2_zip_list(const char *archive, uint32_t *out_count, char ***out_names) ;

extern mach_port_t pthread_mach_thread_np(pthread_t thread);

extern int setjmp(JmpBuf *env);

extern int thread_info(mach_port_t target_act, int flavor, thread_info_t thread_info_out, mach_msg_type_number_t *thread_info_outCnt);

}  // extern "C"

}  // namespace pcsx2

#endif  // PCSX2_COMMON_RS_H
